### PR TITLE
Add Presto function at_timezone for Timestamp type

### PR DESCRIPTION
**Pull request by svm1**

### CODE REVIEW

**Review by majetideepak — COMMENTED** [review]
@svm1 I do not see an `at_timezone` function for Timestamp input on the Presto side. Can you share a link to the implementation?

**Comment by svm1** [comment]
@majetideepak I do not see one in Presto Java either - though passing in just a Timestamp does work there. 

```
SELECT timestamp '2012-10-31 01:00' AT TIME ZONE 'America/Denver';
                 _col0                  
----------------------------------------
 2012-10-30 19:00:00.000 America/Denver 
(1 row)
```

I think when a Timestamp is passed in, it's implicitly casted to a TimestampWithTimezone with timezone UTC, hence the same output here:

```
SELECT timestamp '2012-10-31 01:00 UTC' AT TIME ZONE 'America/Denver';
                 _col0                  
----------------------------------------
 2012-10-30 19:00:00.000 America/Denver 
(1 row)
```

I'd think this conversion might be happening at the parser level, so no Velox signature for Timestamp would actually be necessary.

**Comment by svm1** [comment]
@majetideepak I take back my last comment above - the reason I wrote this implementation for `Timestamp` input in the first place was because I noticed that passing a Timestamp in to `at_timezone()` in Presto Java results in the input Timestamp being interpreted as a `TimestampWithTimezone`, with the Timestamp being interpreted as a wall-clock at the current session timezone. As there is no direct function for this in Presto Java, I am not sure where exactly this is happening; likely an implicit cast at some point prior to hitting the function.

Therefore, I wrote this for Velox to replicate the same functionality here.

**Comment by majetideepak** [comment]
>  that passing a Timestamp in to at_timezone() in Presto Java results in the input Timestamp being interpreted as a TimestampWithTimezone

@svm1 can you confirm that by putting a break point inside the at_timezone() implementation for TimestampWithTimezone?

**Comment by svm1** [comment]
@majetideepak Yes, I can do so. I haven't been able to do so yet due to issues with my Presto Java debug build, but I'll look into that to verify the observations.

**Comment by svm1** [comment]
@majetideepak I was able to debug Presto Java and confirm that calling at_timezone() on a `Timestamp` results in it being implicitly casted as a `TimestampWithTimezone` before hitting the function. It looks like this conversion is happening at the parser level, likely by the coordinator's constant folding.

Query plan confirms as well:
```
presto:tpch> explain select a at time zone 'America/Denver' from (values (TIMESTAMP '2012-11-30 01:00')) t(a);
                                                     Query Plan                                                     
--------------------------------------------------------------------------------------------------------------------
 - Output[PlanNodeId 8][_col0] => [expr_2:timestamp with time zone]                                                 
         Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 18.00, memory: 0.00, network: 0.00}            
         _col0 := expr_2 (1:18)                                                                                     
     - Project[PlanNodeId 4][projectLocality = LOCAL] => [expr_2:timestamp with time zone]                          
             Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 18.00, memory: 0.00, network: 0.00}        
             expr_2 := at_timezone(CAST(field AS timestamp with time zone), VARCHAR'America/Denver') (1:55)         
         - LocalExchange[PlanNodeId 170][ROUND_ROBIN] () => [field:timestamp]                                       
                 Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 9.00, memory: 0.00, network: 0.00}     
             - Values[PlanNodeId 0] => [field:timestamp]                                                            
                     Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00, network: 0.00} 
                     (TIMESTAMP'2012-11-30 01:00:00.000')  
```

So this PR's implementation would indeed be unnecessary - I will close it.

**Pull request closed without merging**
