### PR TITLE
Update FBOS to v2024.07.01

### PR DESCRIPTION
**Pull request by czentgr**

### CODE REVIEW

**Comment by czentgr** [comment]
@majetideepak My adapters image still has issues with the GCS tests but I think we can show that upgrading FBOS works fine as everything else passes.

Turns out the way I built the adapter container can't set the right conda environment and it just installs the testbench to the default env.

```
--> cd56c5d7dad3
STEP 8/15: SHELL ["mamba", "run", "-n", "adapters", "/bin/bash", "-c"]
time="2024-09-30T10:13:17-07:00" level=warning msg="SHELL is not supported for OCI image format, [mamba run -n adapters /bin/bash -c] will be ignored. Must use `docker` format"
--> 54ba5de2a294
```
which then results in the gcs test failure due to the missing pip dependency of testbench
```
 /opt/miniforge/envs/adapters/bin/python3: No module named testbench
```

**Comment by czentgr** [comment]
@majetideepak @assignUser Please review. I will remove the last commit that changes the adapter images that used the new folly version now that we had a clean run.

**Review by majetideepak — APPROVED** [review]
Thanks, @czentgr.

**Comment by majetideepak** [comment]
I will add the merge tag once the last commit has been removed.

**Review by assignUser — APPROVED** [review]

**Review by kgpai — APPROVED** [review]
Thanks @czentgr

**Pull request closed without merging**
