### PR TITLE
Remove obsolete setup-velox-torcharrow.sh

### PR DESCRIPTION
**Pull request by pedroerp**
According to discussion on:
https://github.com/facebookincubator/velox/pull/8950#discussion_r1512167973

### CODE REVIEW

**Comment by majetideepak** [comment]
I see `setup-velox-torcharrow.sh` being used here https://github.com/facebookincubator/velox/blob/f696b569d8f199aea150164e97e6ca0e672c775d/scripts/velox-torcharrow-container.dockfile#L19

**Comment by majetideepak** [comment]
I found this since CI failed in my PR https://github.com/facebookincubator/velox/actions/runs/8167751354/job/22328669824?pr=8943

**Comment by pedroerp** [comment]
> I found this since CI failed in my PR https://github.com/facebookincubator/velox/actions/runs/8167751354/job/22328669824?pr=8943

Ughh, looks like the torcharrow docker image generated is used by pyvelox. I reached out to you guys on Slack to figure out what to do with it.

**Comment by kgpai** [comment]
We need to remove some of these references to torcharrow , Its not required anymore. - this includes the torcharrow dockerimage which uses manylinux2014 which is going eol in june. We will also need to remove the pyvelox wheel jobs that use these scripts/images etc.

**Pull request closed without merging**
