### PR TITLE
Remove extra copy of inline strings in CAST(DECIMAL as VARCHAR)

### PR DESCRIPTION
**Pull request by rui-mo**
This PR writes inline strings directly to the vector's values buffer. This 
buffer has 16 bytes slots, one per value. First 4 bytes store string size, the 
remaining 12 bytes store the string. In this way, extra copy of inline strings 
can be removed. Benchmark shows close performance after this change.

Benchmark  | Before | After
-- | -- | --
cast_decimal_to_inline_string | 8.29ms | 8.24ms

### CODE REVIEW

**Review by mbasmanova — COMMENTED** [review]
@rui-mo Rui, thank you for experimenting. Since there is not much performance win, maybe the additional complexity is not worth it. What do you think?

**Comment by rui-mo** [comment]
@mbasmanova I tried to enlarge the vector size of benchmark as `100'000'000`, and below was the benchmark result. Is the improvement limited with the consideration of additional complexity? If so, we can close this PR.

Benchmark  | Before | After
-- | -- | --
cast_decimal_to_inline_string | 22.49s | 21.67s

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for benchmarking. 100M row vectors seem not very practical. I'd say we can close this PR since the improvement is not significant.

**Comment by rui-mo** [comment]
@mbasmanova Makes sense to me. Let's close this PR. Thank you.

**Pull request closed without merging**
