### PR TITLE
Add support for decimal keys to DistinctAggregations

### PR DESCRIPTION
**Pull request by zhli1142015**
Fixes: #9839

### CODE REVIEW

**Comment by zhli1142015** [comment]
I checked the failures below are not related to this change, cc @mbasmanova , thanks.
https://github.com/facebookincubator/velox/issues/9853
```
E20240517 10:41:10.367101 133060 Exceptions.h:69] Line: /home/runner/work/velox/velox/velox/velox/exec/ExchangeQueue.cpp:103, Function:dequeueLocked, Expression:  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Forced failure after 11 pages
Retriable: False
Function: operator()
File: /home/runner/work/velox/velox/velox/velox/exec/tests/MultiFragmentTest.cpp
Line: 1855
```
https://github.com/facebookincubator/velox/issues/9854
```
[ RUN      ] SharedArbitrationTest.skipNonReclaimableTaskTest
terminate called after throwing an instance of 'facebook::velox::VeloxUserError'
  what():  Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Scalar function doesn't exist: sum.
Retriable: False
Function: resolveScalarFunctionType
File: /home/runner/work/velox/velox/velox/velox/parse/TypeResolver.cpp
Line: 96
Stack trace:
Stack trace has been disabled. Use --velox_exception_user_stacktrace_enabled=true to enable it.
```

**Comment by zhli1142015** [comment]
> @zhli1142015 HUGEINT is used for decimal type, hence, you are adding support for decimal types. Please, update PR title accordingly. Would you add a test?

Updated test to cover long decimal type, thanks.

**Comment by zhli1142015** [comment]
@kgpai and @mbasmanova , could you help to check this PR? Thanks.

**Review by mbasmanova — APPROVED** [review]
Looks good to me. Thanks.

**Review by Yuhta — APPROVED** [review]

**Pull request closed without merging**
