### PR TITLE
Move unit tests from Arrow Parquet writer

### PR DESCRIPTION
**Pull request by pedroerp**
Summary:
Moving unit tests from Arrow Parquet to our recently vendored code.
Also moving Parquet reader codebase into the test directory, since most unit
tests need both a writer and a reader. We will refactor them to use our native
reader in the next PRs.

Differential Revision: D49780809

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]
Thanks, @pedroerp

**Review by xiaoxmeng — APPROVED** [review]
@pedroerp thanks!

**Comment by pedroerp** [comment]
> @xiaoxmeng Can you please help land this PR?

I'm merging it. Just waiting until CI is ready

**Comment by majetideepak** [comment]
Thanks, @pedroerp!

**Comment by majetideepak** [comment]
Filed https://github.com/facebookincubator/velox/issues/7963 to use the native parquet reader in the tests.

**Pull request closed without merging**
