### PR TITLE
Handle real type in AverageAggregation

### PR DESCRIPTION
**Pull request by frankobe**
PR to address https://github.com/facebookincubator/velox/issues/974.

In Presto, the order of argument `sum` & `count` is different in the intermediate step `avg` function between `real` type and other type like

```
- Aggregate(FINAL) => [avg_1:real, avg:double]
                    avg_1 := "presto.default.avg"((avg_11)) (1:66)
                    avg := "presto.default.avg"((avg_10)) (1:35)
                - LocalExchange[SINGLE] () => [avg_11:row("field0" bigint, "field1" double), avg_10:row("field0" double, "field1" bigint)]
                    - RemoteSource[1] => [avg_11:row("field0" bigint, "field1" double), avg_10:row("field0" double, "field1" bigint)]
```

Current Velox implementation assumes the `avg` function signature as `avg(sum:double, count:bigint)`.

This PR registers the `avg(count:bigint, sum:double)` for `real` type and decode the input of `extractAccumulators`, `addIntermediateResults`, `addSingleGroupIntermediateResults` based on the child type to handle both cases

Signed-off-by: frankobe <frank.hu@bytedance.com>

### CODE REVIEW

**Comment by frankobe** [comment]
@spershin Any chance you can review this pull request?

**Comment by aditi-pandit** [comment]
Hi Frank, Not to increase work for you but I have a qq about your solution. In https://github.com/facebookexternal/presto_cpp/blob/52bfe00df137655aee87afcb148168704c62583d/presto_cpp/main/types/PrestoToVeloxExpr.cpp#L338 Presto Expressions are modified to Velox expressions. I feel it might be sufficient to have a special case in this logic for avg aggregation that reverses the order of the arguments for real type. Did you try that approach ? wdyt ?

**Comment by spershin** [comment]
@frankobe 
We are working with Presto team at the moment to see if we can fix that on Presto's side.

**Comment by mbasmanova** [comment]
More discussion in https://github.com/prestodb/presto/pull/17339

**Comment by highker** [comment]
Replied https://github.com/prestodb/presto/pull/17339#issuecomment-1055907845

**Comment by mbasmanova** [comment]
@frankobe Frank, https://github.com/prestodb/presto/pull/17386 changes intermediate type of avg(real) in Presto to match avg for all other input types.

**Comment by mbasmanova** [comment]
> @mbasmanova Great! I will modify this PR to change final type to `REAL` only

I believe Sergey has a PR to do that already: https://github.com/facebookincubator/velox/pull/1108

**Comment by mbasmanova** [comment]
Closing stale PRs. Please, reopen if you'd like to continue working on this PR.

**Pull request closed without merging**
