### PR TITLE
Fix undefined reference to typeinfo for ZeroCopyOutputStream

### PR DESCRIPTION
**Pull request by yingsu00**

### CODE REVIEW

**Comment by yingsu00** [comment]
@kgpai @pedroerp Can you please review and merge this PR? @gaoyangxiaozhu has confirmed it fixed his build issue in https://github.com/facebookincubator/velox/issues/6641. Thank you!

cc @nmahadevuni

**Comment by majetideepak** [comment]
@yingsu00 I opened https://github.com/facebookincubator/velox/pull/7109 to remove the Protobuf dependency on Parquet.

**Comment by nmahadevuni** [comment]
@yingsu00 I already fixed this in https://github.com/facebookincubator/velox/pull/6863

**Comment by nmahadevuni** [comment]
> @yingsu00 I opened #7109 to remove the Protobuf dependency on Parquet.

@majetideepak The refactor was done to use the common compressor logic for Parquet in the future too. @yingsu00

**Comment by majetideepak** [comment]
@nmahadevuni The Parquet compression logic does not need Protobuf streams. I modified the API to address this.
We started reusing compression here https://github.com/facebookincubator/velox/pull/7028

**Comment by majetideepak** [comment]
This should be resolved with https://github.com/facebookincubator/velox/pull/7109

**Comment by majetideepak** [comment]
My bad, I thought this was the issue. Feel free to reopen if this PR is still needed.

**Pull request closed without merging**
