### PR TITLE
Add a way to keep RuntimeMetric::count at 1.

### PR DESCRIPTION
**Pull request by spershin**
Summary:
For some cases we want RuntimeMetric per entity (Operator),
not per event (like load a lazy vector).
This is to understand the overall metric for a single Driver, so
we can quickly identify a potentical cause for slowness (f.e.).
In this diff we add this ability, defaulting to the old way of
increasing 'count' every time we add a value.
We change two counters to keep the 'count' at 1:
"dataSourceWallNanos" and "dataSourceLazyWallNanos".
This will allow us to see if at least one Driver/thread was in
a bottleneck reading the data.

Differential Revision: D44175164

### CODE REVIEW

**Review by xiaoxmeng — COMMENTED** [review]
@spershin thanks for change. Why not we do the merge when we report in case we need? For instance, we can just merge all the updates from one operator as one at cpp?

**Comment by spershin** [comment]
> @spershin thanks for change. Why not we do the merge when we report in case we need? For instance, we can just merge all the updates from one operator as one at cpp?

@xiaoxmeng 
I have considered this.
And I decided against this because I believe it is good to have a clear understanding on how we collect a counter. Does it make sense to collect it per event or per entity. And this is done best at the collection site, rather than at some site that is disconnected from the collection (report).
On top of that there are more stats that would benefit from collection per operator (basically per thread/Driver) than just these two.
Having some special case code resetting their counter to 1 looks like a hack to me. :)

**Comment by xiaoxmeng** [comment]
> > @spershin thanks for change. Why not we do the merge when we report in case we need? For instance, we can just merge all the updates from one operator as one at cpp?
> 
> @xiaoxmeng I have considered this. And I decided against this because I believe it is good to have a clear understanding on how we collect a counter. Does it make sense to collect it per event or per entity. And this is done best at the collection site, rather than at some site that is disconnected from the collection (report). On top of that there are more stats that would benefit from collection per operator (basically per thread/Driver) than just these two. Having some special case code resetting their counter to 1 looks like a hack to me. :)

@spershin
The approach in this PR is to pass a flag at every stats update call site with default set to false. It seems to be error prone if we call the same stats update with different flag. And is also equivalent to just add a method: RuntimeMetric::aggregate() and call that for specific stats in Presto CPP that we want to merge all the stats updates from one operator as a single one?
```
RuntimeMetric::aggregate() {
  count = std::max(count, 1);
  min = sum;
  max = sum;
}
```

**Comment by spershin** [comment]
Abandon for different solution: https://github.com/facebookincubator/velox/pull/4376

**Pull request closed without merging**
