### PR TITLE
Fix the path to copy hive.properties from scripts

### PR DESCRIPTION
**Pull request by rui-mo**
hive.properties has been moved to scripts/presto/etc. We need to update the 
path to copy it from.

### CODE REVIEW

**Comment by rui-mo** [comment]
I notice failures of fuzzer test after merging https://github.com/facebookincubator/velox/pull/9759 due to wrong file path
https://github.com/facebookincubator/velox/actions/runs/9278395956/job/25530734997?pr=9937. This PR is to fix it. Sorry for the inconvenience.
cc: @kgpai @assignUser @Yuhta

**Review by xiaoxmeng — APPROVED** [review]
@rui-mo thanks!

**Review by assignUser — APPROVED** [review]
Thanks, CI is not finished but the changed code ran already. :+1:

**Review by kgpai — APPROVED** [review]

**Comment by rui-mo** [comment]
Thank you for the quick response!

**Pull request closed without merging**
