### PR TITLE
Register re-usable Presto date_trunc functions for Spark

### PR DESCRIPTION
**Pull request by zml1206**
As title, It tested in https://github.com/apache/incubator-gluten/pull/7611

### CODE REVIEW

**Comment by zml1206** [comment]
cc @rui-mo Can you help take a look, thank you.

**Review by rui-mo — COMMENTED** [review]
Given these limitations in Gluten, I assume we need to implement a separate date_trunc function for Spark, and cannot just reuse the Presto one. Thanks!

https://github.com/apache/incubator-gluten/pull/7611/files#diff-0459e833e435d59a9614f196f6ed31070a848b3f5067bf17d7e37f09e6c5e604R53-R59

**Comment by rui-mo** [comment]
@zml1206 If there are semantic differences, a separate implementation would be needed, and we attempt to cover all cases that Spark requires. Thanks.

**Comment by zml1206** [comment]
> @zml1206 If there are semantic differences, a separate implementation would be needed, and we attempt to cover all cases that Spark requires. Thanks.

Got it, I submitted a new PR #11340, please take a look again, thank you

**Pull request closed without merging**
