### PR TITLE
Force openssl@1.1 path.

### PR DESCRIPTION
**Pull request by kgpai**
Probable fix for issue : https://github.com/facebookincubator/velox/issues/5421 .

### CODE REVIEW

**Comment by mbasmanova** [comment]
@majetideepak Deepak, would you help review this change?

**Comment by majetideepak** [comment]
@mbasmanova sure. I am looking at the actual issue.

**Comment by majetideepak** [comment]
@kgpai I feel https://github.com/facebookincubator/velox/pull/5361 is a better fix and it solves non CI environments as well. Can we merge that?

**Comment by kgpai** [comment]
@majetideepak if #5361 solves the issue, please feel free to go ahead with that.

**Comment by majetideepak** [comment]
@kgpai, @mbasmanova I opened a PR here https://github.com/facebookincubator/velox/pull/5428 using the fix #5361 from on the latest main. If that passes CI, let's merge that.

**Comment by mbasmanova** [comment]
Thank you, Deepak. Let's see if CI passes.

**Comment by majetideepak** [comment]
@mbasmanova Let's merge this PR as it fixes the CI issue. The other PR https://github.com/facebookincubator/velox/pull/5361 did not fix CI. We will look into that.

**Review by majetideepak — APPROVED** [review]

**Comment by 652053395** [comment]
> Probable fix for issue : #5421 .

@kgpai  hi, I still meet this problem , " error: 'HMAC_CTX_free' is deprecated ", ask for your help

**Comment by kgpai** [comment]
@652053395 Can you create an issue with more details - like the cmake logs and error message etc. Please tag me on the issue and I will try to help you out there.

**Pull request closed without merging**
