### PR TITLE
Cosmetic refactor on merge join supported types

### PR DESCRIPTION
**Pull request by pedroerp**
Summary: Cosmetic refactor on merge join supported types

Differential Revision: D59252668

### CODE REVIEW

**Comment by pedroerp** [comment]
Cc: @JkSelf @PHILO-HE

**Review by JkSelf — APPROVED** [review]
Thanks for your fix. LGTM.

**Review by PHILO-HE — COMMENTED** [review]
Looks nice! Thanks!

**Review by xiaoxmeng — APPROVED** [review]
@pedroerp thanks!

**Pull request closed without merging**
