### PR TITLE
Fix imcompatible between presto and velox when hash double/float -0.0

### PR DESCRIPTION
**Pull request by shenh062326**
For double/float -0.0 and 0.0, folly::hasher will return the same value.
but in presto/mysql, the return hash values are not equal. We should firstly
cast double/float to longBits, then call folly::hasher to get hash value.

### CODE REVIEW

**Comment by Yuhta** [comment]
@bikramSingh91 @rschlussel Similar to NaN, how does Presto treat 0.0 and -0.0?  It seems 0.0 = -0.0 returns true, but during join/groupby they are treated differently?  Should we add this to our plan of NaN unification?

**Comment by spershin** [comment]
Agree that we need 1st to check what we want it to be in Presto.
Also, just curious, since bit representation of 0.0 and -0.0 look different, does folly::hasher() performa an extra check to return the same hash for 0.0 and -0.0?

**Comment by bikramSingh91** [comment]
> does folly::hasher() performa an extra check to return the same hash for 0.0 and -0.0?

@spershin thats probably true based on this comment in folly


https://github.com/facebook/folly/blob/427a1ef2c1641e0cfaec5c9300487d084175b00e/folly/Range.h#L1664-L1665

**Comment by rschlussel** [comment]
> @bikramSingh91 @rschlussel Similar to NaN, how does Presto treat 0.0 and -0.0? It seems 0.0 = -0.0 returns true, but during join/groupby they are treated differently? Should we add this to our plan of NaN unification?

do you have an example query to reproduce this?  Earlier I had the same suspicion about group by and tried to test it out, but didn't see the behavior you are describing.

**Comment by Yuhta** [comment]
@rschlussel 
```sql
> select 0.0 = -0.0;
 _col0
-------
 true
> WITH t as (SELECT * FROM unnest(array[0.0, -0.0], array[1, 2]) as _t(k, v)) select * from t join t as t2 on t.k = t2.k;
  k   | v |  k   | v
------+---+------+---
  0.0 | 1 |  0.0 | 1
 -0.0 | 2 | -0.0 | 2
(2 rows)
```

**Comment by rui-mo** [comment]
cc: @zhli1142015

**Comment by zhli1142015** [comment]
> With this change, do we need to normalize -0.0 and 0.0 in #9272 for Spark? @zhli1142015

Yes, then we need to also normalize -0.0 and 0.0.

**Comment by shenh062326** [comment]
This is the behavior of mysql, it won't aggregate -0 and 0.
```
mysql> create table double_basic_test_2(id int,col1 double,col2 double) ;
Query OK, 0 rows affected (0.04 sec)

mysql> insert into double_basic_test_2 values(6,'0','-0');
Query OK, 1 row affected (0.04 sec)

mysql> insert into double_basic_test_2 values(5,0,0);
Query OK, 1 row affected (0.04 sec)

mysql> select sum(id),col2 from double_basic_test_2 group by col2;
+---------+------+
| sum(id) | col2 |
+---------+------+
|       6 |   -0 |
|       5 |    0 |
+---------+------+
2 rows in set (0.03 sec)
```

**Comment by aditi-pandit** [comment]
@czentgr, @karteekmurthys

**Pull request closed without merging**
