### PR TITLE
Remove useless variable of VELOX_BUILD_BENCHMARKS_LARGE

### PR DESCRIPTION
**Pull request by leoluan2009**
Remove useless variable of VELOX_BUILD_BENCHMARKS_LARGE for https://github.com/facebookincubator/velox/issues/2448

### CODE REVIEW

**Comment by leoluan2009** [comment]
cc @majetideepak

**Review by majetideepak — APPROVED** [review]
Thanks @leoluan2009

**Comment by majetideepak** [comment]
@kgpai @Yuhta can you please merge this? Thanks.

**Comment by leoluan2009** [comment]
@majetideepak  Thanks!

**Pull request closed without merging**
