### PR TITLE
Allow choosing to register companion functions for all aggregate functions

### PR DESCRIPTION
**Pull request by liujiayi771**
This change allow Spark to use companion functions of all aggregate functions.

### CODE REVIEW

**Comment by liujiayi771** [comment]
Hi @kagamiori. Would you help review this PR?

**Comment by liujiayi771** [comment]
cc @mbasmanova, thanks.

**Review by mbasmanova — COMMENTED** [review]
@liujiayi771 Would it be possible to make this change for all aggregate functions?

Is it the case that set_agg semantics in Presto and Spark are the same?

CC: @kagamiori

**Comment by liujiayi771** [comment]
@mbasmanova 
> Would it be possible to make this change for all aggregate functions?

Yes. Gluten needs to use companion functions of all aggregate functions. Would you recommend that I add all of them in this PR?

> Is it the case that set_agg semantics in Presto and Spark are the same?

The semantics are generally consistent, but there are inconsistencies between Presto and Spark in the handling of null values. Spark always ignores null values in the input, whereas Presto preserves them. The parameter `QueryConfig::kPrestoArrayAggIgnoreNulls` in array_agg can control whether to ignore nulls, but currently, `set_agg` does not support this. Moreover, Presto returns null when all inputs are null, while Spark returns an empty list or set. For the inconsistencies regarding nulls, we hope to adapt in other PRs. 
I think a better approach is to rewrite both `array_agg` and `set_agg` based on the simple aggregate function interface, placing them in `velox/function/lib/aggregate`. Spark can inherit from the simple aggregate function's struct and override methods like `addInput` and `writeFinalResult`. 
Alternatively, we could add the `QueryConfig::kPrestoArrayAggIgnoreNulls` parameter to `set_agg` as well, and then add a `returnEmptyForAllNullInputs` parameter to both `set/array_agg`. Do you have any suggestions?

**Comment by mbasmanova** [comment]
> Yes. Gluten needs to use companion functions of all aggregate functions. Would you recommend that I add all of them in this PR?

Yes. It would be nice to add this flag to all functions. Thanks. CC: @rui-mo

**Comment by mbasmanova** [comment]
> I think a better approach is to rewrite both array_agg and set_agg based on the simple aggregate function interface, placing them in velox/function/lib/aggregate. Spark can inherit from the simple aggregate function's struct and override methods like addInput and writeFinalResult.

I suggest to implement Spark version using simple API while maybe reusing the accumulators. It could be that most of the code is in the accumulators anyway and the amount of code in the function itself is rather small and therefore not worth the trouble of sharing.

**Comment by liujiayi771** [comment]
@mbasmanova @rui-mo Add `withCompanionFunctions` to all aggregate functions.

**Review by rui-mo — COMMENTED** [review]
Thanks. Could you update the PR description at the same time?

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Pull request closed without merging**
