### PR TITLE
Disable arrow support for nightly fuzzer tests.

### PR DESCRIPTION
**Pull request by kgpai**
At the moment enabling arrow doesnt seem to play well with cmake folly leading to recompilation. Disabling while we try and find a fix. cc #2758

### CODE REVIEW

**Review by raulcd — COMMENTED** [review]
The change LGTM, I am curious on why the `linux-build` which is running with `-DVELOX_ENABLE_ARROW=ON` and is running fuzzer tests https://github.com/facebookincubator/velox/blob/main/.circleci/config.yml#L177-L197  is now not re-building: https://app.circleci.com/pipelines/github/facebookincubator/velox/14525/workflows/832c57b8-4b04-4b47-9301-c944ee484d62/jobs/88160 when the change is done to the other job but it seems it was re-building on a previous job: https://app.circleci.com/pipelines/github/facebookincubator/velox/14451/workflows/8ed33839-a0ee-4f69-8a49-c1c202b5b1c9/jobs/87661

**Comment by majetideepak** [comment]
@kgpai can you please update the description before merging? Looks like we are only removing the unnecessary Arrow dependency.

**Comment by kgpai** [comment]
@majetideepak  Will do, but my understanding is that its basically used for thrift /arrow / parquet support. Updated the description though.

**Comment by majetideepak** [comment]
@kgpai Enabling Arrow will not enable Parquet. Parquet has its own cmake flag `VLEOX_ENABLE_PARQUET`. So enabling only Arrow is redundant afaik.

**Pull request closed without merging**
