### PR TITLE
fix TimeStamp toString precision

### PR DESCRIPTION
**Pull request by duanmeng**
Details in https://github.com/facebookincubator/velox/issues/5595

### CODE REVIEW

**Comment by zacw7** [comment]
Hi @duanmeng , thanks for looking into https://github.com/facebookincubator/velox/issues/5595 and drafting this fix. Just want to quickly check what's the current status of this PR? Do you still plan to have the fix merged?

**Comment by duanmeng** [comment]
> Hi @duanmeng , thanks for looking into #5595 and drafting this fix. Just want to quickly check what's the current status of this PR? Do you still plan to have the fix merged?

@zacw7 Hi Zac, The solution in this PR should be not appropriate, and I may have no bandwidth to continue to work on it for now. Should I close it?

**Comment by zacw7** [comment]
> > Hi @duanmeng , thanks for looking into #5595 and drafting this fix. Just want to quickly check what's the current status of this PR? Do you still plan to have the fix merged?
> 
> @zacw7 Hi Zac, The solution in this PR should be not appropriate, and I may have no bandwidth to continue to work on it for now. Should I close it?

Reading the discussion under https://github.com/facebookincubator/velox/issues/5595, it seems we already have a viable solution to fix the issue right? If you don't have the bandwidth I can take it from here. Thanks!

**Comment by duanmeng** [comment]
@zacw7 Zac kindly help to take this one.

**Pull request closed without merging**
