### PR TITLE
Add ReadFileInputStreamTests.cpp to CMakeLists.txt

### PR DESCRIPTION
**Pull request by isadikov**
This test was not included in any CMakeLists file.

### CODE REVIEW

**Comment by isadikov** [comment]
Interestingly, the linux-build failed with the fuzzer error on the initial commit (unrelated to this PR): https://app.circleci.com/pipelines/github/facebookincubator/velox/19391/workflows/a3e63749-9096-4a2f-87e7-fc8173589e29/jobs/122307:
```
I0129 19:59:25.404004 153233 ExpressionVerifier.cpp:80] Executing expression: plus(4466318525357736456,"c0")
I0129 19:59:25.404017 153233 ExpressionVerifier.cpp:32] 1 vectors as input:
I0129 19:59:25.404021 153233 ExpressionVerifier.cpp:34] 	[DICTIONARY BIGINT: 100 elements, 9 nulls], [FLAT BIGINT: 100 elements, 11 nulls]
E0129 19:59:25.404275 153233 Exceptions.h:68] Line: ../.././velox/common/base/CheckedArithmetic.h:31, Function:checkedPlus, Expression:  integer overflow: 4466318525357736456 + 4774894575385321841, Source: USER, ErrorCode: ARITHMETIC_ERROR
E0129 19:59:25.404511 153233 Exceptions.h:68] Line: ../.././velox/common/base/CheckedArithmetic.h:31, Function:checkedPlus, Expression:  integer overflow: 4466318525357736456 + 4960539897478018639, Source: USER, ErrorCode: ARITHMETIC_ERROR
W0129 19:59:25.404592 153233 FuzzerToolkit.cpp:112] Two different VeloxExceptions were thrown:
	integer overflow: 4466318525357736456 + 4774894575385321841
and
	integer overflow: 4466318525357736456 + 4960539897478018639
```

I have re-triggered the tests and will investigate it separately, it should not block this PR.

**Comment by isadikov** [comment]
@aditi-pandit Could you review this small PR when you have time? Thank you.

**Comment by Yuhta** [comment]
@isadikov You can change the status of the PR when you think it's ready

**Comment by isadikov** [comment]
@Yuhta This PR is ready now. Could you take another look? Thank you.

**Pull request closed without merging**
