### PR TITLE
Add weibull_cdf Presto function

### PR DESCRIPTION
**Pull request by Krishna-Prasad-P-V**
Resolves https://github.com/facebookincubator/velox/issues/4760

### CODE REVIEW

**Comment by Krishna-Prasad-P-V** [comment]
This is a new PR as the old PR https://github.com/facebookincubator/velox/pull/5759 had pipeline issues.

**Comment by Krishna-Prasad-P-V** [comment]
Fuzzer test output for weibull_cdf:

I20230628 09:47:29.582652 1731535 ExpressionVerifier.cpp:56] ===================
I20230628 09:47:29.582690 1731535 ExpressionVerifier.cpp:67] All results match.
I20230628 09:47:29.582752 1731535 ExpressionFuzzer.cpp:1357] ==============================> Done with iteration 850
I20230628 09:47:29.583197 1731535 ExpressionFuzzer.cpp:1092] ==============================> Top 1 by number of rows processed
I20230628 09:47:29.583209 1731535 ExpressionFuzzer.cpp:1094] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230628 09:47:29.583216 1731535 ExpressionFuzzer.cpp:1098] weibull_cdf 96259 100.00% 10164
I20230628 09:47:29.583249 1731535 ExpressionFuzzer.cpp:1104] ==============================> Bottom 1 by number of rows processed
I20230628 09:47:29.583256 1731535 ExpressionFuzzer.cpp:1106] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230628 09:47:29.583261 1731535 ExpressionFuzzer.cpp:1111] weibull_cdf 96259 100.00% 10164
I20230628 09:47:29.583276 1731535 ExpressionFuzzer.cpp:1124] ==============================> All stats sorted by number of times the function was chosen
I20230628 09:47:29.583282 1731535 ExpressionFuzzer.cpp:1126] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230628 09:47:29.583292 1731535 ExpressionFuzzer.cpp:1130] weibull_cdf 96259 100.00% 10164

**Comment by Krishna-Prasad-P-V** [comment]
@aditi-pandit - Kindly review and approve this PR. Thanks.
Already, the old PR with the same changes was approved - https://github.com/facebookincubator/velox/pull/5759. Now since the old fork was deleted and created, this becomes a new PR.

**Comment by aditi-pandit** [comment]
@Krishna-Prasad-P-V : Please can you rebase your code. Will do a round of review after that.

**Comment by Krishna-Prasad-P-V** [comment]
Completed code rebase. Attaching fuzzer run output.
```
I1115 20:21:28.405441 370061 ExpressionVerifier.cpp:63] ===================
I1115 20:21:28.405464 370061 ExpressionVerifier.cpp:74] All results match.
I1115 20:21:28.405553 370061 ExpressionFuzzer.cpp:1358] ==============================> Done with iteration 143
I1115 20:21:28.405851 370061 ExpressionFuzzer.cpp:1093] ==============================> Top 1 by number of rows processed
I1115 20:21:28.405869 370061 ExpressionFuzzer.cpp:1095] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I1115 20:21:28.405874 370061 ExpressionFuzzer.cpp:1099] weibull_cdf 16042 100.00% 1429
I1115 20:21:28.406105 370061 ExpressionFuzzer.cpp:1105] ==============================> Bottom 1 by number of rows processed
I1115 20:21:28.406116 370061 ExpressionFuzzer.cpp:1107] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I1115 20:21:28.406121 370061 ExpressionFuzzer.cpp:1112] weibull_cdf 16042 100.00% 1429
I1115 20:21:28.406132 370061 ExpressionFuzzer.cpp:1125] ==============================> All stats sorted by number of times the function was chosen
I1115 20:21:28.406136 370061 ExpressionFuzzer.cpp:1127] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I1115 20:21:28.406140 370061 ExpressionFuzzer.cpp:1131] weibull_cdf 16042 100.00% 1429
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

**Comment by Krishna-Prasad-P-V** [comment]
> @Krishna-Prasad-P-V : Please can you rebase your code. Will do a round of review after that.
> 
> Please also re-run the fuzzer and paste the new results in this PR.

@aditi-pandit - Could you please re-review now? Thanks.

**Review by aditi-pandit — APPROVED** [review]

**Comment by aditi-pandit** [comment]
@Yuhta : PTAL.

**Pull request closed without merging**
