### PR TITLE
Remove global -Wno-type-limits compiler option 

### PR DESCRIPTION
**Pull request by acvictor**
This PR removes -Wno-type-limits compiler option which disables warnings about comparisons that will always be true or false due to the limited range of data types, and removes some checks that always evaluate to true like `unsigned int >= 0` which is always true.

Meant to address https://github.com/facebookincubator/velox/discussions/9469

### CODE REVIEW

**Comment by acvictor** [comment]
@mbasmanova can you please review? Thank you!

**Review by pedroerp — APPROVED** [review]
Thank you!

**Comment by pedroerp** [comment]
@acvictor looks like there is a conflict with another change; could you rebase it first?

**Comment by acvictor** [comment]
> @acvictor looks like there is a conflict with another change; could you rebase it first?

Thank you @pedroerp! I have rebased with main.

**Comment by kgpai** [comment]
Something to note is that presto native also inherits some of the flags we use in building Velox and thus this change would also require changes there - One complication is that lot of the mechanisms where we have per dependency based flags arent present there and its still all or nothing.

**Comment by acvictor** [comment]
> Something to note is that presto native also inherits some of the flags we use in building Velox and thus this change would also require changes there - One complication is that lot of the mechanisms where we have per dependency based flags arent present there and its still all or nothing.

Oh I see! In that case shall I add the flag back while retaining other updates made to resolve the warnings and revisit removing it?

**Comment by kgpai** [comment]
> Oh I see! In that case shall I add the flag back while retaining other updates made to resolve the warnings and revisit removing it? 

I am not suggesting that - as removing the flag means people might inadvertently add these checks again . If you can try building presto-native with your changes that would be great to give the presto folks a heads up ; but again sometimes presto-native requires changes to move forward to latest version of Velox irrespective of your changes.

(In the worst case we might discover that presto-native's dependencies cant be built without this flag and might need to revert removal of the flag)

**Comment by acvictor** [comment]
> > Oh I see! In that case shall I add the flag back while retaining other updates made to resolve the warnings and revisit removing it?
> 
> I am not suggesting that - as removing the flag means people might inadvertently add these checks again . If you can try building presto-native with your changes that would be great to give the presto folks a heads up ; but again sometimes presto-native requires changes to move forward to latest version of Velox irrespective of your changes.
> 
> (In the worst case we might discover that presto-native's dependencies cant be built without this flag and might need to revert removal of the flag)

And that would be https://github.com/prestodb/presto?

**Comment by kgpai** [comment]
> And that would be https://github.com/prestodb/presto/

Yes here : https://github.com/prestodb/presto/tree/master/presto-native-execution . 
Velox is a subproject so you need to check out your pr and then try build presto-native-execution.

**Comment by assignUser** [comment]
> Something to note is that presto native also inherits some of the flags we use in building Velox

tbf that's something presto should decouple and if they want to add the flag back they can do that in their CMakeLists.txt after `add_subdirectory(velox)`

**Comment by assignUser** [comment]
Yeah CMAKE_CXX_FLAGS has project scope and so it shouldn't affect what presto uses when velox is added as a subdir. In this example a subproject adds -Werror to the var but the parent projects flags are unaffected:
```
-- Flags Sub-project: -Wall;-Werror
-- Final Flags: -Wall
```

**Review by assignUser — APPROVED** [review]
Thanks!

**Review by xiaoxmeng — APPROVED** [review]

**Comment by kgpai** [comment]
@assignUser CXX_FLAGS might have dir scope but Presto explicitly gets it from a velox script here : https://github.com/prestodb/presto/blob/master/presto-native-execution/CMakeLists.txt#L24

**Pull request closed without merging**
