### PR TITLE
docs: Add query tracing blog

### PR DESCRIPTION
**Pull request by duanmeng**
Add a query tracing blog to the Velox website.

Original design doc, https://docs.google.com/document/d/1crIIeVz4tWKYQnBoHoxrv2i-4zAML9HSYLps8h5SDrc/edit?tab=t.0#heading=h.y6j2ojtr7hm9

### CODE REVIEW

**Comment by mbasmanova** [comment]
@duanmeng Is this a copy of https://facebookincubator.github.io/velox/develop/debugging/tracing.html ?

**Comment by xiaoxmeng** [comment]
> @duanmeng the blog post reads pretty well, thanks for putting it together. As a thought: are we also adding it to the Velox docs? It would be nice to add the full version there so that people find it more easily in the future.
> 
> One way we could organize this to prevent the blog post from being too dense, would be to move all the detailed information to a doc page (maybe this version could be the doc), and having a more condensed version as the blog post? This reads great, but it feels a bit long for a blog post - which is not necessarily bad.
> 
> Wondering what other think - @mbasmanova @xiaoxmeng @Yuhta @majetideepak

@pedroerp sounds good. @duanmeng could you make a short one and have reference to the detailed design doc? Thanks!

**Comment by duanmeng** [comment]
I've moved all the detailed information to a tracing doc page and condensed the blog post. Could you please help take another look? Thanks. @xiaoxmeng @pedroerp @mbasmanova

**Review by xiaoxmeng — APPROVED** [review]
@duanmeng thanks for putting all the things together!

**Pull request closed without merging**
