### PR TITLE
Refactor Benchmarks

### PR DESCRIPTION
**Pull request by majetideepak**
We expect to have two categories of benchmarks: "basic", which runs on every
commit, and another one that runs less frequently.

This change moves `benchmarks/SimpleArithmetic.cpp` into `benchmarks/basic`
folder.

### CODE REVIEW

**Comment by majetideepak** [comment]
linux-benchmarks-basic is failing since the main branch does not have the renamed `benchmarks-basic-build` target

**Comment by aditi-pandit** [comment]
Nit : Maybe use naming "core" or "base" to be consistent with other directory naming in Velox.

**Comment by majetideepak** [comment]
@aditi-pandit The benchmarks in `basic` need be limited to "core" or "base". The current benchmark is `SimpleArithmetic.cpp` and tests the basic multiply operation. `simple`, `small` could be other terms.

**Review by mbasmanova — APPROVED** [review]
@majetideepak Looks good to me. I edited PR description for brevity and clarity and formatted it to limit lines to 80 characters.

**Pull request closed without merging**
