### PR TITLE
Covar agg dist

### PR DESCRIPTION
**Pull request by timber-lin**

### CODE REVIEW

**Review by mbasmanova — COMMENTED** [review]
@timber-lin I'm seeing multiple draft PRs from you and wondering what are you up to. These PRs do not have any description and are not tied to any GitHub issue and appear to have very rough code changes. It almost looks like you might be using GitHub to test your changes. Any chance you could clarify what you are doing and what are you plans going forward?

**Comment by shiyu-bytedance** [comment]
> @timber-lin I'm seeing multiple draft PRs from you and wondering what are you up to. These PRs do not have any description and are not tied to any GitHub issue and appear to have very rough code changes. It almost looks like you might be using GitHub to test your changes. Any chance you could clarify what you are doing and what are you plans going forward?

@mbasmanova Thank you for the comment and apologies about the confusion. 
@timber-lin is our summer intern year, who has worked on implementing the distinct keyword support for aggregation.

We created these pull requests following the Github instruction for "draft" pull request and had thought these would be considered "not ready for review" until we "mark them as ready for review". 
image
image

We'd planned to create these draft requests, polish them up and then mark them as ready for review. The reason we created these PR as draft is so that velox Github CI can be run against the changes.

Overall, what we are trying to do is to incorporate your feedback in https://github.com/facebookincubator/velox/pull/5888#issuecomment-1658935292 by submitting a PR for a unit test that crashes when covar_pop(distinct) is in the query plan (left as DISABLED test), create an issue tracking this disabled test and the code change needed to make this test pass.

We apologize if this is inconsistent with Facebook's expectation and will withdraw these requests.

**Comment by timber-lin** [comment]
withdrawing this PR now by closing

**Comment by mbasmanova** [comment]
@shiyu-bytedance Thank you for sharing this context. 

> Overall, what we are trying to do is to incorporate your feedback in https://github.com/facebookincubator/velox/pull/5888#issuecomment-1658935292 by submitting a PR for a unit test that crashes when covar_pop(distinct) is in the query plan (left as DISABLED test), create an issue tracking this disabled test and the code change needed to make this test pass.

Can you run this test locally and then create a GitHub issue explaining what you found? You can include the test code as well as test results in the issue.

It would also be helpful to discuss the problem you are trying to solve and the approach you'd like to use for the solution in the same GitHub issue.

Thanks.

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance Thank you for sharing this context.
> 
> > Overall, what we are trying to do is to incorporate your feedback in [#5888 (comment)](https://github.com/facebookincubator/velox/pull/5888#issuecomment-1658935292) by submitting a PR for a unit test that crashes when covar_pop(distinct) is in the query plan (left as DISABLED test), create an issue tracking this disabled test and the code change needed to make this test pass.
> 
> Can you run this test locally and then create a GitHub issue explaining what you found? You can include the test code as well as test results in the issue.
> 
> It would also be helpful to discuss the problem you are trying to solve and the approach you'd like to use for the solution in the same GitHub issue.
> 
> Thanks.

Sure, done. https://github.com/facebookincubator/velox/issues/5972

**Pull request closed without merging**
