### PR TITLE
Change the arrow dependency from private to public in velox_external_hdfs

### PR DESCRIPTION
**Pull request by JkSelf**
Fix https://github.com/facebookincubator/velox/pull/9835#discussion_r1820046134

### CODE REVIEW

**Comment by JkSelf** [comment]
@majetideepak @Yohahaha @PHILO-HE Can you help to review? Thanks.

**Review by PHILO-HE — COMMENTED** [review]
Looks good! Thanks!

**Review by Yohahaha — APPROVED** [review]
👍

**Review by majetideepak — APPROVED** [review]

**Review by assignUser — APPROVED** [review]

**Comment by mbasmanova** [comment]
@JkSelf Would you rebase to allow merging?

**Comment by JkSelf** [comment]
> @JkSelf Would you rebase to allow merging?

@mbasmanova Yes. Rebased.

**Pull request closed without merging**
