### PR TITLE
Migrate circleci worklfows to github actions

### PR DESCRIPTION
**Pull request by robandpdx**
This pull request converts the CircleCI workflows to GitHub actions workflows.

The GitHub actions workflows need runner groups with [larger runners configured for the organization](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/managing-larger-runners).

The following runner group is needed:
- 32-core

For my testing, I have these runner groups populated with the following runners:
| Group       | Runner size                         | OS            |
|-------------|-------------------------------------|---------------|
| 32-core     | 32-cores · 128 GB RAM · 1200 GB SSD | Ubuntu Latest |

**Issues**  
There are issue with some of the workflow that someone smarter than me needs to address.  
1. linux-pr-fuzzer-run  
This appears to fail getting the merge base. I'm not sure why this is happening.  

2. linux-adapters  
The error is...  
```
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:98: build] Error 1
make[1]: Leaving directory '/__w/velox/velox'
make: *** [Makefile:105: release] Error 2
Error: Process completed with exit code 2.
```

https://fburl.com/workplace/f6mz6tmw

### CODE REVIEW

**Comment by kgpai** [comment]
Thanks @robandpdx for this work. Please give us a day or so to verify that this works.

**Comment by assignUser** [comment]
This is great thanks, I'll have a look soon, we can probably unify the fuzzer stuff with the existing `scheduled.yml` etc.. Any objections to me pushing to this PR directly?

 @robandpdx I see we have access to the new m1 runners, very nice! I think the fuzzer job is the only one using the 32core runner and we can probably downgrade that (we have done that with the scheduled runs already see #7842 ).

**Comment by robandpdx** [comment]
> I think the fuzzer job is the only one using the 32core runner and we can probably downgrade that (we have done that with the scheduled runs already see #7842 ).

@assignUser No objections to pushing to this PR or my branch. My fork is public and I've added you as a collaborator there. It makes sense to downgrade jobs to a smaller runners if possible, for cost control. I'm happy to help reorganize stuff if needed with some direction from folks in the know here. Just let me know how I can help.

**Comment by assignUser** [comment]
@robandpdx  Thanks for your work. We have discussed offline and will consolidate and rework the jobs to remove redundancies and make better use of gha capabilities. Therefor we are going to split this into multiple PRs (as well as for reviewability :) ).

You have some cool ideas here that I am going to reuse in the reworked builds, would you like to be pinged on those? I would appreciate your experience but I understand if you don't have the bw.

**Comment by robandpdx** [comment]
> You have some cool ideas here that I am going to reuse in the reworked builds, would you like to be pinged on those?

@assignUser Sure! I'm happy to help.

**Comment by bigfootjon** [comment]
@assignUser: AFAICT all CircleCI workflows have been migrated to GitHub and all that remains is a "noop" workflow. Can we delete that workflow and disable CircleCI? (and close this PR?)

**Comment by kgpai** [comment]
@bigfootjon I plan to do disable CCI by Friday, we just migrated all this and wanted to be sure there are no regressions before turning off CCI.

**Comment by assignUser** [comment]
But we can close this PR immediately :)

**Pull request closed without merging**
