### PR TITLE
Enable decimal fuzzer test in experimental workflow

### PR DESCRIPTION
**Pull request by rui-mo**
Enables experimental fuzzer test with decimal type enabled. We can turn it on 
for the nightly and CI jobs once we get a few green runs.

### CODE REVIEW

**Comment by rui-mo** [comment]
@kgpai @assignUser This PR enables a decimal fuzzer test experimentally. Would you like to take a review? Thanks.

**Review by assignUser — APPROVED** [review]
looks like it already found some issues ^^

**Comment by rui-mo** [comment]
@assignUser Thanks for your review. Just want to clarify that the two failures are related to https://github.com/facebookincubator/velox/issues/10871 and https://github.com/facebookincubator/velox/issues/10989, after the change from user error to runtime error, but they are not related to the decimal type.

**Comment by rui-mo** [comment]
@kgpai @majetideepak Would you like to take a review? Thanks.

**Comment by rui-mo** [comment]
@assignUser @kgpai @majetideepak Could we merge this PR if no further comment? Thanks for your help.

**Review by majetideepak — APPROVED** [review]
Looks good to me. @assignUser can you make a final pass? Thanks.

**Pull request closed without merging**
