### PR TITLE
Relink new targets in velox/common

### PR DESCRIPTION
**Pull request by assignUser**
There were some changes merged to velox/common during review of #6237 that need to be updated.

### CODE REVIEW

**Comment by kgpai** [comment]
Looks good, Can you rebase against main and rebuild so I can start the merge process ?

**Comment by kgpai** [comment]
cc: @assignUser

**Comment by kgpai** [comment]
@assignUser should we close this ?

**Comment by assignUser** [comment]
Let's close it for now, I will re-open when relevant.

**Pull request closed without merging**
