### PR TITLE
Update Presto functions coverage map

### PR DESCRIPTION
**Pull request by pramodsatya**
Updated the complete list of Presto scalar functions using output from `SHOW FUNCTIONS` command.

Re-generated coverage maps using instructions from
`velox/functions/prestosql/coverage/README.md`.

### CODE REVIEW

**Review by aditi-pandit — APPROVED** [review]
Thanks @pramodsatya

**Review by mbasmanova — COMMENTED** [review]
@pramodsatya Thank you for the update. It looks like you have updated the list of Presto functions to add functions added recently. Is this the case? If so, would you update PR description to state that clearly and explain how did you generate the updated list.

**Comment by pramodsatya** [comment]
> @pramodsatya Thank you for the update. It looks like you have updated the list of Presto functions to add functions added recently. Is this the case? If so, would you update PR description to state that clearly and explain how did you generate the updated list.

Thanks for the feedback @mbasmanova, yes that is what I did and the PR description is updated to reflect this. Could you please take another look at the changes? Thanks

**Review by mbasmanova — APPROVED** [review]
@pramodsatya Thanks.

**Pull request closed without merging**
