### PR TITLE
Use envvar for DuckDB version in setup script

### PR DESCRIPTION
**Pull request by JackyWoo**
### Changelog

Make duckdb version an versiable

### CODE REVIEW

**Review by assignUser — CHANGES_REQUESTED** [review]
Sensible change but please also add the change to the other setup scripts aswell.

**Review by assignUser — APPROVED** [review]
Thanks!

**Comment by JackyWoo** [comment]
@assignUser this is my first PR in velox, may I ask how a PR is merged?  For I foud all PR is closed but not merged in github, thanks.

**Comment by assignUser** [comment]
@JackyWoo as this is a Meta project the code actually lives in the Meta monorepo. So PRs from github get reviewed and tested here but a meta employee has to import them into the internal monorepo. Once that is done and has passes checks it gets exported into the facebookincubator/velox repo by facebookbot and the PR is closed. It looks weird in your gh activity but the code does get merged properly ^^

It's a bit of a process and we are working towards are more streamlined  open-source first approach but that's stll a while of.

**Comment by JackyWoo** [comment]
@assignUser really thanks.

**Pull request closed without merging**
