### PR TITLE
Fix fmt error in RuntimeMetrics

### PR DESCRIPTION
**Pull request by yingsu00**
After fmt package was updated, some of the VELOX_CHECK_XXX fails. An example error message:
    "error: 'fmt::v10::detail::type_is_unformattable_for<const facebook::velox::RuntimeCounter::Unit, char> _' has incomplete type". This commit fixes this error in RuntimeMetrics.cpp.

The full error log can be found https://app.circleci.com/pipelines/github/facebookincubator/velox/44177/workflows/079e5931-917d-410a-85a5-c62201dae588/jobs/308209
```
/root/project/./velox/common/base/Exceptions.h:153:49:   required from 'std::string facebook::velox::detail::errorMessage(fmt::v10::string_view, const Args& ...) [with Args = {facebook::velox::RuntimeCounter::Unit, facebook::velox::RuntimeCounter::Unit}; std::string = std::__cxx11::basic_string<char>; fmt::v10::string_view = fmt::v10::basic_string_view<char>]'
/root/project/velox/common/base/RuntimeMetrics.cpp:38:3:   required from here
/usr/local/include/fmt/core.h:1576:63: error: 'fmt::v10::detail::type_is_unformattable_for<const facebook::velox::RuntimeCounter::Unit, char> _' has incomplete type
 1576 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
/usr/local/include/fmt/core.h:1580:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1580 |       formattable,
      |       ^~~~~~~~~~~
cc1plus: error: unrecognized command line option '-Wno-stringop-overread' [-Werror]
```

### CODE REVIEW

**Comment by Yuhta** [comment]
@kgpai Anything we need to add to make it work with the new fmt?

**Review by pedroerp — CHANGES_REQUESTED** [review]
@assignUser I remember seeing a codemod changing some of the fmt printer interface. We are probably missing one for this object? 

Let's fix the fmt printers as moving to a boolean check loses the additional context print when the check fails.

**Comment by assignUser** [comment]
I don't see this issue on main so this must be caused by your changes in #8728 as there already is a [specialization](https://github.com/facebookincubator/velox/blob/main/velox/common/base/RuntimeMetrics.h#L114-L119) for `facebook::velox::RuntimeCounter::Unit` which is an enum, so I don't quite undestand why fmt is complaining about char?  But I might be misinterpreting the error message?

**Comment by yingsu00** [comment]
Thanks every one for looking at this! I didn't see @assignUser 's fix when I submitted this PR, as my branch was old. The problem went away after I synced my branch. Sorry for the confusions, and I'll close it now.

**Pull request closed without merging**
