### PR TITLE
Revert "Buckify simdjson and use it everywhere (#5405)"

### LINKED ISSUE #5666: Can not find simdjson.h when use system simdjson
### Problem description

Since PR #5405 force use simdjson.h under ${CMAKE_BINARY_DIR}/_deps/simdjson-src/simdjson, it breaks build when simdjson was already installed.

simdjson in my build machine:
```
# find /usr simdjson | grep simdjson
/usr/local/lib64/libsimdjson.a
/usr/local/lib64/cmake/simdjson
/usr/local/lib64/cmake/simdjson/simdjsonTargets.cmake
/usr/local/lib64/cmake/simdjson/simdjson-config-version.cmake
/usr/local/lib64/cmake/simdjson/simdjson-config.cmake
/usr/local/lib64/cmake/simdjson/simdjsonTargets-release.cmake
/usr/local/lib64/pkgconfig/simdjson.pc
/usr/local/include/simdjson.h
```

Could we use more general way to find simdjson?

CC @assignUser @kgpai 

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-14.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### CMake log

_No response_

### PR DESCRIPTION
**Pull request by assignUser**
This reverts commit 1b8a802f179ec8f8cf0ffa08327b98ac8ed65cfa.

Closes #5666

### CODE REVIEW

**Comment by pedroerp** [comment]
@assignUser seems like all jobs are failing

**Comment by assignUser** [comment]
Ah it looks like the include path was changes in additional PRs.

**Comment by assignUser** [comment]
@pedroerp pretty sure the linux build test failure is unrelated

**Comment by mbasmanova** [comment]
I'm seeing build errors now:

```
In file included from /Users/mbasmanova/cpp/velox-1/velox/functions/prestosql/json/SIMDJsonExtractor.cpp:17:
In file included from /Users/mbasmanova/cpp/velox-1/./velox/functions/prestosql/json/SIMDJsonExtractor.h:25:
/Users/mbasmanova/cpp/velox-1/./velox/functions/prestosql/json/SIMDJson.h:22:10: error: non-portable path to file '"SIMDJson.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
#include "simdjson.h"
         ^~~~~~~~~~~~
         "SIMDJson.h"
In file included from /Users/mbasmanova/cpp/velox-1/velox/functions/prestosql/json/SIMDJsonExtractor.cpp:17:
/Users/mbasmanova/cpp/velox-1/./velox/functions/prestosql/json/SIMDJsonExtractor.h:38:32: error: use of undeclared identifier 'simdjson'
using JsonVector = std::vector<simdjson::ondemand::value>;
```

**Comment by pedroerp** [comment]
Fixed in https://github.com/facebookincubator/velox/pull/6203

**Pull request closed without merging**
