### PR TITLE
Throw USER error when exceeding max number of regex

### PR DESCRIPTION
**Pull request by mbasmanova**
Categorize 'Max number of regex reached' failure as USER error.

### CODE REVIEW

**Comment by laithsakka** [comment]
does it make sense to throw this from out side applyToSelectedNoThrow, so that try wont suppress this error. until i get to add a different type of error.
maybe set a flag and then if that flag is true throw outside after applyToSelectedNoThrow.

**Comment by spershin** [comment]
Folks, I'm a bit concerned that Presto Java can run such queries and Presto Native fails.
Should we fallback to a slow execution?

cc @mbasmanova @laithsakka

**Comment by mbasmanova** [comment]
> Should we fallback to a slow execution?

It is not safe to compile unlimited number of regex per query. This can bring down a cluster cause a SEV. 

We can enable all reasonable queries though. See https://github.com/facebookincubator/velox/pull/7158

**Review by xiaoxmeng — APPROVED** [review]
@mbasmanova LGTM. Thanks!

**Pull request closed without merging**
