### PR TITLE
Fix order of functions in .rst files

### PR DESCRIPTION
**Pull request by isadikov**
Make sure functions appear in alphabetical order in the docs. Update function coverage map.

### CODE REVIEW

**Review by aditi-pandit — APPROVED** [review]
Thanks Ivan !

**Comment by isadikov** [comment]
Thanks for the review, @aditi-pandit. Do you know how I can regenerate `functions.rst` and `coverage.rst` files? I can include them in my PR. 

It looks like those files are generated based on commits like this one: https://github.com/facebookincubator/velox/commit/5d4a550713a98f0a0cacaef7ca551025f2bbd965 but I cannot figure out how to do that.

**Comment by aditi-pandit** [comment]
> Thanks for the review, @aditi-pandit. Do you know how I can regenerate `functions.rst` and `coverage.rst` files? I can include them in my PR.
> 
> It looks like those files are generated based on commits like this one: [5d4a550](https://github.com/facebookincubator/velox/commit/5d4a550713a98f0a0cacaef7ca551025f2bbd965) but I cannot figure out how to do that.
There are some instructions at https://github.com/facebookincubator/velox/tree/main/velox/functions/prestosql/coverage. Check if they work for you.

**Comment by isadikov** [comment]
I have also updated functions.rst and coverage.rst based on the docs https://github.com/facebookincubator/velox/tree/main/velox/functions/prestosql/coverage. Please take a look, thanks!

**Review by mbasmanova — APPROVED** [review]
@isadikov Thank you for cleaning the docs and re-generating coverage map. Next time, create separate PRs for different changes to help keep each PR small and easy to review.

**Comment by isadikov** [comment]
Thanks for merging!

**Comment by mbasmanova** [comment]
@isadikov Thank you for the contribution.

**Pull request closed without merging**
