### PR TITLE
Set required simdjson version to be 3.2.0

### LINKED ISSUE #8836: Building velox can fail if system installed simdjson is not right
### Problem description

Building latest velox master fails with following error because it uses system provided simdjson by default. 
```
FAILED: velox/functions/prestosql/CMakeFiles/velox_functions_prestosql_impl.dir/JsonFunctions.cpp.o
/usr/bin/ccache /usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFOLLY_HAVE_INT128_T=1 -DGFLAGS_IS_A_DLL=0 -DSIMDJSON_THREADS_ENABLED=1 -I../../. -I../../velox/external/xxhash -isystem ../../velox -isystem ../../velox/external -isystem /usr/include/libdwarf -isystem /usr/include/libiberty -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits          -Wno-stringop-overflow          -Wno-stringop-overread          -Wno-return-type -Werror -g -fPIC   -fdiagnostics-color=always -std=gnu++17 -MD -MT velox/functions/prestosql/CMakeFiles/velox_functions_prestosql_impl.dir/JsonFunctions.cpp.o -MF velox/functions/prestosql/CMakeFiles/velox_functions_prestosql_impl.dir/JsonFunctions.cpp.o.d -o velox/functions/prestosql/CMakeFiles/velox_functions_prestosql_impl.dir/JsonFunctions.cpp.o -c ../../velox/functions/prestosql/JsonFunctions.cpp
../../velox/functions/prestosql/JsonFunctions.cpp: In member function 'simdjson::error_code facebook::velox::functions::{anonymous}::JsonParseFunction::parse(size_t) const':
../../velox/functions/prestosql/JsonFunctions.cpp:138:14: error: 'class simdjson::fallback::ondemand::document' has no member named 'at_end'
  138 |     if (!doc.at_end()) {
      |              ^~~~~~
At global scope:
cc1plus: error: unrecognized command line option '-Wno-stringop-overread' [-Werror]
cc1plus: all warnings being treated as errors
```

### System information

Velox System Info v0.0.2
Commit: 7945122036f102c9f51bd54a419c523e9d34c70b
CMake Version: 3.16.3
System: Linux-5.4.0-1063-aws
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### CMake log

```bash
simdjson related:

-- Setting simdjson source to AUTO
-- Using SYSTEM simdjson

grep '#define SIMDJSON_VERSION' /usr/local/include/simdjson.h
#define SIMDJSON_VERSION "3.1.5"
```

### PR DESCRIPTION
**Pull request by qqibrow**
Fixes #8836

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]
Thanks, @qqibrow

**Comment by majetideepak** [comment]
@qqibrow simdjson is also missing from the table here in the README.mc https://github.com/facebookincubator/velox/tree/main/CMake/resolve_dependency_modules
Can you please add it along with this version? Thanks.

**Review by assignUser — APPROVED** [review]
Thanks

**Comment by pedroerp** [comment]
Thanks @qqibrow. Let's update the mardown file @majetideepak suggested then I can get it merged.

**Comment by qqibrow** [comment]
Thanks! all done.

**Review by kgpai — APPROVED** [review]

**Pull request closed without merging**
