### PR TITLE
Create folder if not exits on HDFS write

### PR DESCRIPTION
**Pull request by xieqi**
currently there is no check whether the parent folder exist, we should create it if the directory does not exist.
I add a test case writeWithParentDirNotExist in HdfsFileSystemTest, without this patch, the test can't pass due to parent directory does not exist.

### CODE REVIEW

**Comment by xieqi** [comment]
@rui-mo plz review, thanks.

**Comment by Yohahaha** [comment]
As I know, when Spark execute a write task, it will check whether dir exists and mkdir if not exist.
I mean this check and mkdir operation should be done in application which integrate Velox, would you add more background information about this issue?

**Comment by FelixYBW** [comment]
@xieqi can you check if Spark can create the folder before we execute the query plan? if folder is created in executor, then let's continue the proposal.

**Comment by JkSelf** [comment]
@Yohahaha @FelixYBW @xieqi 
When writing Parquet data in Spark, the data is first written to a temporary directory. After the write operation is completed, the entire directory is atomically moved to the final destination. This ensures that only complete and consistent data is exposed to other reading tasks.

For example `df.write.foramt("parquet").path("/user/sparkuser/write")`. It contains three steps to create the temporary direcrory.

1.  Before starting the job, the Spark driver checks if `/user/sparkuser/parquet` exists. If it doesn't exist, spark will create it.
2. Start Spark job, `/user/sparkuser/parquet/_temporary/0` directory is created.
3. Launch spark task, 
`/user/sparkuser/write/_temporary/0/_temporary/attempt_202308141254068848329907173588393_0025_m_000000_25/` directory is created.

Therefore, when Gluten call velox parquet writer to write parquet file, the path obtained from spark has not been created yet. It is necessary to create the folder before writing the data.

**Comment by Yohahaha** [comment]
@JkSelf Thanks! I got your points. 

Maybe implement a logic which check whether parent dir exist then mkdir in Velox parquet writer would more make sense? Current implementation will create wrong dir if we pass wrong file path to HdfsWriteFile.

**Comment by JkSelf** [comment]
Yes. Maybe we can also put this logic in Gluten. I will have a try later. Thanks for your reply.

**Pull request closed without merging**
