### PR TITLE
Refactor Decimal Average Implementation

### PR DESCRIPTION
**Pull request by majetideepak**
This refactor is to help implement the Presto Sum Aggregate function that also uses
VARBINARY as an intermediate type.
The plan for Sum is to re-use the DecimalAggregate class.

### CODE REVIEW

**Comment by karteekmurthys** [comment]
LGTM! linux-build is failing.

**Comment by majetideepak** [comment]
The build error `collect2: fatal error: ld terminated with signal 9 [Killed]` is seen on the main branch as well.
This is due to insufficient memory on the build machine.
CC: @kgpai

**Comment by majetideepak** [comment]
The PR https://github.com/facebookincubator/velox/pull/4005 shows how Decimal sum would look like with this change.

**Comment by majetideepak** [comment]
@Yuhta anything I can help with for the failures?

**Comment by Yuhta** [comment]
@majetideepak The internal ones are actually ok, just want the `linux-build` CCI job to pass to be safe, it was broken for a while.

**Comment by majetideepak** [comment]
@Yuhta can you rerun the workflow?

**Comment by Yuhta** [comment]
@majetideepak  Can you try rebase to latest `main` branch?

**Comment by majetideepak** [comment]
@Yuhta all tests are now passing.

**Pull request closed without merging**
