### PR TITLE
Fix undefined symbols MakeCheckOpValueString

### PR DESCRIPTION
**Pull request by yingsu00**
Fixes https://github.com/facebookincubator/velox/issues/6621

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]
nit: order the include in alphabetic order.

**Comment by majetideepak** [comment]
@yingsu00 I am marking this ready for review and it seems to fix the problem.
I don't know why we have to add this now after moving the arrow parquet writer code.
CC: @pedroerp

**Comment by majetideepak** [comment]
This also seems to only happen on MacOS.

**Comment by yingsu00** [comment]
> nit: order the include in alphabetic order.

The formatter insists to make it this order, otherwise the format-check would fail

**Comment by yingsu00** [comment]
> @yingsu00 I am marking this ready for review and it seems to fix the problem. I don't know why we have to add this now after moving the arrow parquet writer code. CC: @pedroerp

THank you @majetideepak I think maybe this header was included in some other Arrow code before. MakeCheckOpValueStringstd<T>() is a template function and its generic type implementation is defined in this header. The specialized ones were defined in the corresponding .cc file and included in the glog::glog lib.
```
template <typename T>
inline void MakeCheckOpValueString(std::ostream* os, const T& v) {
  (*os) << v;
}

// Overrides for char types provide readable values for unprintable
// characters.
template <> GLOG_EXPORT
void MakeCheckOpValueString(std::ostream* os, const char& v);
template <> GLOG_EXPORT
void MakeCheckOpValueString(std::ostream* os, const signed char& v);
template <> GLOG_EXPORT
void MakeCheckOpValueString(std::ostream* os, const unsigned char& v);

// Provide printable value for nullptr_t
template <>
GLOG_EXPORT void MakeCheckOpValueString(std::ostream* os,
                                        const std::nullptr_t& v);
```

**Pull request closed without merging**
