### PR TITLE
Remove DuckDB functions

### PR DESCRIPTION
**Pull request by majetideepak**
DuckDB functions code is not used anywhere and can be removed.

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Comment by pedroerp** [comment]
I always wondered why we still had this code around :) Thanks for cleaning this up

**Comment by majetideepak** [comment]
@mbasmanova any issues with merging this change?

**Comment by pedroerp** [comment]
@kgpai is merging it.

**Pull request closed without merging**
