### PR TITLE
fix: Use input directly in createLongDecimalVector if aligned

### PR DESCRIPTION
**Pull request by rui-mo**
In 'createLongDecimalVector', uses the input directly if it is already 16-byte 
aligned.
Follow-up for: https://github.com/facebookincubator/velox/pull/11404.

### CODE REVIEW

**Comment by rui-mo** [comment]
@jinchengchenghh Opened this PR to address https://github.com/facebookincubator/velox/pull/11404#discussion_r1853164162. Would you like to take a look? Thanks.

**Review by jinchengchenghh — APPROVED** [review]
Thanks! Do we have API for checking the address 16 byte aligned?

**Comment by rui-mo** [comment]
> Do we have API for checking the address 16 byte aligned?

No, I did not find an API for this purpose.

**Comment by rui-mo** [comment]
@majetideepak Would you like to review this minor follow-up? Thanks!

**Review by majetideepak — APPROVED** [review]

**Review by gggrace14 — APPROVED** [review]

**Pull request closed without merging**
