### PR TITLE
Fix a bug in VectorArithmetic::processAsDense

### PR DESCRIPTION
**Pull request by yvxiang**

### CODE REVIEW

**Comment by yvxiang** [comment]
@mbasmanova can someone review this pr?

**Comment by yvxiang** [comment]
I refer to some PRs and change the title and description, is it ok now?

I have not run a benchmark because time is limited, maybe later.

But as you mentioned, VectorArithmetic.cpp is just an example,  all arithmetic functions is scalar functions now, did you compared the performance between implementation in Arithmetic.h and VectorArithmetic.cpp？Compiler can optimize loop in SimpleFunctionAdapter too? Why not make it can be used in production code, and which vector functions are ready to be used? 

Thanks:)

**Review by mbasmanova — APPROVED** [review]

**Comment by yvxiang** [comment]
Thanks, I see what you mean.

My question is why not make it ready for production, it seems have higher performance.
Other vector functions registered by VELOX_REGISTER_VECTOR_FUNCTION can not be use too?

**Comment by mbasmanova** [comment]
> My question is why not make it ready for production, it seems have higher performance.

Too many things to do, not enough time :-)

> Other vector functions registered by VELOX_REGISTER_VECTOR_FUNCTION can not be use too?

All functions except VectorArithmetic can be used.

**Pull request closed without merging**
