### PR TITLE
Support write file sink for hdfs

### PR DESCRIPTION
**Pull request by KevinyhZou**
### Support  write file sink for hdfs
1. Implement a write sink for hdfs file in DataSink.cpp base on implement of HdfsWriteFile(#3021), the class name is WriteFileSink, which can also support to write local file.
2. Implement a e2e test to read and write dwrf format file from hdfs in HdfsFilesytemTest.cpp, which shows the usage of this wirte file sink for hdfs.

### CODE REVIEW

**Comment by KevinyhZou** [comment]
cc @mbasmanova

**Comment by mbasmanova** [comment]
@KevinyhZou We are seeing CI failures that seem to be related to some earlier PR: https://app.circleci.com/pipelines/github/facebookincubator/velox/16430/workflows/b66f9d81-7c26-4006-840a-ac4c68508bda/jobs/101767

```
The following tests FAILED:
	148 - velox_hdfs_file_test (Timeout)
```

Would you help take a look?

**Comment by KevinyhZou** [comment]
> @KevinyhZou We are seeing CI failures that seem to be related to some earlier PR: https://app.circleci.com/pipelines/github/facebookincubator/velox/16430/workflows/b66f9d81-7c26-4006-840a-ac4c68508bda/jobs/101767
> 
> ```
> The following tests FAILED:
> 	148 - velox_hdfs_file_test (Timeout)
> ```
> 
> Would you help take a look?

OK

**Comment by KevinyhZou** [comment]
> https://app.circleci.com/pipelines/github/facebookincubator/velox/16430/workflows/b66f9d81-7c26-4006-840a-ac4c68508bda/jobs/101767
image

does it have some other error logs? it seems get stuck in HdfsFileSystemTest.writeFlushFailures, but this always run succcess in my local environment.
image

**Comment by KevinyhZou** [comment]
> https://app.circleci.com/pipelines/github/facebookincubator/velox/16430/workflows/b66f9d81-7c26-4006-840a-ac4c68508bda/jobs/101767
image

does it have some other error logs? it seems get stuck in HdfsFileSystemTest.writeFlushFailures, but this always run succcess in my local environment.
image

**Comment by KevinyhZou** [comment]
> 
image
does it have some other error logs? it seesm stuck in HdfsFileSystemTest.writeFlushFailures, but it always run succss in my local environment.

**Comment by mbasmanova** [comment]
@KevinyhZou There is a button "Download the full output as a file": https://circleci.com/api/v1.1/project/github/facebookincubator/velox/101767/output/109/0?file=true&allocation-id=6372cbf9ebfaca185105d3e6-0-build%2F215C9FE9

The failures are intermittent. You can check them out here: https://app.circleci.com/pipelines/github/facebookincubator/velox?branch=main

You may want to re-run the failed job with SSH to get access to the container for debugging: 

https://app.circleci.com/pipelines/github/facebookincubator/velox?branch=main

Screen Shot 2022-11-15 at 6 40 36 AM

**Comment by mbasmanova** [comment]
@KevinyhZou I filed GitHub issue about this: #3237

**Comment by KevinyhZou** [comment]
> @KevinyhZou I filed GitHub issue about this: #3237

OK

**Comment by KevinyhZou** [comment]
> @KevinyhZou There is a button "Download the full output as a file": https://circleci.com/api/v1.1/project/github/facebookincubator/velox/101767/output/109/0?file=true&allocation-id=6372cbf9ebfaca185105d3e6-0-build%2F215C9FE9
> 
> The failures are intermittent. You can check them out here: https://app.circleci.com/pipelines/github/facebookincubator/velox?branch=main
> 
> You may want to re-run the failed job with SSH to get access to the container for debugging:
> 
> https://app.circleci.com/pipelines/github/facebookincubator/velox?branch=main
> 
> Screen Shot 2022-11-15 at 6 40 36 AM

image
hello, it seems i have no permission to re-run the failed job, can you give me the permission? @mbasmanova

**Pull request closed without merging**
