### PR TITLE
Remove -march=intel to fix build on Ubuntu(#1383)

### LINKED ISSUE #1383: Build fail on ubuntu 20.04
I'm trying to build velox on Ubuntu 20.04 using the provided script setup-ubuntu.sh
These are my steps:
```bash
git clone --recursive https://github.com/facebookincubator/velox.git
cd velox
git submodule sync --recursive
git submodule update --init --recursive
cd scripts/
sudo ./setup-ubuntu.sh
```

Unfortunately, the build fails with the following here due to folly
image

I tried using different releases of folly, to no avail.
I don't know how to fix this problem, can anyone please help me ? =)

### PR DESCRIPTION
**Pull request by xumingming**
It fix #1383.
Tested on ubuntu.

### CODE REVIEW

**Comment by majetideepak** [comment]
Should the title say `Remove -masm=intel ...` instead of `Remove -march=native ...`?

**Comment by xumingming** [comment]
> Should the title say `Remove -masm=intel ...` instead of `Remove -march=native ...`?

Good catch! Updated both the PR title and the commit message.

**Comment by majetideepak** [comment]
@xumingming thanks! Can you also write a brief description of the build failure on Ubuntu that this change fixes?

**Comment by xumingming** [comment]
> @xumingming thanks! Can you also write a brief description of the build failure on Ubuntu that this change fixes?

@majetideepak It fixes #1383 , updated the description.

**Comment by majetideepak** [comment]
@xumingming the title and commit should still say `-masm=intel` instead of `-march=intel`.
@Yuhta Is this change covered by your xsimd work?

**Comment by majetideepak** [comment]
I see that this change is similar to https://github.com/facebookincubator/velox/pull/1336

**Review by Yuhta — APPROVED** [review]

**Pull request closed without merging**
