### PR TITLE
refactor: Reduce dependencies in LocalRunnerTestBase.h

### PR DESCRIPTION
**Pull request by mbasmanova**
Differential Revision: D66667591

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]

**Comment by assignUser** [comment]
This seems to contain the changes from #11715 and #11713, should those be closed?

**Comment by mbasmanova** [comment]
> This seems to contain the changes from #11715 and #11713, should those be closed?

This is expected as this is a stacked diff.

**Comment by assignUser** [comment]
I see, that's not really visible on the OSS side, just looks like 3 similar PRs ^^

**Comment by mbasmanova** [comment]
> I see, that's not really visible on the OSS side, just looks like 3 similar PRs ^^

True. You can see the individual PRs in the "commits" tab, but it is not super clear.

**Pull request closed without merging**
