### PR TITLE
Add next_day Spark function

### PR DESCRIPTION
**Pull request by kerwin-zk**
Add next_day Spark function. #4741

### CODE REVIEW

**Comment by kerwin-zk** [comment]
@mbasmanova  Could you help review this fuction?

**Comment by kerwin-zk** [comment]
@mbasmanova  Could you help review this fuction?

**Review by mbasmanova — COMMENTED** [review]
@bikramSingh91 Bikram, would you help review this PR?

**Comment by kerwin-zk** [comment]
@PHILO-HE ok.

**Pull request closed without merging**
