### PR TITLE
Upgrade protobuf to v26

### PR DESCRIPTION
**Pull request by majetideepak**

### CODE REVIEW

**Comment by assignUser** [comment]
If this works and we update protobuf we should also go over the protobuf.cmake in resolve_dependency as that was one of the first ones added. We can probably update it a bit!

**Comment by rui-mo** [comment]
> Protobuf V22 has breaking changes and requires additional dependencies.

@majetideepak May I ask if you are talking about the absl dependencies? I just encountered similar issue and linked them like https://github.com/facebookincubator/velox/pull/9559/files#diff-e0d8ea8469f5f57022c8b6a8e1816f94d346f5739c48231f437fc398cf401181R212-R281. Thanks.

**Comment by majetideepak** [comment]
@rui-mo here is the link for reference https://protobuf.dev/support/migration/#cpp-22
yes, absl is the dependency. Why do you need absl in your PR?

**Comment by rui-mo** [comment]
@majetideepak My PR depends on grpc, which installs a protobuf requiring absl dependencies in my local test. Here is the link https://github.com/grpc/grpc for reference. I assume I will need to use the protobuf provided by Velox instead of a grpc installed one.

**Comment by majetideepak** [comment]
> I assume I will need to use the protobuf provided by Velox instead of a grpc installed one.

Yes!

**Pull request closed without merging**
