### PR TITLE
Move StreamingAggregation's initialization from ctor to initialize().

### PR DESCRIPTION
**Pull request by usurai**
Part of https://github.com/facebookincubator/velox/issues/7233:
1. Extend `StreamingAggregationTest` to trigger memory pool allocation at `StreamingAggregation`'s initialization, so the driver can have a chance to detect if it's in operator ctor.
2. Move `StreamingAggregation`'s initialization from ctor to `initialize()`.

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
@usurai Thank you for much for all these fixes and tests.

**Comment by mbasmanova** [comment]
@usurai I believe this change is causing a crash in StreamingAggregation::close() when it is called without calling initialize().

**Comment by usurai** [comment]
@mbasmanova Could you point me to log/reproduce of the crash?
My assumption of these change is that `initialize()` is guaranteed to be called for every operator. Is that correct?

**Comment by mbasmanova** [comment]
@usurai Here, if one op->initialize() throws, the rest won't be called. I fixed this crash in #7325

```
void Driver::initializeOperators() {
  if (operatorsInitialized_) {
    return;
  }
  operatorsInitialized_ = true;
  for (auto& op : operators_) {
    op->initialize();
  }
}
```

**Comment by usurai** [comment]
@mbasmanova  Oh.. I didn't consider the partially init scenario. Thanks for the fix!

**Pull request closed without merging**
