### PR TITLE
Fix velox_tpch_benchmark compilation failure

### PR DESCRIPTION
**Pull request by pramodsatya**
Fixes the velox_tpch_benchmark build failure seen on MacOS.

### CODE REVIEW

**Comment by mbasmanova** [comment]
Are we not building velox_tpch_benchmark in CicleCI? If so, let's update CircleCI jobs to build it. CC: @kgpai

**Comment by kgpai** [comment]
This should be built if VELOX_ENABLE_BENCHMARKS is enabled, that is done with make benchmarks-basic-build , so it should be built as a part of that process. Typically we run this via build-benchmarks job in circleci.

**Comment by pramodsatya** [comment]
> @pramodsatya Can you add more details on where you are seeing this compilation failure ?

Hi @kgpai, CI doesn't fail but when I build velox_tpch_benchmark locally, I get the following error:
```
velox/velox/benchmarks/tpch/TpchBenchmark.cpp:173:14: error: no matching constructor for initialization of 'std::pair<std::unique_ptr<TaskCursor>, std::vector<RowVectorPtr>>' (aka 'pair<unique_ptr<facebook::velox::exec::test::TaskCursor>, vector<shared_ptr<facebook::velox::RowVector>>>')
      return {nullptr, {}};
```

**Review by aditi-pandit — COMMENTED** [review]
Thanks for this change Pramod. Please can you also add velox_tpch_benchmark to the CircleCI run.

**Comment by pramodsatya** [comment]
Hi Aditi, as @kgpai had shared, velox_tpch_benchmark is being built in linux-benchmarks-basic CI job. Locally the build fails on my Macos though, updating the dependencies by re-running setup-macos.sh didn't help. Will check further and update.

**Comment by isadikov** [comment]
Hi @pramodsatya. I also encountered this issue when building on macos with M1 and confirm the patch solves the problem.  Is there an ETA on when this PR will be merged?

**Comment by pramodsatya** [comment]
Hi @isadikov, thanks for confirming the issue. I suspected there was an issue with my local setup and wanted to investigate before proceeding further. 
Hi @aditi-pandit, since this build failure appears to be an issue on macos, could we please proceed with merging this PR? Also, would it be feasible to add a macos-benchmarks CI job to catch such errors going forward?

**Comment by aditi-pandit** [comment]
We can add the fix. macos benchmarks are only used for local debugging on our parts. So in the future also we might find issues on macos while local debugging only. 
@kgpai : What do you think ? Are there particular compiler or flag differences that could make such errors frequent ?

**Comment by kgpai** [comment]
Hi @pramodsatya , Can you give me a short repro for the mac that gives this error ? I will try to repro on my end and validate.

**Comment by pramodsatya** [comment]
Hi @kgpai, I am building velox_tpch_benchmark in Debug mode with CLion (on Intel i7 Macbook running MacOS 13.1). The build command is:
```
cmake --build velox/cmake-build-debug --target velox_tpch_benchmark -j 9
```
I am getting the following error:
```
velox/velox/benchmarks/tpch/TpchBenchmark.cpp:173:14: error: no matching constructor for initialization of 'std::pair<std::unique_ptr<TaskCursor>, std::vector<RowVectorPtr>>' (aka 'pair<unique_ptr<facebook::velox::exec::test::TaskCursor>, vector<shared_ptr<facebook::velox::RowVector>>>')
      return {nullptr, {}};
             ^~~~~~~~~~~~~
```
Please let me know if any additional information is needed. Thanks!

**Comment by kgpai** [comment]
@pramodsatya I can validate that I am seeing the same error on a Mac and this goes away with the fix. 
I suppose the reason this wasnt caught is because we dont run benchmark builds on the Mac :(  (among with several other things). 
I will work on merging this , Thanks !

**Comment by kgpai** [comment]
@pramodsatya Can you rebase with latest main and push to this branch ? Thanks !

**Comment by pramodsatya** [comment]
Hi @kgpai, rebased on latest main, thanks!

**Pull request closed without merging**
