### PR TITLE
install dependencies needed to support Azure Storage ABFS Connector

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
install dependencies needed to support Azure Storage ABFS Connector, This update is one of the modifications necessary for issue https://github.com/facebookincubator/velox/issues/6415

### CODE REVIEW

**Comment by gaoyangxiaozhu** [comment]
can anyone help review ?

**Comment by pedroerp** [comment]
@kgpai @assignUser could you guys help review this PR?

**Review by assignUser — APPROVED** [review]
Looks fine to me, I will add it to the conda env too (not merged yet)

**Comment by gaoyangxiaozhu** [comment]
> Looks fine to me, I will add it to the conda env too (not merged yet)

hey @assignUser thank you for approved. Would i know when this part change can be merged ? then I can do submit the following ABFS Read/Write PR both the PRe depends on this PR.

**Review by kgpai — APPROVED** [review]

**Comment by gaoyangxiaozhu** [comment]
> @kgpai has imported this pull request. If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D49393106).

hey @kgpai can i know when this change will be merged ?

**Pull request closed without merging**
