### PR TITLE
add substrait extension yaml files for further function registry

### PR DESCRIPTION
**Pull request by chaojun-zhang**
copy substrait extension yaml files from https://github.com/substrait-io/substrait/tree/main/extensions for further function registry

### CODE REVIEW

**Comment by pedroerp** [comment]
Hi @chaojun-zhang. For future reference, could you add more context on what these extensions are and why they are needed?

**Comment by chaojun-zhang** [comment]
> Hi @chaojun-zhang. For future reference, could you add more context on what these extensions are and why they are needed?

Yes,  plan to use Substrait YAML extension file as input to establish the function signatures instead of a hard-coded function signatures [here ](https://github.com/facebookincubator/velox/blob/09a57405ca7234c8093ee64dce4819f1c2006fc2/velox/substrait/VeloxToSubstraitPlan.cpp#L310)

**Comment by mbasmanova** [comment]
@chaojun-zhang ChaoJun, would it be possible to provide the overall design for how the function mappings will be handled in the Substrat-to-Velox plan conversions? I see that functions are currently hard-coded and hope we can move away from doing that. However, it is not clear to me what the new logic will be.

**Comment by chaojun-zhang** [comment]
> @chaojun-zhang ChaoJun, would it be possible to provide the overall design for how the function mappings will be handled in the Substrat-to-Velox plan conversions? I see that functions are currently hard-coded and hope we can move away from doing that. However, it is not clear to me what the new logic will be.

Sure,  let's schedule a team meeting for this,  how about 5:00-6:00 PM the day on 24/08 or 25/08  based on your time zone ?  or you can provide your available time slot?

**Comment by mbasmanova** [comment]
@chaojun-zhang Let's try to find a time slot on Slack. We would also need a written design document. Do you have something I can read ahead of the meeting?

**Pull request closed without merging**
