### PR TITLE
Add support for decimal and timestamp inputs to hash and xxhash Spark functions

### PR DESCRIPTION
**Pull request by jinchengchenghh**
Spark implementation: https://github.com/apache/spark/blob/branch-3.3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L538

### CODE REVIEW

**Comment by jinchengchenghh** [comment]
Wait for https://github.com/facebookincubator/velox/pull/5444

**Comment by rui-mo** [comment]
Can we find Spark's implementations and add them in the PR description? We also need to ensure the implementations are the same as Spark's. 
Looks it would be better to separate this PR into several small PRs according to the data type.

**Comment by jinchengchenghh** [comment]
Can you help review this PR? Thanks! @mbasmanova

**Review by mbasmanova — APPROVED** [review]
@jinchengchenghh Thank. Looks good to me.

**Pull request closed without merging**
