### PR TITLE
Add uuid function and type

### PR DESCRIPTION
**Pull request by pranjalssh**

### CODE REVIEW

**Review by majetideepak — COMMENTED** [review]
We are introducing HUGEINT (int128_t) type as part of https://github.com/facebookincubator/velox/pull/4434
Do we need another CPP type for UUID? Can it be a logical type based on HUGEINT?

**Comment by pranjalssh** [comment]
@majetideepak yes that sounds like a good idea. One difference is uuid uses unsigned int - so we'll have to typecast when checking for comparisions.

**Comment by pranjalssh** [comment]
@majetideepak Can you please let me know once the HugeInt change is merged? I'll redo this PR.

**Comment by majetideepak** [comment]
@pranjalssh Will do! I am just waiting for https://github.com/facebookincubator/velox/pull/4638 to be merged first.

**Comment by yzhang1991** [comment]
Hi @pranjalssh, do you plan to move forward with this PR?

**Pull request closed without merging**
