### PR TITLE
Add inverse_f_cdf Presto Function

### PR DESCRIPTION
**Pull request by rrando901**
Add Presto function inversef_cdf following the Java implementation([source](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java#L909))

Resolves: https://github.com/facebookincubator/velox/issues/5429

### CODE REVIEW

**Comment by rrando901** [comment]
Fuzzer Results

```
I20230627 13:03:53.577378 1508538 ExpressionVerifier.cpp:56] ===================
I20230627 13:03:53.577400 1508538 ExpressionVerifier.cpp:67] All results match.
I20230627 13:03:53.577447 1508538 ExpressionFuzzer.cpp:1357] ==============================> Done with iteration 366
I20230627 13:03:53.577965 1508538 ExpressionFuzzer.cpp:1092] ==============================> Top 1 by number of rows processed
I20230627 13:03:53.577987 1508538 ExpressionFuzzer.cpp:1094] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230627 13:03:53.578002 1508538 ExpressionFuzzer.cpp:1098] inverse_f_cdf 38489 100.00% 4482
I20230627 13:03:53.578020 1508538 ExpressionFuzzer.cpp:1104] ==============================> Bottom 1 by number of rows processed
I20230627 13:03:53.578035 1508538 ExpressionFuzzer.cpp:1106] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230627 13:03:53.578050 1508538 ExpressionFuzzer.cpp:1111] inverse_f_cdf 38489 100.00% 4482
I20230627 13:03:53.578066 1508538 ExpressionFuzzer.cpp:1124] ==============================> All stats sorted by number of times the function was chosen
I20230627 13:03:53.578080 1508538 ExpressionFuzzer.cpp:1126] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230627 13:03:53.578102 1508538 ExpressionFuzzer.cpp:1130] inverse_f_cdf 38489 100.00% 4482
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

**Comment by aditi-pandit** [comment]
@rrando901 : Please can you check the macos-build-macos-intel failures.

**Comment by rrando901** [comment]
@aditi-pandit I see the following error in the macos-build-macos-intel failure. 
I'm not sure if this is related to my changes or not.

```
/Users/distiller/project/_build/debug/_deps/folly-src/folly/Memory.h:289:33: error: 'HMAC_CTX_free' is deprecated [-Werror,-Wdeprecated-declarations]
  void operator()(T* t) const { f(t); }
                                ^
/Applications/Xcode-14.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__memory/unique_ptr.h:305:7: note: in instantiation of member function 'folly::static_function_deleter<hmac_ctx_st, &HMAC_CTX_free>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/Users/distiller/project/_build/debug/_deps/folly-src/folly/ssl/OpenSSLHash.h:232:14: note: in instantiation of member function 'std::unique_ptr<hmac_ctx_st, folly::static_function_deleter<hmac_ctx_st, &HMAC_CTX_free>>::reset' requested here
        ctx_.reset(HMAC_CTX_new());
             ^
/Users/distiller/deps/include/openssl/hmac.h:35:1: note: 'HMAC_CTX_free' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 void HMAC_CTX_free(HMAC_CTX *ctx);
^
/Users/distiller/deps/include/openssl/macros.h:193:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/Users/distiller/deps/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
1 error generated.
```

**Comment by rrando901** [comment]
@aditi-pandit I've opened an a new PR with these changes that is up-to-date with the main branch - https://github.com/facebookincubator/velox/pull/5774

**Pull request closed without merging**
