### PR TITLE
Expose queryThreadIoLatency counter in connector

### PR DESCRIPTION
**Pull request by akashsha1**
Expose query thread IO Latency counter in connector, which would help analyze latencies observed by Velox in Gluten.

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
It would be nice to document all these runtime stats and make sure their names are consistent and intuitive.

**Comment by mbasmanova** [comment]
@akashsha1 There are CI failures. Would you take a look?

**Comment by akashsha1** [comment]
> 



> It would be nice to document all these runtime stats and make sure their names are consistent and intuitive.

Where would you suggest adding such a documentation? 
There is documentation about them present in:
https://github.com/facebookincubator/velox/blob/main/velox/dwio/common/IoStatistics.h

**Comment by mbasmanova** [comment]
> Where would you suggest adding such a documentation?

Maybe somewhere here: https://facebookincubator.github.io/velox/develop/debugging.html

**Comment by zhouyuan** [comment]
@akashsha1 
you may need to update the tests with the new metric here:
https://github.com/facebookincubator/velox/blob/main/velox/exec/tests/PrintPlanWithStatsTest.cpp#L174

-yuan

**Comment by akashsha1** [comment]
> @akashsha1 you may need to update the tests with the new metric here: https://github.com/facebookincubator/velox/blob/main/velox/exec/tests/PrintPlanWithStatsTest.cpp#L174
> 
> -yuan

thanks for pointing this out. Fixing the test worked.

**Pull request closed without merging**
