### PR TITLE
Add leading zeroes in decimal to string

### PR DESCRIPTION
**Pull request by pramodsatya**
Adds leading zeroes in decimal to string function, by extending the utility function to help generate decimal IN-list ( #4031 ).

### CODE REVIEW

**Comment by karteekmurthys** [comment]
Can you explain why leading zeros are important and how it is related to IN-List. Is it for verification?

**Comment by majetideepak** [comment]
@pramodsatya Why does the IN-LIST require leading zeros?

**Comment by pramodsatya** [comment]
@karteekmurthys, @majetideepak, without leading zeroes the precision of the decimals in the IN-list string is inferred wrongly. The following error is seen for the IN-list, `IN (0.01, 0.03, 0.05)`, with decimals of type DECIMAL(5, 2):
```
Reason: Scalar function signature is not supported: in(DECIMAL(5,2), ARRAY<DECIMAL(3,2)>). Supported signatures: ...
```
The PR is opened as suggested here: https://github.com/facebookincubator/velox/pull/4031/files#r1286316620 .

**Comment by karteekmurthys** [comment]
> Supported

How about a cast to decimal(5,2) in the INlist if possible?

**Comment by majetideepak** [comment]
@pramodsatya I thought you fixed a bug in the formatDecimal and hence asked to open a separate PR.
As @karteekmurthys mentioned other tests are using cast inside the IN List. Example: 
`"c0 IN ( CAST(1.2 AS REAL), CAST(1.3 AS REAL), null )`
We don't need to modify the formatDecimal function.

**Comment by pramodsatya** [comment]
Thanks for the suggestion @majetideepak, @karteekmurthys. Closing this PR and will use cast in the IN-list.

**Pull request closed without merging**
