### PR TITLE
fix: Fix trace exception and code refactor

### PR DESCRIPTION
**Pull request by xiaodouchen**
1. "VELOX_SPILL_LIMIT_EXCEEDED" -> "VELOX_TRACE_LIMIT_EXCEEDED" in updateTracedBytesAndCheckLimit().
2. Typo in the comment of OperatorTraceTest.

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]
@xiaodouchen thanks for the fix!

**Review by xiaoxmeng — COMMENTED** [review]
@xiaodouchen can you fix the format? Thanks!

**Review by xiaoxmeng — COMMENTED** [review]
@xiaodouchen  There is circular dependence detected by Meta internal build tool. Could you help move velox/exec/TraceConfig.h to velox/common/base/TraceConfig.h and also move VELOX_TRACE_LIMIT_EXCEEDED there? Thanks!

**Comment by xiaodouchen** [comment]
> @xiaodouchen There is circular dependence detected by Meta internal build tool. Could you help move velox/exec/TraceConfig.h to velox/common/base/TraceConfig.h and also move VELOX_TRACE_LIMIT_EXCEEDED there? Thanks!

Thank you for the suggestion. It has been fixed.

**Pull request closed without merging**
