### PR TITLE
Add support for GZIP compression in native parquet reader

### PR DESCRIPTION
**Pull request by majetideepak**
Include support for compressed dictionary pages.
Extend E2EFilterTest::integerDictionary with ZSTD, GZIP compression.
Enable reading Presto-generated Parquet files.

### CODE REVIEW

**Comment by Yuhta** [comment]
@majetideepak It will take some time (probably several days) to rebuild the arrow in monorepo with compression support.  If we are in a hurry I can exclude the test from our internal build.  Otherwise I will merge this once the arrow in monorepo is rebuilt.

**Comment by majetideepak** [comment]
@Yuhta Orri mentioned that I can catch an exception for missing compression and exclude the test. I will add that support now.

**Comment by majetideepak** [comment]
@Yuhta can you import and check? I was able to use the arrow API to check if the compression is available.

**Comment by majetideepak** [comment]
It will be nice to add this support soon.

**Pull request closed without merging**
