### PR TITLE
Replace BlockingCounter with folly::Latch in CachedFactoryTest

### PR DESCRIPTION
**Pull request by usurai**
Resolve `TODO` in `CachedFactoryTest`:
https://github.com/facebookincubator/velox/blob/35ab8cc2fcb3da75b602cd6f3187314ded6507f2/velox/common/caching/tests/CachedFactoryTest.cpp#L115-L117

### CODE REVIEW

**Comment by usurai** [comment]
@mbasmanova Could you please take a look?

**Comment by usurai** [comment]
Kindly ping.

**Review by mbasmanova — COMMENTED** [review]
@Yuhta Jimmy, would you help review this PR?

**Comment by mbasmanova** [comment]
@usurai I see that CI is red. Would you take a look?

**Comment by usurai** [comment]
> @usurai I see that CI is red. Would you take a look?

The failed CI test seems to be related to memory allocation, and it is unrelated to the change.

**Comment by mbasmanova** [comment]
@usurai 

> The failed CI test seems to be related to memory allocation, and it is unrelated to the change.

Can you file a GitHub issue? @xiaoxmeng Would you help look into this?

We need to make sure we do not merge PRs with red CI.

**Comment by usurai** [comment]
Since the cause of the CI failure is still unclear(output exceeded the limit), turning the PR into draft to investigate the issue.

**Comment by usurai** [comment]
@mbasmanova Seems the CI issue has been addressed in #5003 .
@Yuhta The PR is ready for review.

**Pull request closed without merging**
