### PR TITLE
Fix Benchmark CI run

### PR DESCRIPTION
**Pull request by majetideepak**
Resolves https://github.com/facebookincubator/velox/issues/1210

### CODE REVIEW

**Comment by majetideepak** [comment]
@mbasmanova This should resolve the issue. The CI still seems to fail since the main branch does not have this change.
The `linux-build` failures are unrelated.

**Comment by mbasmanova** [comment]
> The linux-build failures are unrelated.

@majetideepak Deepak, would you rebase on top to main. https://github.com/facebookincubator/velox/pull/1209 should allow linux-build CI job to pass.

**Comment by mbasmanova** [comment]
> This should resolve the issue. 

Curious how did you verify that these changes fix ci/circleci: linux-benchmarks-basic job.

**Comment by majetideepak** [comment]
@mbasmanova The CI job said that the executable was missing. I verified that. This change fixes the issue. I see that the benchmark executable is built and present as expected.

**Review by mbasmanova — APPROVED** [review]
@majetideepak Thank you, Deepak, for a quick fix.

**Pull request closed without merging**
