### PR TITLE
feat: Support viewfs file system in velox

### PR DESCRIPTION
**Pull request by JkSelf**
Support [Viewfs ](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/ViewFs.html)file system in velox.

### CODE REVIEW

**Review by majetideepak — COMMENTED** [review]
@JkSelf can we add some read/write tests? If not, can we add some unit tests for the "viewfs" scheme?

**Comment by JkSelf** [comment]
> @JkSelf can we add some read/write tests? If not, can we add some unit tests for the "viewfs" scheme?

@majetideepak Thanks for your review. I have fixed the failed unit tests and added the viewfs scheme test. Can you help to review again? Thanks.

**Review by majetideepak — APPROVED** [review]
Thanks, @JkSelf

**Comment by kgpai** [comment]
Hi @JkSelf , Can you confirm/investigate that the fuzzer failure isnt due to your changes ?

**Comment by JkSelf** [comment]
> Hi @JkSelf , Can you confirm/investigate that the fuzzer failure isnt due to your changes ?

@kgpai The failure is not due to this pr. I have rebased and the tests passed.

**Review by bikramSingh91 — APPROVED** [review]

**Comment by JkSelf** [comment]
@kgpai Can you help to merge this PR? Thanks.

**Pull request closed without merging**
