### PR TITLE
[WIP] add env setup script for centos-7

### PR DESCRIPTION
**Pull request by zhouyuan**

### CODE REVIEW

**Comment by pedroerp** [comment]
What are the main differences from this one to setup_centos8.sh? Is there a way to de-duplicate some of the repeated steps?

Also, if we want to support this we should find a way to set up a CI job to exercise the script periodically against a centos7 docker image.

Cc: @kgpai @majetideepak @assignUser

**Comment by kgpai** [comment]
FYI - @zhouyuan Centos 7 will end of lifed in a little more than 6 months : https://www.redhat.com/en/topics/linux/centos-linux-eol .

**Comment by assignUser** [comment]
With the eol of centos7 being pretty imminent I don't think it makes sense to add this tbh. If we want to add it I think a general 'setup-centos' script would be better?

**Comment by zhouyuan** [comment]
@pedroerp @kgpai @assignUser 
Thanks for looking and also the great inputs! The main difference for CentOS7 is some libraries are too old, we need to compile and install newer one to make Velox happy to compile. 
There are quite a few PRC Gluten users are still using CentOS 7, mostly due to some legacy applications/services I think. Understood the concerns on EOL of 7 and I agree on this. Merge with the script on `setup-centos8` looks like a good idea, as for Ubuntu there's only one `setup-ubunbtu.sh`. I'll check with them for what's the best, or if it's able to maintain this by themself. 

thanks, -yuan

**Pull request closed without merging**
