### PR TITLE
refactor(parquet): Move arrow levelComparison to common

### PR DESCRIPTION
**Pull request by majetideepak**
Both Parquet reader and writer depend on levelComparison.
This currently resides in parquet/writer/arrow which introduces a dependency of the writer to the reader.
Refactor to parquet common along with renaming variables to Velox coding convention.

Fixes: https://github.com/facebookincubator/velox/issues/11678

### CODE REVIEW

**Review by pedroerp — APPROVED** [review]
Not sure if it's in draft mode, but looks good to me. Let's just ensure all CI jobs are healthy (some are still running).

**Comment by majetideepak** [comment]
I moved it to draft mode to undo the unrelated thrift refactor. The changes now are minimal.

**Comment by pedroerp** [comment]
Alright, let me know once you work through the CI failures.

**Comment by majetideepak** [comment]
@pedroerp this is ready, CI is green.

**Review by pedroerp — APPROVED** [review]
Thank you @majetideepak

**Comment by bikramSingh91** [comment]
Struggling with the build system internally to unblock merge, will continue working on it tomorrow.

**Comment by bikramSingh91** [comment]
@majetideepak do you mind replacing 

```#include <external/xxhash/xxhash.h>```
with 
```
#include <xxhash.h>
```
in https://github.com/facebookincubator/velox/blob/3dd572fe47b7aa78f255b407995957f8589b785e/velox/dwio/parquet/common/XxHasher.cpp#L22

This would make it conform to how its being included in other places in velox like in ApproxDistinctAggregate.cpp, BinaryFunctions.h, etc.. and also resolves the include automatically.

**Pull request closed without merging**
