### PR TITLE
Disable stringop-overflow warning

### PR DESCRIPTION
**Pull request by save-buffer**
I found this error in #2994. This PR disables the flag that caused the issue due to it being a false positive.

### CODE REVIEW

**Comment by save-buffer** [comment]
@majetideepak Please take a look!

**Comment by pedroerp** [comment]
Is this something we should report upstream to the DuckDB team?

**Comment by save-buffer** [comment]
I didn't have any issues building duckdb, only Velox. I think the issue is in the amalgamation generation, so it should be reported to whoever generates that.

**Comment by pedroerp** [comment]
Makes sense. Thanks for looking into this!

**Pull request closed without merging**
