### PR TITLE
Use Velox Build Type for Arrow Build

### PR DESCRIPTION
**Pull request by majetideepak**
This fix helps with debugging Arrow integrations.

### CODE REVIEW

**Comment by Yuhta** [comment]
For some reason thrift is not built by the time we build arrow_bridge?

**Comment by majetideepak** [comment]
I also feel the Velox CI image should contain the Thrift dependency to save CI build time. CC @kgpai

**Comment by majetideepak** [comment]
@Yuhta Adding a dependency did not help.

**Comment by majetideepak** [comment]
I built this locally. The thrift library name is `libthriftd.a`

**Comment by majetideepak** [comment]
@Yuhta all checks are passing. Can you please import and merge this? Thanks.

**Pull request closed without merging**
