### PR TITLE
Remove the usage of "using namespace std"

### PR DESCRIPTION
**Pull request by leoluan2009**

### CODE REVIEW

**Comment by leoluan2009** [comment]
cc @mbasmanova

**Review by mbasmanova — APPROVED** [review]
@leoluan2009 Nice. Thank you for the cleanup. The PR description repeats PR title. In cases when there is nothing to add to PR title, just leave PR description empty. Otherwise, the final commit message that is created by combining PR title with description will end up with duplicate text.

**Comment by mbasmanova** [comment]
@leoluan2009 There are CircleCI failures. Ping me when these are resolved, so I can merge.

**Comment by leoluan2009** [comment]
> @leoluan2009 Nice. Thank you for the cleanup. The PR description repeats PR title. In cases when there is nothing to add to PR title, just leave PR description empty. Otherwise, the final commit message that is created by combining PR title with description will end up with duplicate text.
OK, I will remove the PR description, Thanks!

**Review by aditi-pandit — APPROVED** [review]

**Pull request closed without merging**
