### PR TITLE
Add current_timestamp Spark function

### PR DESCRIPTION
**Pull request by acvictor**
Addresses #9251 

### Description

Returns the current timestamp at the start of query evaluation as a TimestampType column. All calls of current_timestamp within the same query return the same value.

Spark docs - https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.current_timestamp.html

Alias: `now`

Implemented as https://github.com/apache/spark/blob/branch-3.4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/DateTimeUtils.scala#L1085

### CODE REVIEW

**Comment by acvictor** [comment]
@PHILO-HE can you please review? Thanks!

**Review by PHILO-HE — COMMENTED** [review]
Hi @acvictor, I found Spark will return same result for multiple rows.
E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
```txt
    a                     res                
0  10 2024-03-27 08:39:59.382                                                   
1   0 2024-03-27 08:39:59.382                                             
2   3 2024-03-27 08:39:59.382                                        
3   2 2024-03-27 08:39:59.382                                          
4   2 2024-03-27 08:39:59.382                                        
5   0 2024-03-27 08:39:59.382   
```
In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.

**Comment by PHILO-HE** [comment]
In addition, to make same result returned for one query, I found an optimizer rule has been introduced in Spark latest code (seems it does not exist in Spark-3.5 or earlier versions). Maybe, we only need to do such replacement in Gluten for earlier Spark versions.
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/finishAnalysis.scala#L108

**Comment by acvictor** [comment]
> Hi @acvictor, I found Spark will return same result for multiple rows. E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
> 
> ```
>     a                     res                
> 0  10 2024-03-27 08:39:59.382                                                   
> 1   0 2024-03-27 08:39:59.382                                             
> 2   3 2024-03-27 08:39:59.382                                        
> 3   2 2024-03-27 08:39:59.382                                          
> 4   2 2024-03-27 08:39:59.382                                        
> 5   0 2024-03-27 08:39:59.382   
> ```
> 
> In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.

Thank you @PHILO-HE. I've changed the implementation to the initialize function which will be called once per query.

**Comment by acvictor** [comment]
> > Hi @acvictor, I found Spark will return same result for multiple rows. E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
> > ```
> >     a                     res                
> > 0  10 2024-03-27 08:39:59.382                                                   
> > 1   0 2024-03-27 08:39:59.382                                             
> > 2   3 2024-03-27 08:39:59.382                                        
> > 3   2 2024-03-27 08:39:59.382                                          
> > 4   2 2024-03-27 08:39:59.382                                        
> > 5   0 2024-03-27 08:39:59.382   
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.
> 
> Thank you @PHILO-HE. I've changed the implementation to the initialize function which will be called once per query.

`foldable` is set to true for this function so it will be constant folded by Spark.

**Comment by PHILO-HE** [comment]
> > > Hi @acvictor, I found Spark will return same result for multiple rows. E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
> > > ```
> > >     a                     res                
> > > 0  10 2024-03-27 08:39:59.382                                                   
> > > 1   0 2024-03-27 08:39:59.382                                             
> > > 2   3 2024-03-27 08:39:59.382                                        
> > > 3   2 2024-03-27 08:39:59.382                                          
> > > 4   2 2024-03-27 08:39:59.382                                        
> > > 5   0 2024-03-27 08:39:59.382   
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.
> > 
> > 
> > Thank you @PHILO-HE. I've changed the implementation to the initialize function which will be called once per query.
> 
> `foldable` is set to true for this function so it will be constant folded by Spark.

Hi @acvictor, when I do some setting in Spark to exclude `ConstantFolding` optimizer, the result is still pre-produced on Spark side. Seems Spark's such optimization cannot be excluded, but must be applied. See [Spark code](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L268).

**Comment by acvictor** [comment]
> > > > Hi @acvictor, I found Spark will return same result for multiple rows. E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
> > > > ```
> > > >     a                     res                
> > > > 0  10 2024-03-27 08:39:59.382                                                   
> > > > 1   0 2024-03-27 08:39:59.382                                             
> > > > 2   3 2024-03-27 08:39:59.382                                        
> > > > 3   2 2024-03-27 08:39:59.382                                          
> > > > 4   2 2024-03-27 08:39:59.382                                        
> > > > 5   0 2024-03-27 08:39:59.382   
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.
> > > 
> > > 
> > > Thank you @PHILO-HE. I've changed the implementation to the initialize function which will be called once per query.
> > 
> > 
> > `foldable` is set to true for this function so it will be constant folded by Spark.
> 
> Hi @acvictor, when I do some setting in Spark to exclude `ConstantFolding` optimizer, the result is still pre-produced on Spark side. Seems Spark's such optimization cannot be excluded, but must be applied. See [Spark code](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L268).

@PHILO-HE do you mean we must do the constant folding but setting the current timestamp in `initialize`?

**Comment by PHILO-HE** [comment]
> > > > > Hi @acvictor, I found Spark will return same result for multiple rows. E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
> > > > > ```
> > > > >     a                     res                
> > > > > 0  10 2024-03-27 08:39:59.382                                                   
> > > > > 1   0 2024-03-27 08:39:59.382                                             
> > > > > 2   3 2024-03-27 08:39:59.382                                        
> > > > > 3   2 2024-03-27 08:39:59.382                                          
> > > > > 4   2 2024-03-27 08:39:59.382                                        
> > > > > 5   0 2024-03-27 08:39:59.382   
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.
> > > > 
> > > > 
> > > > Thank you @PHILO-HE. I've changed the implementation to the initialize function which will be called once per query.
> > > 
> > > 
> > > `foldable` is set to true for this function so it will be constant folded by Spark.
> > 
> > 
> > Hi @acvictor, when I do some setting in Spark to exclude `ConstantFolding` optimizer, the result is still pre-produced on Spark side. Seems Spark's such optimization cannot be excluded, but must be applied. See [Spark code](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L268).
> 
> @PHILO-HE do you mean we must do the constant folding but setting the current timestamp in `initialize`?

@acvictor, I mean if Spark always pre-computes the result for this function, it's impossible and unnecessary to offload it to Velox. Then, we don't need to implement this function in Velox. Do you think so?

**Comment by acvictor** [comment]
> > > > > > Hi @acvictor, I found Spark will return same result for multiple rows. E.g., here is the result for `SELECT c0, current_timestamp() from table;`:
> > > > > > ```
> > > > > >     a                     res                
> > > > > > 0  10 2024-03-27 08:39:59.382                                                   
> > > > > > 1   0 2024-03-27 08:39:59.382                                             
> > > > > > 2   3 2024-03-27 08:39:59.382                                        
> > > > > > 3   2 2024-03-27 08:39:59.382                                          
> > > > > > 4   2 2024-03-27 08:39:59.382                                        
> > > > > > 5   0 2024-03-27 08:39:59.382   
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > In this pr, it looks the implemented `call` method can return different result for different rows. Maybe, you can add a test with a batch input (use `makeRowVector` to produce multiple rows) to confirm.
> > > > > 
> > > > > 
> > > > > Thank you @PHILO-HE. I've changed the implementation to the initialize function which will be called once per query.
> > > > 
> > > > 
> > > > `foldable` is set to true for this function so it will be constant folded by Spark.
> > > 
> > > 
> > > Hi @acvictor, when I do some setting in Spark to exclude `ConstantFolding` optimizer, the result is still pre-produced on Spark side. Seems Spark's such optimization cannot be excluded, but must be applied. See [Spark code](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L268).
> > 
> > 
> > @PHILO-HE do you mean we must do the constant folding but setting the current timestamp in `initialize`?
> 
> @acvictor, I mean if Spark always pre-computes the result for this function, it's impossible and unnecessary to offload it to Velox. Then, we don't need to implement this function in Velox. Do you think so?

I see what you mean. @mbasmanova would this be useful for Presto?

**Comment by mbasmanova** [comment]
> @mbasmanova would this be useful for Presto?

@acvictor I'm not sure I understand this question? Would you elaborate?

**Comment by acvictor** [comment]
> > @mbasmanova would this be useful for Presto?
> 
> @acvictor I'm not sure I understand this question? Would you elaborate?

Presto has `current_date` Presto function implemented in Velox. From Feilong's comments above, it looks like Spark always precomputes the value for `current_timestamp` and so it is unnecessary to offload this to Velox. Can I move the `current_timestamp` implementation in this PR to functions/prestosql?

**Comment by mbasmanova** [comment]
@acvictor Presto also has this functionality. Deterministic functions with no arguments or constant arguments are evaluated on coordinator and never reach the worker. This is referred to as constant folding.

**Comment by mbasmanova** [comment]
@acvictor 

> In that case can current_date be removed?

I don't think we need to remove it. Currently, we rely on Velox applications (Presto, Spark) to have their own implementations of functions and use these for constant folding. However, I expect we'll eventually move away from that and change constant folding logic to use Velox-based implementation of the functions. Then, these will be needed. 

At some point, we'll start adding new functions only to C++. At the point, constant folding that uses Java implementations will stop working.

**Comment by acvictor** [comment]
> @acvictor
> 
> > In that case can current_date be removed?
> 
> I don't think we need to remove it. Currently, we rely on Velox applications (Presto, Spark) to have their own implementations of functions and use these for constant folding. However, I expect we'll eventually move away from that and change constant folding logic to use Velox-based implementation of the functions. Then, these will be needed.
> 
> At some point, we'll start adding new functions only to C++. At the point, constant folding that uses Java implementations will stop working.

I see, thank you! Does it make sense to close this PR or keep this function around for that eventuality?

**Comment by mbasmanova** [comment]
> Does it make sense to close this PR or keep this function around for that eventuality?

I don't have a strong opinion. @rui-mo @PHILO-HE What's your preference?

**Comment by PHILO-HE** [comment]
> > Does it make sense to close this PR or keep this function around for that eventuality?
> 
> I don't have a strong opinion. @rui-mo @PHILO-HE What's your preference?

@acvictor, @mbasmanova, I feel this pr is not needed, as discussed with Rui.
Even if we replace the constant folding logic in Presto coordinator or Spark's driver in the future, such function should be implemented differently, not under Velox's simple/vector function framework.

**Comment by mbasmanova** [comment]
> I feel this pr is not needed, as discussed with Rui.

Sounds good to me.

> Even if we replace the constant folding logic in Presto coordinator or Spark's driver in the future, such function should be implemented differently, not under Velox's simple/vector function framework.

Curious, why do you think this function won't be implemented as a simple function in Velox?

**Comment by PHILO-HE** [comment]
> > Even if we replace the constant folding logic in Presto coordinator or Spark's driver in the future, such function should be implemented differently, not under Velox's simple/vector function framework.
> 
> Curious, why do you think this function won't be implemented as a simple function in Velox?

Hi @mbasmanova, I think constant folding functions are like common C++ functions. For such a function, the result generally depends on the provided args (`current_timestamp` function even doesn't require any arg), instead of each row's input. So I guess it doesn't require the complex handling introduced in simple/vector functions framework.

**Comment by mbasmanova** [comment]
> Hi @mbasmanova, I think constant folding functions are like common C++ functions. For such a function, the result generally depends on the provided args (current_timestamp function even doesn't require any arg), instead of each row's input. So I guess it doesn't require the complex handling introduced in simple/vector functions framework.

@PHILO-HE Constant folding applies to any expression in a query that depends only on constant values or nothing at all: 2 + 5 / 100, for example. These expressions may use any of the available SQL functions and constant folding needs to be able to evaluate these expressions. Hence, it must use the same implementations of the function as are used during query execution, hence, functions that are used in constant-folding are exactly the same as used during query execution.

current_timestamp, current_date, now are a little bit special in that they never used in query execution because they are always eligible for constant folding.

**Pull request closed without merging**
