### PR TITLE
Add to_base32 and from_base32 Presto functions

### PR DESCRIPTION
**Pull request by Joe-Abraham**
Fixes https://github.com/facebookincubator/velox/issues/7294

### CODE REVIEW

**Comment by aditi-pandit** [comment]
@majetideepak : Please can you take a look at the build changes for cppcodec library in this code.

**Comment by aditi-pandit** [comment]
@Joe-Abraham : Please can you run this function with Velox fuzzer and PrestoQueryRunner, so that we are assured this is consistent with Presto java implementation.

**Comment by Joe-Abraham** [comment]
Fuzzer run for `from_base32`:

```
I20240603 14:25:17.659835 449396 FuzzerToolkit.cpp:126] ===================
I20240603 14:25:17.659845 449396 FuzzerToolkit.cpp:137] Two vectors match.
I20240603 14:25:17.659858 449396 ExpressionFuzzerVerifier.cpp:367] ==============================> Done with iteration 35741
I20240603 14:25:17.659885 449396 ExpressionFuzzerVerifier.cpp:164] ==============================> Top 1 by number of rows processed
I20240603 14:25:17.659890 449396 ExpressionFuzzerVerifier.cpp:166] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240603 14:25:17.659894 449396 ExpressionFuzzerVerifier.cpp:170] from_base32 35742 100.00% 617425
I20240603 14:25:17.659904 449396 ExpressionFuzzerVerifier.cpp:176] ==============================> Bottom 1 by number of rows processed
I20240603 14:25:17.659909 449396 ExpressionFuzzerVerifier.cpp:178] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240603 14:25:17.659912 449396 ExpressionFuzzerVerifier.cpp:183] from_base32 35742 100.00% 617425
I20240603 14:25:17.659917 449396 ExpressionFuzzerVerifier.cpp:196] ==============================> All stats sorted by number of times the function was chosen
I20240603 14:25:17.659921 449396 ExpressionFuzzerVerifier.cpp:198] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240603 14:25:17.659925 449396 ExpressionFuzzerVerifier.cpp:202] from_base32 35742 100.00% 617425
E20240603 14:25:17.659930 449396 ExpressionFuzzerVerifier.cpp:373] Total iterations: 35742
```


Fuzzer run for `to_base32`:
```
I20240603 14:21:24.365578 446190 FuzzerToolkit.cpp:126] ===================
I20240603 14:21:24.365595 446190 FuzzerToolkit.cpp:137] Two vectors match.
I20240603 14:21:24.365613 446190 ExpressionFuzzerVerifier.cpp:367] ==============================> Done with iteration 10656
I20240603 14:21:24.365648 446190 ExpressionFuzzerVerifier.cpp:164] ==============================> Top 1 by number of rows processed
I20240603 14:21:24.365651 446190 ExpressionFuzzerVerifier.cpp:166] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240603 14:21:24.365655 446190 ExpressionFuzzerVerifier.cpp:170] to_base32 10657 100.00% 174340
I20240603 14:21:24.365664 446190 ExpressionFuzzerVerifier.cpp:176] ==============================> Bottom 1 by number of rows processed
I20240603 14:21:24.365667 446190 ExpressionFuzzerVerifier.cpp:178] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240603 14:21:24.365671 446190 ExpressionFuzzerVerifier.cpp:183] to_base32 10657 100.00% 174340
I20240603 14:21:24.365676 446190 ExpressionFuzzerVerifier.cpp:196] ==============================> All stats sorted by number of times the function was chosen
I20240603 14:21:24.365680 446190 ExpressionFuzzerVerifier.cpp:198] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240603 14:21:24.365684 446190 ExpressionFuzzerVerifier.cpp:202] to_base32 10657 100.00% 174340
E20240603 14:21:24.365689 446190 ExpressionFuzzerVerifier.cpp:373] Total iterations: 10657
E20240603 14:21:24.365693 446190 ExpressionFuzzerVerifier.cpp:374] Total failed: 0
```

**Comment by aditi-pandit** [comment]
@Joe-Abraham : My bad. PrestoQueryRunner is not applicable for Expressions yet.

**Review by majetideepak — COMMENTED** [review]
@Joe-Abraham In the PR description, can you add the motivation to use a third-party library as opposed to writing our own?
One issue I see with the library is that the buffer allocations do not use a memory pool.

**Comment by Joe-Abraham** [comment]
Other PRs are raised to fix the functionality

**Comment by aditi-pandit** [comment]
> @Joe-Abraham In the PR description, can you add the motivation to use a third-party library as opposed to writing our own? One issue I see with the library is that the buffer allocations do not use a memory pool.

@majetideepak, @Joe-Abraham  : Was trying to understand the scope of the buffer allocations in this library.  If they are limited to small per-row allocations that can be released each apply function call, then we might be okay I feel. Big allocations are generally problematic when they are resident in memory for a long period. 

Though https://github.com/tplgy/cppcodec?tab=readme-ov-file#api-1 seems to indicate the user has to allocate the memory and provide it to the library.

The from/to base64 logic was copied from a library that we don't have much background. If the code for these functions is minimal then its fine. But else the library seemed quite exhaustive to me.

**Comment by majetideepak** [comment]
@aditi-pandit, @Joe-Abraham wrote a benchmark to compare existing base64 vs the library and there was a perf degradation using the library. He shared the below results with me.
image

**Pull request closed without merging**
