### PR TITLE
Move zstd codec from arrow to velox parquet writer

### PR DESCRIPTION
**Pull request by karteekmurthys**

### CODE REVIEW

**Review by pedroerp — COMMENTED** [review]
Thank you! Can you just look at the format check failure first?

**Comment by karteekmurthys** [comment]
@pedroerp I have some issues running cmake-format on M1 mac. Will fix asap.

**Comment by karteekmurthys** [comment]
@pedroerp I had conflicting python3 on my machine which was causing format-fix issue. I fixed it now. Please review.

**Comment by majetideepak** [comment]
@karteekmurthys do we need the `decompress` code also?
We should add a test as well. I believe there is some effort to add an E2E compression test.
@pdabre12, do we have a test now?

**Comment by pdabre12** [comment]
@majetideepak  It's almost ready for review https://github.com/facebookincubator/velox/pull/6826, just correcting some formatting issues.

**Comment by pedroerp** [comment]
> We should add a test as well. I believe there is some effort to add an E2E compression test.

I'm porting all the unit tests in https://github.com/facebookincubator/velox/pull/6830. These should cover GZIP, ZSTD, and etc, though they are protected by the same macros.

**Comment by majetideepak** [comment]
@pedroerp I believe we then need the decompress code as well since the tests use the Arrow Parquet Reader.

**Comment by majetideepak** [comment]
@mbasmanova, @Yuhta Since Pedro is taking time off, can you please help merge this? This is a regression with the Parquet Writer.
This PR is similar to https://github.com/facebookincubator/velox/pull/6702 Thanks!

**Comment by majetideepak** [comment]
If https://github.com/facebookincubator/velox/pull/6830/files lands first, we can enable the testing for the codec in this PR.
The tests live in `[velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp](https://github.com/facebookincubator/velox/pull/6830/files#diff-5db88eb9ef259f061a2b42cf475732d5c9b45e1c98e7bc313634dbf6c84dbef3)`

**Review by mbasmanova — COMMENTED** [review]
Why do we need another ZSTD compressor? Can we reuse velox/dwio/common/compression/Compression.cpp ?

**Comment by majetideepak** [comment]
@mbasmanova, in the first phase, Pedro and I felt we should simply move the code. We will then integrate with Velox step by step. I briefly looked at the APIs inside `velox/dwio/common/compression/Compression.cpp` and they are different from Arrow's compression APIs. Once we land the E2E Parquet writer tests, we will get more confidence to start integrating with Velox.

**Comment by majetideepak** [comment]
Pedro missed moving the compression code in the first phase. He could only move Snappy https://github.com/facebookincubator/velox/pull/6702 before his vacation time off.

**Comment by mbasmanova** [comment]
@majetideepak 

> in the first phase, Pedro and I felt we should simply move the code from Arrow to Velox. We will then integrate with Velox step by step.

Got it. Is there a GitHub issue that outlines the overall plan?

**Review by mbasmanova — APPROVED** [review]

**Comment by mbasmanova** [comment]
@majetideepak Would you rebase to resolve conflicts?

**Comment by majetideepak** [comment]
@karteekmurthys, Pedro landed the tests, can you rebase and enable ZSTD codec inside `velox/dwio/parquet/writer/arrow/tests/FileSerializeTest.cpp`?

**Comment by majetideepak** [comment]
> Is there a GitHub issue that outlines the overall plan?

@mbasmanova I just updated the discussion here https://github.com/facebookincubator/velox/discussions/6193#discussioncomment-7199940 with some pending tasks.
I will create Github issues for each task. Ying already opened one for compression https://github.com/facebookincubator/velox/issues/6901

**Comment by majetideepak** [comment]
@karteekmurthys There are tests in `parquet/writer/arrow/tests/ColumnWriterTest.cpp` and `parquet/writer/arrow/tests/FileSerializeTest.cpp` also.

**Comment by karteekmurthys** [comment]
I moved this PR to: https://github.com/facebookincubator/velox/pull/6915.
Ahana-Inc repository will be closing soon and our access are revoked. Not able to update this PR anymore.

**Pull request closed without merging**
