### PR TITLE
Breeze fixes

### PR DESCRIPTION
**Pull request by dreveman**

### CODE REVIEW

**Comment by dreveman** [comment]
@Yuhta I found these issues when trying to build breeze tests in ToT. The cmake change is just a result of my MR falling behind before it was merged and the other issues turned up when using ubuntu 24.04 instead of 22.04 to build.

**Comment by dreveman** [comment]
@Yuhta Added a commit that provides an autogen header for generated files as discussed

**Comment by Yuhta** [comment]
@dreveman Something to be fixed with formatter: https://github.com/facebookincubator/velox/actions/runs/11843156393/job/33008280565

**Comment by dreveman** [comment]
> @dreveman Something to be fixed with formatter: https://github.com/facebookincubator/velox/actions/runs/11843156393/job/33008280565

Yeah, I'll take care of that and also include a number of changes that are needed to build perf tests and tests for other platforms after everything was moved into the breeze subdir

**Comment by dreveman** [comment]
> > @dreveman Something to be fixed with formatter: https://github.com/facebookincubator/velox/actions/runs/11843156393/job/33008280565
> 
> Yeah, I'll take care of that and also include a number of changes that are needed to build perf tests and tests for other platforms after everything was moved into the breeze subdir

@Yuhta Should be fixed now and this PR should be ready to be merged

**Comment by dreveman** [comment]
@Yuhta let me know if I need to do anything to get that warning fixed?

**Pull request closed without merging**
