### PR TITLE
Add abstract reader interface

### PR DESCRIPTION
**Pull request by ienkovich**
This is preparation work for the Parquet reader. It moves some of the DWRF reader classes into dwio/common for shared usage and introduces abstract reader classes.

### CODE REVIEW

**Comment by ienkovich** [comment]
I've pushed additional fixes a few days ago, but this PR was not updated for some reason. Will try to rebase and push again.

**Comment by mbasmanova** [comment]
> @mbasmanova One more push didn't help. Have you ever met similar issues? Should I create a new PR and close this one?

I wonder if this is because the repo became public. Try making a new PR.

**Comment by ienkovich** [comment]
> I wonder if this is because the repo became public. Try making a new PR.

It appears my fork isn't even counted as a fork anymore. I can't even create a new PR from it. Will work on that.

**Comment by majetideepak** [comment]
> It appears my fork isn't even counted as a fork anymore. I can't even create a new PR from it. Will work on that.
This happened to us after Velox became public. We created a new fork again.

**Pull request closed without merging**
