### PR TITLE
Fix code style for CMakeLists.txt files

### LINKED ISSUE #10240: Make sure entire code base is properly formatted
While testing the new format I noticed that there are A LOT of files that are not correctly formatted but didn't show up because we only look at touched files.  You can repro this by running `./scripts/check.py format tree --fix velox` and check the changed files in git.

We should probably apply formatting across everything, merge that as a standalone commit and than create a [git blame revs ignore file](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt) to avoid that commit showing up everywhere when people git blame. @kgpai @pedroerp @mbasmanova ?

_Originally posted by @assignUser in https://github.com/facebookincubator/velox/issues/9948#issuecomment-2161795278_

### LINKED ISSUE #10550: CI Code Format checking failed
### Problem description

In many new PRs, the `Run Checks / Code Format (pull_request)` CI job fails due to formatting checks on `CMakeLists.txt` files.

In #9948, a new `.cmake-format.yaml` file was added to define the format of the `CMakeLists.txt` file, instead of using the default format of the `cmake-format` tool.

For a PR, currently only the modified files will be checked formatting, so for those PRs that modify the `CMakeLists.txt` file, this problem will occur.

Therefore, in order to solve this problem, all `CMakeLists.txt` files should be formatted uniformly once.

### System information

N/A

### CMake log

```bash
N/A
```

### PR DESCRIPTION
**Pull request by lingbin**
Fixes #10550
Fixes #10240 

It was fixed by using the following command (because only need to
format `CMakeLists.txt` files, so I modify check.py to skip the check
for python and cpp files)

```
python3 scripts/check.py format tree --fix ./velox
```

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]

**Comment by majetideepak** [comment]
@lingbin can you add in the description of how this PR was generated?

**Comment by lingbin** [comment]
> @lingbin can you add in the description of how this PR diff was generated?

@majetideepak  Added.

**Comment by Yuhta** [comment]
@lingbin There is some build error

**Comment by majetideepak** [comment]
@Yuhta Not related to this PR. I see this build failure on the PRs as well. Likely starting from https://github.com/facebookincubator/velox/pull/9948

**Comment by Yuhta** [comment]
Let's wait the build to be green then rebase then, this change is quite large and we need a clean signal

**Comment by assignUser** [comment]
Can you also install `clang-format` and run this again, I noticed there are a number of source files that are also not formatted correctly
```
velox/connectors/hive/tests/HiveDataSinkTest.cpp
velox/core/Metaprogramming.h
velox/dwio/common/DecoderUtil.h
velox/dwio/dwrf/test/E2EFilterTest.cpp
velox/dwio/parquet/writer/arrow/Schema.cpp
velox/exec/ExchangeSource.h
velox/exec/OutputBuffer.cpp
velox/exec/tests/LocalPartitionTest.cpp
velox/exec/tests/OutputBufferManagerTest.cpp
velox/exec/tests/PrintPlanWithStatsTest.cpp
velox/experimental/wave/common/tests/BlockTest.cpp
velox/expression/ComplexViewTypes.h
velox/expression/ConjunctExpr.cpp
velox/expression/SimpleFunctionAdapter.h
velox/expression/tests/CastExprTest.cpp
velox/expression/tests/ExprTest.cpp
velox/functions/CoverageUtil.cpp
velox/functions/prestosql/aggregates/tests/ApproxDistinctTest.cpp
velox/functions/prestosql/aggregates/tests/HistogramTest.cpp
velox/functions/prestosql/tests/utils/FunctionBaseTest.cpp
velox/functions/sparksql/tests/ComparisonsTest.cpp
velox/tpch/gen/dbgen/bm_utils.cpp
velox/tpch/gen/dbgen/build.cpp
velox/type/tests/FilterTest.cpp
velox/type/tests/TypeTest.cpp
velox/vector/tests/DecodedVectorTest.cpp
velox/vector/tests/VectorSaverTest.cpp
velox/vector/tests/VectorTest.cpp
velox/vector/tests/VectorTestUtils.h
velox/vector/tests/VectorToStringTest.cpp
```

**Comment by lingbin** [comment]
@assignUser  On my machine, unlike your list, only the following C++ files need to be formatted. 

```
 velox/common/caching/AsyncDataCache.cpp              | 2 +-
 velox/common/caching/AsyncDataCache.h                | 2 +-
 velox/common/caching/SsdCache.h                      | 2 +-
 velox/common/caching/SsdFile.h                       | 2 +-
 velox/common/file/tests/FaultyFile.h                 | 4 ++--
 velox/connectors/hive/storage_adapters/s3fs/S3Util.h | 2 +-
 velox/dwio/dwrf/test/ColumnWriterIndexTest.cpp       | 2 +-
 velox/exec/prefixsort/PrefixSortEncoder.h            | 2 +-
 velox/exec/tests/AggregateSpillBenchmarkBase.h       | 2 +-
 velox/type/parser/Scanner.h                          | 2 +-
 10 files changed, 11 insertions(+), 11 deletions(-)
```

Is it because we used a different `clang-format` version or `.clang-format` file?
I did not modify the `.clang-format` files in the root directory, and my `clang-format` version is 18.1.8 (installed using brew).

```
$ clang-format --version
clang-format version 18.1.8
```

**Comment by assignUser** [comment]
Ah hm, pretty sure it's the clang version. We should run this with the version in the check container so it matches ci.

**Comment by lingbin** [comment]
@assignUser  I am not familiar with how to get the "check container", could you tell me how to get it? I can download it locally to format it, thanks.  I got the following error.

```
#docker pull ghcr.io/facebookincubator/velox-dev:check
Error response from daemon: manifest for ghcr.io/facebookincubator/velox-dev:check not found
```

In addition, I have a small question: For C++ source files, it seems that in the new version of `clang-format`(on my machine), there are fewer files that need to be formatted. If I use the `clang-format` in the container(old version?) to format, will we need to modify it again after upgrading its version in the future?

**Comment by majetideepak** [comment]
CI clang-format version is
```
clang-format --version
Ubuntu clang-format version 18.1.3 (1ubuntu1)
```

**Comment by majetideepak** [comment]
@lingbin You should try downloading the check image on an x86_64 machine or specify --arch x86_64 on an arm arch.

**Comment by majetideepak** [comment]
I ran on the container check image and mostly saw CMakeList issues.

**Pull request closed without merging**
