### PR TITLE
Add crc32 Presto Functions

### PR DESCRIPTION
**Pull request by duanmeng**
[Add crc32 Presto Functions](https://prestodb.io/docs/current/functions/binary.html#crc32)

crc32(binary) → bigint

Computes the CRC-32 of binary. For general purpose hashing, use [xxhash64()](https://prestodb.io/docs/current/functions/binary.html#xxhash64), as it is much faster and produces a better quality hash.

### CODE REVIEW

**Comment by duanmeng** [comment]
```
velox_expression_fuzzer_test --logtostderr=1 --velox_fuzzer_enable_complex_types --only crc32 --duration_sec 60
velox_expression_fuzzer_test --logtostderr=1 --velox_fuzzer_enable_complex_types --enable_variadic_signatures --duration_sec 600
```
Succeed

**Review by xiaoxmeng — APPROVED** [review]
@Yuhta LGTM. Thanks!

**Comment by Yuhta** [comment]
@duanmeng No worry for now, it's a zlib version issue.  I will try to fix that first.

**Comment by Yuhta** [comment]
@duanmeng Can you use `folly::crc32` here instead of `crc32_z` from zlib?

**Comment by duanmeng** [comment]
> @duanmeng Can you use `folly::crc32` here instead of `crc32_z` from zlib?

@Yuhta Sure, done.

**Pull request closed without merging**
