### PR TITLE
Add to_ieee754_32 Presto Scalar Function

### PR DESCRIPTION
**Pull request by pdabre12**
Add to_ieee754_32 Presto function.

Fixes : https://github.com/facebookincubator/velox/issues/4425

### CODE REVIEW

**Review by aditi-pandit — APPROVED** [review]
Thanks !

**Comment by aditi-pandit** [comment]
@pdabre12 : Please can you paste the fuzzer output for this function https://facebookincubator.github.io/velox/develop/testing/fuzzer.html#how-to-run

**Review by aditi-pandit — CHANGES_REQUESTED** [review]
Please run the fuzzer and paste the output.

**Comment by pdabre12** [comment]
@aditi-pandit 

**Fuzzer output for to_ieee754_32 Presto function:**

I20230907 15:40:46.891588 1158555 ExpressionVerifier.cpp:63] ===================
I20230907 15:40:46.891608 1158555 ExpressionVerifier.cpp:74] All results match.
I20230907 15:40:46.891635 1158555 ExpressionFuzzer.cpp:1358] ==============================> Done with iteration 7713
I20230907 15:40:46.891666 1158555 ExpressionFuzzer.cpp:1093] ==============================> Top 1 by number of rows processed
I20230907 15:40:46.891683 1158555 ExpressionFuzzer.cpp:1095] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230907 15:40:46.891698 1158555 ExpressionFuzzer.cpp:1099] to_ieee754_32 7714 100.00% 124784
I20230907 15:40:46.891722 1158555 ExpressionFuzzer.cpp:1105] ==============================> Bottom 1 by number of rows processed
I20230907 15:40:46.891737 1158555 ExpressionFuzzer.cpp:1107] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230907 15:40:46.891753 1158555 ExpressionFuzzer.cpp:1112] to_ieee754_32 7714 100.00% 124784
I20230907 15:40:46.891769 1158555 ExpressionFuzzer.cpp:1125] ==============================> All stats sorted by number of times the function was chosen
I20230907 15:40:46.891783 1158555 ExpressionFuzzer.cpp:1127] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230907 15:40:46.891798 1158555 ExpressionFuzzer.cpp:1131] to_ieee754_32 7714 100.00% 124784
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.

**Review by aditi-pandit — APPROVED** [review]

**Comment by pdabre12** [comment]
@aditi-pandit Any updates on this PR merge?

**Pull request closed without merging**
