### PR TITLE
Fix formatting for AggregationNode documentation

### PR DESCRIPTION
**Pull request by ViggoC**

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
Thanks. Would you share a screenshot after the fix?

**Comment by mbasmanova** [comment]
Current formatting is clearly off: 

Screenshot 2023-10-31 at 7 15 50 AM

CC: @aditi-pandit

**Comment by ViggoC** [comment]
> Current formatting is clearly off:

> CC: @aditi-pandit
There is no problem with the preview in Github.
image

**Comment by mbasmanova** [comment]
@ViggoC Would you also generate docs locally and confirm the formatting. Please, attach a screenshot.

**Comment by mbasmanova** [comment]
@ViggoC Looks great. Thank you for fixing this issue.

**Comment by ViggoC** [comment]
@mbasmanova It was my pleasure.

**Review by aditi-pandit — COMMENTED** [review]
Thanks @ViggoC

**Pull request closed without merging**
