### PR TITLE
Remove unused DuckWrapper

### PR DESCRIPTION
**Pull request by majetideepak**

### CODE REVIEW

**Comment by kgpai** [comment]
@majetideepak Need to validate that this isnt used internally at Meta, I will import to test that out..

**Comment by majetideepak** [comment]
@kgpai thanks. We are planning to remove the DuckDB dependency. I am removing the bits incrementally.

**Review by pedroerp — APPROVED** [review]
Thanks @majetideepak!

**Comment by majetideepak** [comment]
@kgpai can you confirm that this code is used internally? If so, we can keep this code. Looks like it does not impact the removal of the DuckDB dependency.

**Pull request closed without merging**
