### PR TITLE
Update coverage maps for Spark/Presto.

### PR DESCRIPTION
**Pull request by myandpr**
### Summary
Update functions coverage maps in SparkSQL/Presto to reflect current additions

Until commit: b414dd4fa6734b1cc3c9c73fde5c08c7a799f162
1. Spark:
https://facebookincubator.github.io/velox/spark_functions.html
https://facebookincubator.github.io/velox/functions/spark/coverage.html

2. Presto:
https://facebookincubator.github.io/velox/functions.html
https://facebookincubator.github.io/velox/functions/presto/coverage.html

### Function commits lists:
1. Spark:
acos 57e1600eeab3a7849e9a368a2c464ceb074e6259
bin 148676b1d6cf1186e0cd0ab596442f0c9cc57a8a
hypot 6819495907ec5d917809eee9c26f009c1699c15a
left 9cbeb8b190b9cbcb3f5a7413e78ccaa2620aabf3
log1p f50e27cce57b41bb4c61aed32c75e4a2910ddcac
sinh 8b1d6ba4c4900813593707e55095d5cdeafdb507

2. Presto:
array_sort_desc 7e27cac1b6eca0449601c405c8dfc02f1db3b888

### CODE REVIEW

**Comment by myandpr** [comment]
@mbasmanova I have updated spark coverage maps as we talked about in https://github.com/facebookincubator/velox/pull/5511
you can review this PR when you have time.

**Review by mbasmanova — COMMENTED** [review]
@myandpr Would you update both Presto and Spark coverage maps?

**Comment by mbasmanova** [comment]
In this PR would be good. Thanks.

**Comment by myandpr** [comment]
> In this PR would be good. Thanks.

OK, I will add presto functions.

**Review by kgpai — APPROVED** [review]

**Comment by kgpai** [comment]
@myandpr Sorry did not notice that you intend to update the presto coverage maps also. Will look into it again after that.

**Comment by myandpr** [comment]
> @myandpr Sorry did not notice that you intend to update the presto coverage maps also. Will look into it again after that.

Updated.

@kgpai ,Please take a look, thanks.

**Pull request closed without merging**
