### PR TITLE
Fix static initialization order of default memory manager

### PR DESCRIPTION
**Pull request by zhztheplayer**
Velox GHA CI job `Run Benchmarks - Baseline` is now failing by this error:

```
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: The memory manager is not set
Retriable: False
Expression: instanceRef != nullptr
Function: getInstance
File: ../../velox/common/memory/Memory.cpp
Line: 129
Stack trace:
# 0  std::shared_ptr<facebook::velox::VeloxException::State const> facebook::velox::VeloxException::State::make<facebook::velox::VeloxException::make(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)::{lambda(auto:1&)#1}>(facebook::velox::VeloxException::Type, facebook::velox::VeloxException::make(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)::{lambda(auto:1&)#1})
# 1  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
# 2  facebook::velox::VeloxRuntimeError::VeloxRuntimeError(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, std::basic_string_view<char, std::char_traits<char> >)
# 3  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, char const*>(facebook::velox::detail::VeloxCheckFailArgs const&, char const*)
# 4  facebook::velox::memory::MemoryManager::getInstance()
# 5  __static_initialization_and_destruction_0(int, int)
# 6  _GLOBAL__sub_I__ZN5fLI6417FLAGS_fuzzer_seedE
# 7  __libc_csu_init
# 8  __libc_start_main
# 9  _start
```

The error should be fixed by this patch.

Follow up to https://github.com/facebookincubator/velox/pull/8079
Related to https://github.com/facebookincubator/velox/pull/7168

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@xiaoxmeng

The PR should fix the CI error but seems to be like CI is checking out main branch code but not the PR head/merge so still failing.

**Comment by zhztheplayer** [comment]
cc @mbasmanova

**Comment by mbasmanova** [comment]
@xiaoxmeng Meng, would you help review this change?

**Review by xiaoxmeng — APPROVED** [review]
@zhztheplayer LGTM. Thanks!

**Review by tanjialiang — APPROVED** [review]

**Pull request closed without merging**
