### PR TITLE
Back out "Handle allocations that exceed PageRun limits"

### PR DESCRIPTION
**Pull request by xiaoxmeng**
Summary:
Original commit changeset: 8a568db14e51

Original Phabricator Diff: D51167059

Differential Revision: D51919841

### CODE REVIEW

**Comment by mbasmanova** [comment]
@majetideepak Hi Deepak, we had to revert this diff because it caused a slow memory leak in one of the Velox applications running at Meta.

**Comment by mbasmanova** [comment]
@majetideepak We didn't get a chance to investigate and figure out what exactly is the problem, but without that diff the leak stopped happening.

**Comment by majetideepak** [comment]
@mbasmanova Thank you for the update!

**Comment by xiaoxmeng** [comment]
@majetideepak we run into memory leak in some Meta internal system using MallocAllocator. The memory free logic based on the contiguous memory addresses has problem. The forward fix needs to have map with address and length to handle the memory allocations from jemalloc

**Pull request closed without merging**
