### PR TITLE
[BUILD] Support loading dependencies from non-system directories

### PR DESCRIPTION
**Pull request by jackylee-ch**
Recently, we are trying to compile velox with components installed in the user directory by non-root users, which causes failed to find errors for these components. So this PR tries to resolve this problem and support to find components from other directories.

### CODE REVIEW

**Comment by pedroerp** [comment]
@kgpai @assignUser could you help review this PR?

**Comment by assignUser** [comment]
I don't think this PR is necessary, cmake provides different solutions to influence the `find_package` search procedure without having to resort to vendoring additional find-modules.

Each of the libraries you added modules for usually installs a config file. If you installed to an unusual place cmake does not look at by default you can use [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html)  to add those locations to the search path and it should work as if those were installed normally to `/usr/include` or where ever.  Similar purpose but more package specific [`<package>_ROOT`](https://cmake.org/cmake/help/latest/envvar/PackageName_ROOT.html#envvar:%3CPackageName%3E_ROOT).

@jackylee-ch could you give those alternatives a try and let us know if they work for you?

**Comment by jackylee-ch** [comment]
> @jackylee-ch could you give those alternatives a try and let us know if they work for you?

@assignUser Thank you for your attension and suggestion. Using `CMAKE_PREFIX_PATH` can indeed solve the package not found problem, but it cannot solve all the problems. We still need to call i`nclude_directories` to add dependencies include dirs or add them to `CMAKE_REQUIRED_INCLUDES`, otherwise some header files will not be found. Or could we add some checks so that we can know which header files are missing before compiling?

**Comment by assignUser** [comment]
@jackylee-ch What exactly is your setup and how are you installing the libraries? If cmake find the packages via config or find module than there should not be a need to manually add the include directories. 
(Additionally the use of non target based `include_directories()` is deprecated and we hope to refactor our cmake in that regard soon :D)

**Comment by jackylee-ch** [comment]
> @jackylee-ch What exactly is your setup and how are you installing the libraries? If cmake find the packages via config or find module than there should not be a need to manually add the include directories.

In our scenario, users will use non-root users, such as work, to install dependent packages into their own directories, such as /home/work/libraries/{library} or ${WORKDIR}/{library}.

> (Additionally the use of non target based include_directories() is deprecated and we hope to refactor our cmake in that regard soon :D)

It is okey to me about not using `include_directories`. I just wonder whether we can add some `find_path` to check which dependencies are missing before make, so that users can add them to `CMAKE_REQUIRED_INCLUDES` or find their way to solve this missing dependencies. The modification of this PR can be discarded, this is just an additional small suggestion.

**Comment by assignUser** [comment]
If they installed the libraries by building from source using cmake they should install find modules or configs. Even if they have no configs or modules the build in modules there are envvars that can be set to help cmake find the libraries (please refer to the docs linked above). Worst case you can add custom Find modules as you did in this pr and point the cmake module path to it.

Regarding the include directories you could add `-DCMAKE_CXX_FLAGS=-I\ /path/to/include ` to the cmake invocation to add your custom path (I have not tested this but it should work).

**Comment by jackylee-ch** [comment]
> Regarding the include directories you could add `-DCMAKE_CXX_FLAGS=-I\ /path/to/include ` to the cmake invocation to add your custom path (I have not tested this but it should work).

Yes, this can work too, I have already tested it before.

**Comment by assignUser** [comment]
As stated above cmake already provides multiple ways to specify non-standard paths for dependencies.

**Pull request closed without merging**
