### PR TITLE
re-organize presto function registration

### PR DESCRIPTION
**Pull request by laithsakka**
- Split functions to semantic type-based category:
Deprecate registerVectorFunctions() and registerSimpleFunctions()
and instead introduce registerStringFunctions(), registerMapFunctions()...etc.

- This split also reduces the compile time by distributing the instantiations of the simple 
functions across multiple compilation units.

### CODE REVIEW

**Comment by kgpai** [comment]
Thanks @laithsakka this is great. Do you have a rough idea of how much time this saves in compiling ?

**Comment by laithsakka** [comment]
rebase on master

**Comment by laithsakka** [comment]
rebase on master

**Comment by laithsakka** [comment]
> Thanks @laithsakka this is great. Do you have a rough idea of how much time this saves in compiling ?

I did not collect numbers, i will try to collect and add some.
aside from the compilation time also, is the re-compile freq. it the prev model.
if any function changes all functions are recompiled since they are all in the same compilation unit.

**Pull request closed without merging**
