### PR TITLE
Keep DuckDB re2 headers private

### PR DESCRIPTION
**Pull request by majetideepak**
DuckDB source when bundled includes a copy of re2 as a third-party dependency. However, it defines
the re2 headers as public which seem to conflict with the system re2 headers.

The base build needs the manual install_duckdb since it is being built off master.

Developers must delete the `_deps/duckdb_*` folders in their build folder for the patches to apply cleanly.

Resolves https://github.com/facebookincubator/velox/issues/10154

### CODE REVIEW

**Comment by majetideepak** [comment]
@czentgr Can you verify this change locally and confirm the MacOS build succeeds?

**Review by assignUser — APPROVED** [review]
Thanks! Looks good as a fix for now. It might cause issues with installing down the line but for that we will likely need to change a bunch of stuff so we can ignore it for now.

**Review by zacw7 — APPROVED** [review]
Thanks for the fix!

**Comment by czentgr** [comment]
@majetideepak it works on mac as well. Fixes the issue.

**Pull request closed without merging**
