### PR TITLE
Extract fuzzer into expression/fuzzer directory

### PR DESCRIPTION
**Pull request by rui-mo**
Extract fuzzer from expression/tests into expression/fuzzer directory.

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
@rui-mo This is nice. Thank you for refactoring, Rui.

**Comment by kagamiori** [comment]
Hi @rui-mo, could you rebase onto the latest main? There is a merge conflict in ExpressionFuzzerVerifier.h. Thanks!

**Comment by rui-mo** [comment]
@kagamiori This PR was rebased. Thanks for the reminder.

**Comment by kagamiori** [comment]
Hi @rui-mo, sorry that there is a new merge conflict again while I ran for some tests. Could you rebase again? I'll try to land as soon as possible before the next merge conflict.

**Comment by rui-mo** [comment]
@kagamiori This PR was rebased. Thanks for your help.

**Pull request closed without merging**
