### PR TITLE
[Substrait to Velox] Support list and string literal

### PR DESCRIPTION
**Pull request by rui-mo**
This PR supports the conversion from Substrait list and string literal to Velox constant expression.

### CODE REVIEW

**Comment by mbasmanova** [comment]
@rui-mo Rui, I see the PR is closed now. Was it intentional or did you close by accident?

**Comment by rui-mo** [comment]
> @rui-mo Rui, I see the PR is closed now. Was it intentional or did you close by accident?

Sorry it is closed intentiaonlly to change the branch raising PR from. There is another PR https://github.com/facebookincubator/velox/pull/2450 for this change.

**Comment by mbasmanova** [comment]
> it is closed intentiaonlly to change the branch raising PR from

When you want to update an existing PR from a different branch, you can simply rename local branch to the branch associated with the PR. There is no need to create new PR.

**Comment by rui-mo** [comment]
> When you want to update an existing PR from a different branch, you can simply rename local branch to the branch associated with the PR. There is no need to create new PR.

Got it! Will do that when needed next time, thank you.

**Pull request closed without merging**
