### PR TITLE
Add script to modify Thrift include guard variables 

### PR DESCRIPTION
**Pull request by jwyles-ahana**
This adds a script which will modify the include guard variables for the Thrift includes included by DuckDB. This is necessary because the new parquet reader also includes Thrift headers and without renaming there are collisions.

### CODE REVIEW

**Comment by yingsu00** [comment]
@jwyles-ahana Can you please squash the two commits into one and update the commit message? The commit message needs to show what the commit is about. Right now you have the PR message but I couldn't see the commit message.

**Comment by jwyles-ahana** [comment]
@yingsu00 I have squashed the two commits into one and updated the commit message.

**Comment by yingsu00** [comment]
This PR is the first PR to resolve https://github.com/facebookincubator/velox/issues/1734

**Comment by yingsu00** [comment]
@majetideepak The S3 tests kept failing, will you be able to help take a look? I saw the following error messages
```
126: E0603 21:40:03.008405  7145 Exceptions.h:68] Line: ../../velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp:82, Function:initialize, Expression: Failed to get metadata for S3 object due to: 'Network connection'. Path:'s3://dummy/foo.txt', SDK Error Type:99, HTTP Status Code:-1, S3 Service:'Unknown', Message:'curlCode: 7, Couldn't connect to server', Source: RUNTIME, ErrorCode: INVALID_STATE
126: [       OK ] S3FileSystemTest.noBackendServer (27561 ms)
126: [----------] 9 tests from S3FileSystemTest (47754 ms total)
126: 
126: [----------] Global test environment tear-down
126: [==========] 12 tests from 2 test suites ran. (47757 ms total)
126: [  PASSED  ] 9 tests.
126: [  FAILED  ] 3 tests, listed below:
126: [  FAILED  ] S3FileSystemTest.writeAndRead
126: [  FAILED  ] S3FileSystemTest.viaRegistry
126: [  FAILED  ] S3FileSystemTest.fileHandle
126: 
126:  3 FAILED TESTS
```

**Comment by yingsu00** [comment]
@jwyles-ahana you don't have to create a separate commit just to retry CircleCI. Would you please just do something in your original commit and try a few more times?

**Comment by majetideepak** [comment]
The S3 test failures are fixed on the main branch. Please rebase with main.

**Comment by yingsu00** [comment]
@jwyles-ahana Will you please squash the commits and make the commit title shorter? Thank you!

**Comment by yingsu00** [comment]
@jwyles-ahana Could you resolve the conflict please?

**Pull request closed without merging**
