### PR TITLE
fix: Add support for sm5x CUDA archs to breeze

### PR DESCRIPTION
**Pull request by dreveman**
Code was limited to sm60 and above previously. This makes it compile for sm50 too, which is the default for nvcc.

Also adds a ubsan build type and fixes some issues that caused building without tracing enabled to fail.

### CODE REVIEW

**Comment by dreveman** [comment]
@Yuhta some build fixes

**Comment by dreveman** [comment]
@Yuhta Please review this when you have a chance, thanks!

**Comment by dreveman** [comment]
> Not urgent, but would be nice if you can run some of the tests in https://github.com/facebookincubator/velox/blob/main/.github/workflows/linux-build-base.yml

@Yuhta Yes, happy to add that. Should we limit it to OpenMP or can we also run CUDA tests? And how about also running some tests on MacOS?

**Comment by Yuhta** [comment]
@dreveman If we can run GPU tests we can also enable CUDA tests, otherwise let's just enable OpenMP for now.
@assignUser Can we run GPU tests on GitHub action now?

**Comment by assignUser** [comment]
> Can we run GPU tests on GitHub action now?

No that stalled out a while ago #9527

**Comment by Yuhta** [comment]
@dreveman If your team has bandwidth to help setting up GPU on GitHub action it would be nice.  We are only running some very minimal sanity check for breeze/CUDA inside Wave.

**Pull request closed without merging**
