### PR TITLE
Remove EXACT protobuf dependency on 3.21.4

### PR DESCRIPTION
**Pull request by karteekmurthys**
Fixes: https://github.com/facebookincubator/velox/issues/10112

### CODE REVIEW

**Review by assignUser — CHANGES_REQUESTED** [review]
This does not actually fix the issue, it just circumvents building protobuf from scratch. As I mentioned in the issue I am not sure if we still need the exact pin, so the change might be ok in general but I can't judge that.

**Comment by karteekmurthys** [comment]
> This does not actually fix the issue, it just circumvents building protobuf from scratch. As I mentioned in the issue I am not sure if we still need the exact pin, so the change might be ok in general but I can't judge that.

@kgpai let me know if this change to mark EXACT required or can we remove it.

```
-- Could NOT find Protobuf: Found unsuitable version "3.21.12", but required is exact version "3.21.4" (found /opt/homebrew/lib/libprotobuf.dylib)
-- Building Protobuf from source
-- 
-- 3.21.4.0
-- Using BUNDLED Protobuf
-- Setting simdjson source to AUTO
```

**Comment by majetideepak** [comment]
We still need 3.21 as 3.22 onwards has breaking changes afaik.
Will using `resolve_dependency(Protobuf 3.21 EXACT)` help?

**Comment by assignUser** [comment]
As we bumped the cmake version we can now use a range:
>A version range with the format versionMin...[<]versionMax where versionMin and versionMax have the same format and constraints on components being integers as the single version. By default, both end points are included. By specifying <, the upper end point will be excluded. Version ranges are only supported with CMake 3.19 or later.

So `resolve_dependency(Protobuf 3...<4) should work as v22 is actually [4.22](https://github.com/protocolbuffers/protobuf/commit/a847a8dc4ba1d99e7ba917146c84438b4de7d085#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR102)

**Comment by majetideepak** [comment]
> So resolve_dependency(Protobuf 3...<4) should work as v22 is actually

The quick fix for now is to use this. I agree that we should confirm support for v22+. I will try that after we move to Centos9.

**Comment by majetideepak** [comment]
I also see a security issue against 3.21.4. We should update the minimum version https://github.com/facebookincubator/velox/issues/3136.

**Comment by assignUser** [comment]
https://github.com/facebookincubator/velox/issues/10133 I'll open a PR with the version range and minversion bump

**Comment by assignUser** [comment]
@karteekmurthys this should fix your issue, could you confirm? https://github.com/facebookincubator/velox/pull/10134

**Pull request closed without merging**
