### PR TITLE
Add support for S3 FileSystem compatible schemes 's3n'

### PR DESCRIPTION
**Pull request by puchengy**
S3 compatible scheme "s3a" and "oss" was added by https://github.com/facebookincubator/velox/pull/2410. However, there are currently datasets still using the old scheme "s3n". This PR adds support for that.

As "s3n" is deprecated in latest Hadoop. Thus we are adding comment indicating this is just a change for backward compatibility purpose.

### CODE REVIEW

**Comment by puchengy** [comment]
@Mionsz @majetideepak @mbasmanova Hi, can you take a look? Thanks!

**Review by Mionsz — APPROVED** [review]

**Comment by puchengy** [comment]
@Mionsz thanks for the review, do you know who will be able to merge this?

**Comment by puchengy** [comment]
@Mionsz @majetideepak @mbasmanova Hi, do you know how can this change be merged? Thanks!

**Comment by mbasmanova** [comment]
@puchengy I can merge this PR.

**Pull request closed without merging**
