### PR TITLE
Fix VeloxRuntimeError when reading parquet file with only meta data

### PR DESCRIPTION
**Pull request by zhixingheyi-tian**
Issue is exposed from https://github.com/oap-project/gluten/issues/770

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
cc @mbasmanova

**Comment by zhixingheyi-tian** [comment]
Hi  @Yuhta @kgpai

**Comment by zhixingheyi-tian** [comment]
Hi @mbasmanova @Yuhta @kgpai y,
Would you please give a review.

**Comment by Yuhta** [comment]
@zhixingheyi-tian Thanks for the fix.  Can you add a unit test for this?

**Comment by majetideepak** [comment]
+1. Resolves https://github.com/facebookincubator/velox/issues/2871
As mentioned, a test will be nice to add.

**Comment by zhixingheyi-tian** [comment]
hi @Yuhta @majetideepak ,
have added UT,  thanks!

**Pull request closed without merging**
