### PR TITLE
Optimize SortBuffer memory allocation by allocating row bytes at once

### PR DESCRIPTION
**Pull request by jinchengchenghh**

### CODE REVIEW

**Comment by jinchengchenghh** [comment]
After this change, some dataset can pass test, but SortBufferTest.batchOutput failed by coredump:
```
#0  0x0000562d7c0bc368 in facebook::velox::HashStringAllocator::Header::size (this=0x3239335b202c3632)
    at /mnt/DP_disk1/code/velox/./velox/common/memory/HashStringAllocator.h:110
110           return data_ & kSizeMask;
[Current thread is 1 (Thread 0x7f786a06dc00 (LWP 3546508))]
(gdb) bt
#0  0x0000562d7c0bc368 in facebook::velox::HashStringAllocator::Header::size (this=0x3239335b202c3632)
    at /mnt/DP_disk1/code/velox/./velox/common/memory/HashStringAllocator.h:110
#1  0x0000562d7c0b6bbd in facebook::velox::exec::RowContainer::extractString (value=..., values=0x562d8feeb850, index=432)
    at /mnt/DP_disk1/code/velox/velox/exec/RowContainer.cpp:762
#2  0x0000562d7a99b37c in facebook::velox::exec::RowContainer::extractValuesWithNulls<false, facebook::velox::StringView> (rows=0x562d9008dd20,
    rowNumbers=..., numRows=2000, offset=27, nullByte=12, nullMask=32 ' ', resultOffset=0, result=0x562d8feeb850)
    at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:947
#3  0x0000562d7a98ff97 in facebook::velox::exec::RowContainer::extractColumnTypedInternal<false, (facebook::velox::TypeKind)7> (rows=0x562d9008dd20,
    rowNumbers=..., numRows=2000, column=..., resultOffset=0, result=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...})
    at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:854
#4  0x0000562d7a98b36d in facebook::velox::exec::RowContainer::extractColumnTyped<(facebook::velox::TypeKind)7> (rows=0x562d9008dd20, rowNumbers=...,
    numRows=2000, column=..., resultOffset=0, result=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...})
    at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:823
#5  0x0000562d7a980880 in facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const (__closure=0x7ffeb45d9420)
    at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:1424
#6  0x0000562d7a9803f6 in facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&)::{lambda()#1}::operator()() const (__closure=0x7ffeb45d94a0) at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:1424
#7  0x0000562d7a980c21 in facebook::velox::exec::RowContainer::extractColumn (rows=0x562d9008dd20, numRows=2000, column=..., resultOffset=0,
    result=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...}) at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:1424
#8  0x0000562d7a98010b in facebook::velox::exec::RowContainer::extractColumn (rows=0x562d9008dd20, numRows=2000, col=...,
    result=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...}) at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:358
#9  0x0000562d7a980159 in facebook::velox::exec::RowContainer::extractColumn (this=0x562d8fff5cc0, rows=0x562d9008dd20, numRows=2000, columnIndex=5,
    result=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...}) at /mnt/DP_disk1/code/velox/./velox/exec/RowContainer.h:390
#10 0x0000562d7c0cb3aa in facebook::velox::exec::SortBuffer::getOutputWithoutSpill (this=0x562d8fee7fc0)
    at /mnt/DP_disk1/code/velox/velox/exec/SortBuffer.cpp:341
#11 0x0000562d7c0c9e66 in facebook::velox::exec::SortBuffer::getOutput (this=0x562d8fee7fc0, maxOutputRows=2000)
    at /mnt/DP_disk1/code/velox/velox/exec/SortBuffer.cpp:166
#12 0x0000562d7ac6c58c in facebook::velox::functions::test::SortBufferTest_batchOutput_Test::TestBody (th
```
The string value cannot correctly read, don't know why this happens.

**Comment by jinchengchenghh** [comment]
I use valgrind to debug:
```
==3857129== Use of uninitialised value of size 8
==3857129==    at 0xBC2860A: facebook::velox::HashStringAllocator::Header::size() const (HashStringAllocator.h:110)
==3857129==    by 0xBC22E88: facebook::velox::exec::RowContainer::extractString(facebook::velox::StringView, facebook::velox::FlatVector<facebook::velox::StringView>*, int) (RowContainer.cpp:757)
==3857129==    by 0xA50737B: void facebook::velox::exec::RowContainer::extractValuesWithNulls<false, facebook::velox::StringView>(char const* const*, folly::Range<int const*>, int, int, int, unsigned char, int, facebook::velox::FlatVector<facebook::velox::StringView>*) (RowContainer.h:951)
==3857129==    by 0xA4FBF96: void facebook::velox::exec::RowContainer::extractColumnTypedInternal<false, (facebook::velox::TypeKind)7>(char const* const*, folly::Range<int const*>, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&) (RowContainer.h:858)
==3857129==    by 0xA4F736C: void facebook::velox::exec::RowContainer::extractColumnTyped<(facebook::velox::TypeKind)7>(char const* const*, folly::Range<int const*>, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&) (RowContainer.h:827)
==3857129==    by 0xA4EC87F: facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const (in /mnt/DP_disk1/code/velox/build/velox/exec/tests/velox_exec_test)
==3857129==    by 0xA4EC3F5: facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&)::{lambda()#1}::operator()() const (RowContainer.h:1428)
==3857129==    by 0xA4ECC20: facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, facebook::velox::exec::RowColumn, int, std::shared_ptr<facebook::velox::BaseVector> const&) (RowContainer.h:1428)
==3857129==    by 0xA4EC10A: facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, facebook::velox::exec::RowColumn, std::shared_ptr<facebook::velox::BaseVector> const&) (RowContainer.h:362)
==3857129==    by 0xA4EC158: facebook::velox::exec::RowContainer::extractColumn(char const* const*, int, int, std::shared_ptr<facebook::velox::BaseVector> const&) (RowContainer.h:394)
==3857129==    by 0xBC3766D: facebook::velox::exec::SortBuffer::getOutputWithoutSpill() (SortBuffer.cpp:332)
==3857129==    by 0xBC36129: facebook::velox::exec::SortBuffer::getOutput(unsigned int) (SortBuffer.cpp:157)
==3857129==  Uninitialised value was created by a heap allocation
==3857129==    at 0x1E80D7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3857129==    by 0x10539D26: facebook::velox::memory::MallocAllocator::allocateNonContiguousWithoutRetry(facebook::velox::memory::MemoryAllocator::SizeMix const&, facebook::velox::memory::Allocation&)::{lambda()#1}::operator()() const (MallocAllocator.cpp:81)
==3857129==    by 0x1053D15F: void facebook::velox::memory::Stats::recordAllocate<facebook::velox::memory::MallocAllocator::allocateNonContiguousWithoutRetry(facebook::velox::memory::MemoryAllocator::SizeMix const&, facebook::velox::memory::Allocation&)::{lambda()#1}>(long, int, f




==3857129== 1576 errors in context 22 of 38:
==3857129== Conditional jump or move depends on uninitialised value(s)
==3857129==    at 0xA763A7A: int facebook::velox::exec::RowContainer::listRows<(facebook::velox::exec::RowContainer::ProbeType)0>(facebook::velox::exec::RowContainerIterator*, int, unsigned long, char**) (RowContainer.h:515)
==3857129==    by 0xA75BFE5: facebook::velox::exec::RowContainer::listRows(facebook::velox::exec::RowContainerIterator*, int, char**) (RowContainer.h:560)
==3857129==    by 0xBC35F98: facebook::velox::exec::SortBuffer::noMoreInput() (SortBuffer.cpp:118)
==3857129==    by 0xA7D883A: facebook::velox::functions::test::SortBufferTest_batchOutput_Test::TestBody() (SortBufferTest.cpp:327)
==3857129==    by 0x10764AE1: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2621)
==3857129==    by 0x1075EC0E: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2657)
==3857129==    by 0x1073D051: testing::Test::Run() (gtest.cc:2696)
==3857129==    by 0x1073DB20: testing::TestInfo::Run() (gtest.cc:2845)
==3857129==    by 0x1073E471: testing::TestSuite::Run() (gtest.cc:3004)
==3857129==    by 0x1074E391: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5890)
==3857129==    by 0x10765A2A: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2621)
==3857129==    by 0x1075FC7C: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2657)
==3857129==  Uninitialised value was created by a heap allocation
==3857129==    at 0x1E80D7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3857129==    by 0x10539D26: facebook::velox::memory::MallocAllocator::allocateNonContiguousWithoutRetry(facebook::velox::memory::MemoryAllocator::SizeMix const&, facebook::velox::memory::Allocation&)::{lambda()#1}::operator()() const (MallocAllocator.cpp:81)

```
image

```
        if (bits::isBitSet(rows[count - 1], freeFlagOffset_)) {
          std::cout << "free flag offset " << count - 1 << "offset "
                    << freeFlagOffset_ << std::endl;
          if (count - 1 >= 4000) {
            std::cout << "access illegal memory " << count - 1 << "offset "
                      << freeFlagOffset_ << std::endl;
          }
          --count;
          continue;
        }
```
Print result:
```
numInputRows 0
numInputRows 2000
list rows 4000
numInputRows 0
numInputRows 2000
numInputRows 0
numInputRows 2000
list rows 4000
free flag offset 2001offset 102
free flag offset 2002offset 102
free flag offset 2004offset 102
free flag offset 2004offset 102
free flag offset 2004offset 102
free flag offset 2010offset 102
free flag offset 2011offset 102
free flag offset 2012offset 102
```
I suppose it should not hit `freeFlag`, so the memory may be destroyed in freeFlagOffset_ bit

**Comment by jaystarshot** [comment]
@jinchengchenghh  Did you use valgrind with mmapallocator on?

**Comment by jinchengchenghh** [comment]
I use the default valgrind argument, not sure mmapallocator status

**Pull request closed without merging**
