### PR TITLE
Back out "Add FlatVector support for Decimal Type"

### PR DESCRIPTION
**Pull request by tgalkovskyi**
Summary:
Original commit changeset: 515b13782ed0

Original Phabricator Diff: D36557565 (https://github.com/facebookincubator/velox/commit/a35b9830f69a92c633d365b58538a4381b0f472d)

Reviewed By: kapilsh

Differential Revision: D36788068

### CODE REVIEW

**Comment by kgpai** [comment]
cc @karteekmurthys

**Comment by kgpai** [comment]
@karteekmurthys Apparently this commit broke torch arrow internally. We are still figuring out the root cause and temporarily have to back out the change. We will recommit the change along with the fix after we figure it out. I will keep you in the loop .

**Comment by majetideepak** [comment]
I find it very odd to revert this PR. You could pin torcharrow to an older velox version until the issue is fixed.
CC: @mbasmanova @pedroerp

**Comment by kgpai** [comment]
@majetideepak  Apologies for late reply Deepak 
1 - Unfortunately we cant pin this to an older version right now . (
2 - I am working with TA team to get better visibility into their systems so that we dont have these problems after things land, so hopefully it shouldnt happen in future. 
3. FYI, The problem is caused  by an intermittent segfault in certain machines (we arent sure what the exact root cause is yet, but I am working on it ).  
4. I will post all communication regarding this in this Issue going forward : https://github.com/facebookincubator/velox/issues/1753 . 
5. Again as posted I hope to have this resolved at the very latest by eow. 

Thanks.

**Comment by majetideepak** [comment]
@kgpai thanks for the clarification.

**Pull request closed without merging**
