### PR TITLE
Fix QueryAssertions and variant::toJson() to support logical types

### PR DESCRIPTION
**Pull request by Krishna-Prasad-P-V**
QueryAssertions uses variants to compare results and uses the physical type for the output
error message generation.
This PR enables using the expected result TypePtr for the output error generation.
Resolves: https://github.com/facebookincubator/velox/issues/5338

### CODE REVIEW

**Comment by majetideepak** [comment]
@kgpai, @pedroerp, For some reason @Krishna-Prasad-P-V PRs have an issue with CI jobs. The MacOS and Ubuntu CI jobs do not run on any PR. Do you know the reason? Thanks!

**Comment by kgpai** [comment]
@majetideepak I did not see him in the contributor list and added him. Can you make a token push and see if it helps ?

**Comment by Krishna-Prasad-P-V** [comment]
Completed a rebase with main and pushed changes. The CI pipelines are still not running.

**Comment by kgpai** [comment]
I suspect it might be becuase the Facebook CLA Check seems stuck for some reason. Investigating..

**Comment by kgpai** [comment]
Doesnt look like the CLA Check since it succeeded in some other PRs but the CI is still stuck. Again investigating.

**Comment by kgpai** [comment]
I am reaching out to get some help from folks internally. Will keep this PR upto date with what I know.

**Comment by kgpai** [comment]
This is what CCI got back to me with : 
```
If a user is following their own fork of a project instead of the original project, CircleCI builds may not be triggered for open source repositories. This behavior is due to the way CircleCI handles forked repositories and user permissions. Here are some reasons why this could be happening:
 
Forked Repository Ownership: When a user forks a repository, the forked repository becomes their own personal copy. By default, CircleCI is configured to trigger builds for the source project but not for forked repositories. Therefore, if the user has not set up CircleCI integration specifically for their forked repository, the builds will not be triggered.
 
Ownership vs. Following: When a user follows a repository on CircleCI, it means they are following the original project, not their forked copy. If the user is only following their forked repository, CircleCI will not trigger builds for that repository.
 
[To resolve this issue, the user should follow the steps below](https://circleci.com/docs/oss/):
 
Unfollow Forked Repository: The user should unfollow their forked repository on CircleCI.
 
Follow Original Project: Instead of following their forked repository, the user should follow the original project repository on CircleCI. This will ensure that CircleCI triggers builds for the open source repository.
 
By unfollowing the forked repository and following the original project, the user should be able to trigger CircleCI builds for their pull requests in the open source repository correctly.
``` 

Which repo are you following @Krishna-Prasad-P-V ?

**Comment by Krishna-Prasad-P-V** [comment]
> This is what CCI got back to me with :
> 
> ```
> If a user is following their own fork of a project instead of the original project, CircleCI builds may not be triggered for open source repositories. This behavior is due to the way CircleCI handles forked repositories and user permissions. Here are some reasons why this could be happening:
>  
> Forked Repository Ownership: When a user forks a repository, the forked repository becomes their own personal copy. By default, CircleCI is configured to trigger builds for the source project but not for forked repositories. Therefore, if the user has not set up CircleCI integration specifically for their forked repository, the builds will not be triggered.
>  
> Ownership vs. Following: When a user follows a repository on CircleCI, it means they are following the original project, not their forked copy. If the user is only following their forked repository, CircleCI will not trigger builds for that repository.
>  
> [To resolve this issue, the user should follow the steps below](https://circleci.com/docs/oss/):
>  
> Unfollow Forked Repository: The user should unfollow their forked repository on CircleCI.
>  
> Follow Original Project: Instead of following their forked repository, the user should follow the original project repository on CircleCI. This will ensure that CircleCI triggers builds for the open source repository.
>  
> By unfollowing the forked repository and following the original project, the user should be able to trigger CircleCI builds for their pull requests in the open source repository correctly.
> ```
> 
> Which repo are you following @Krishna-Prasad-P-V ?

I did fork from https://github.com/facebookincubator/velox/tree/main. Not anything much. Actually, I even has delivered a PR earlier. Should I delete my fork again and create another one?

**Comment by kgpai** [comment]
Deleting fork might invalidate this PR (not sure I have never tried something like that). I am going to reach out for further details from CCI.

**Comment by Krishna-Prasad-P-V** [comment]
> Deleting fork might invalidate this PR (not sure I have never tried something like that). I am going to reach out for further details from CCI.

Yes. All the PRs will be invalid then or else I can use Github Support to detach the fork.

**Comment by kgpai** [comment]
@Krishna-Prasad-P-V Lets not delete unless we exhaust all other options.

**Comment by Krishna-Prasad-P-V** [comment]
> @Krishna-Prasad-P-V Lets not delete unless we exhaust all other options.

@kgpai - I have fixed it. In my app CircleCI, with my Github account projects - i unfollowed velox project and then use facebookincubator account. Now the ci pipelines are triggered. Thanks a lot for this. Not sure how it got followed by its own.
Screenshot 2023-09-02 at 1 06 00 AM

**Comment by Krishna-Prasad-P-V** [comment]
@kgpai @majetideepak - I am closing this PR( https://github.com/facebookincubator/velox/pull/6215) as we already the existing PR with CI pipelines now running. Again, thanks for all help on this issue.

**Pull request closed without merging**
