### PR TITLE
Componetize SelectiveColumnReader

### PR DESCRIPTION
**Pull request by oerling**
Split SelectiveColumnReader into format-specific readers and extract
generic logic for value processing,filtering and the column visitor
pattern.

The objective is reusing common pieces in selective readers for Parquet and Alpha.

The next step is adapting the Visitor signatures so that a single
Visitor can handle alternating direct and dictionary encodings in the
same stripe.

### CODE REVIEW

**Comment by majetideepak** [comment]
@oerling Isn't this a duplicate of https://github.com/facebookincubator/velox/pull/1085 that is already merged?

**Comment by oerling** [comment]
Must be.

**Comment by pedroerp** [comment]
@oerling @majetideepak if this is a duplicate, can we safely close it? This is showing up on the top of our stale PR dashboard.

**Comment by pedroerp** [comment]
Closing it for now as it seems like it was merged in #1085

**Pull request closed without merging**
