### PR TITLE
Remove DuckDB Parquet Reader implementation

### PR DESCRIPTION
**Pull request by majetideepak**
Remove DuckDB Parquet Reader
Merge DuckDB tests with Native Parquet Reader tests.

Co-authored-by: Ivan Sadikov <ivan@ahana.io>

### CODE REVIEW

**Comment by majetideepak** [comment]
@karteekmurthys, @pramodsatya can you verify that the duckdb tests `ParquetReaderTest.cpp`, `ParquetTableScanTest.cpp` have been correctly ported to the native reader tests?
The test names have been renamed.

**Review by pramodsatya — APPROVED** [review]
LGTM @majetideepak, thank you!

**Comment by majetideepak** [comment]
ParquetTpchTestBase uses DuckDB to write Parquet. We need to remove this use as well. I will try using the Velox Parquet Writer.

**Review by karteekmurthys — APPROVED** [review]

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Review by aditi-pandit — APPROVED** [review]

**Comment by pedroerp** [comment]
Super awesome. Thanks @majetideepak!

**Comment by pedroerp** [comment]
Btw, this PR changes the API with Prestissimo, so it it will take me another minute to merge it and reconcile it.

**Comment by majetideepak** [comment]
@pedroerp I am curious to know what this API on the Prestissimo side is. I recently moved the Parquet Reader registration to Velox as well.

**Comment by pedroerp** [comment]
Yeah, just noticed that. Could you point me to the Presto PR where this was changed (the one that changed PrestoServer.cpp)?

**Comment by majetideepak** [comment]
@pedroerp this is the one https://github.com/prestodb/presto/pull/20321/

**Comment by pedroerp** [comment]
Nice, let me look into it. Thanks

**Pull request closed without merging**
