### PR TITLE
Upgrade FB_OS_VERSION to v2022.07.11.00

### PR DESCRIPTION
**Pull request by mshang816**
To fix an issue building fbthrift for presto_cpp https://github.com/facebook/fbthrift/pull/494

### CODE REVIEW

**Comment by majetideepak** [comment]
@kgpai can we merge this? Or is there more work?

**Comment by kgpai** [comment]
@majetideepak Before merging I would like the torcharrow image to be produced to validate that it builds. TA relies on centos 7(manylinux2014) which is somewhat old and hence any upgrade risks breaking it the most. 
@mshang816 Can you let us know if you are able to build that ?

**Comment by mshang816** [comment]
> @majetideepak Before merging I would like the torcharrow image to be produced to validate that it builds. TA relies on centos 7(manylinux2014) which is somewhat old and hence any upgrade risks breaking it the most. @mshang816 Can you let us know if you are able to build that ?

I was off for the past week. Will try to build the ta image. so we just have to make sure it can be built ? So the TA team can decide to use it or not ?

**Comment by kgpai** [comment]
@mshang816 Thats right.

**Comment by mshang816** [comment]
> @mshang816 Thats right.

Successfully build a touch arrow image prestocpp/velox-avx-velox-torcharrow:mikesh-20220804 and pushed it to docker hub.

**Pull request closed without merging**
