### PR TITLE
Upgrade Arrow version from 8.0.0 to 11.0.0

### PR DESCRIPTION
**Pull request by zhztheplayer**

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]

**Review by majetideepak — CHANGES_REQUESTED** [review]
@zhztheplayer `velox_arrow_bridge_test` build is failing. Can you take a look?

**Review by majetideepak — APPROVED** [review]

**Comment by Yuhta** [comment]
Any reason we want to upgrade arrow version?  Upgrading this requires us to reimport the new version of arrow internally, and that is a lot of work.  We should do that only if necessary.

**Comment by zhztheplayer** [comment]
I though it should be a quick update since our project [Gluten](http://github.com/oap-project/gluten) is also upgrading the Arrow version.

Would you like to explain a bit more about the difficuty you met for this upgrading? And indeed I don't have enough information about how much it costs internally so feel free to hold this off until the community think is needed.

**Comment by Yuhta** [comment]
@zhztheplayer When we upgrade a new version of third party dependency in mono repo, we need to import all transitive dependencies of the project as well.  This may take longer for large project like Arrow.  Also because in mono repo we are using buck instead of cmake, the build is not always straightforward.  So we only upgrade the version when necessary.

**Pull request closed without merging**
