### PR TITLE
Extract initializeVerifiers and compareEquivalentPlanResults in AggregationFuzzer

### PR DESCRIPTION
**Pull request by duanmeng**

### CODE REVIEW

**Comment by duanmeng** [comment]
@mbasmanova I've created this PR to extract initializeVerifiers and compareEquivalentPlanResults in AggregationFuzzer, could you please help to review? Thanks.

**Review by mbasmanova — APPROVED** [review]
Nice refactoring. Thanks.

**Comment by mbasmanova** [comment]
CI is red.

**Comment by duanmeng** [comment]
> CI is red.

@mbasmanova The error is strange, I use the same command locally and succeed. I will rebase and push again to trigger a rerun of the CI.
It looks like the failure is caused by lack of resources。
```C++
g++: fatal error: Killed signal terminated program cc1plus
```

**Comment by duanmeng** [comment]
@mbasmanova Hi Masha, now the CI has only one unrelated failure caused by a flaky test `AsyncDataCacheTest.tll`.  I can repeat it locally by repeated run. I will fix it separately when I have bandwidth.

### CI log
https://app.circleci.com/pipelines/github/facebookincubator/velox/42640/workflows/62ff9929-300f-48e9-8b68-753132aa24a7/jobs/295125  
```C++
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AsyncDataCacheTest.ttl
```

### local reproduce log
```C++
Repeating all tests (iteration 2) . . .

...
/Users/macduan/work/native/velox-2/velox/common/caching/tests/AsyncDataCacheTest.cpp:1144: Failure
Expected equality of these values:
  statsTtl.numAgedOut
    Which is: 0
  statsT1.numEntries
    Which is: 2046
/Users/macduan/work/native/velox-2/velox/common/caching/tests/AsyncDataCacheTest.cpp:1145: Failure
Expected equality of these values:
  statsTtl.ssdStats->entriesAgedOut
    Which is: 0
  statsT1.ssdStats->entriesCached
    Which is: 621
```

**Comment by mbasmanova** [comment]
@gggrace14 Ge, would you help take a look at AsyncDataCacheTest.tll failures?

**Comment by gggrace14** [comment]
> @mbasmanova Hi Masha, now the CI has only one unrelated failure caused by a flaky test `AsyncDataCacheTest.tll`. I can repeat it locally by repeated run. I will fix it separately when I have bandwidth.
> 
> ### CI log
> https://app.circleci.com/pipelines/github/facebookincubator/velox/42640/workflows/62ff9929-300f-48e9-8b68-753132aa24a7/jobs/295125
> 
> ```c++
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] AsyncDataCacheTest.ttl
> ```
> 
> ### local reproduce log
> ```c++
> Repeating all tests (iteration 2) . . .
> 
> ...
> /Users/macduan/work/native/velox-2/velox/common/caching/tests/AsyncDataCacheTest.cpp:1144: Failure
> Expected equality of these values:
>   statsTtl.numAgedOut
>     Which is: 0
>   statsT1.numEntries
>     Which is: 2046
> /Users/macduan/work/native/velox-2/velox/common/caching/tests/AsyncDataCacheTest.cpp:1145: Failure
> Expected equality of these values:
>   statsTtl.ssdStats->entriesAgedOut
>     Which is: 0
>   statsT1.ssdStats->entriesCached
>     Which is: 621
> ```

Hi @duanmeng , I'm looking at the failed unit test AsyncDataCacheTest.ttl. I think It's unrelated to this change. You can ignore it at the moment.

**Pull request closed without merging**
