### PR TITLE
Move test files to tests directory

### PR DESCRIPTION
**Pull request by leoluan2009**
Minor code refactor to move test files to tests directory

### CODE REVIEW

**Comment by leoluan2009** [comment]
@pedroerp can you help to review this pr?

**Comment by leoluan2009** [comment]
cc @mbasmanova

**Review by mbasmanova — APPROVED** [review]
@leoluan2009 Nice refactor. 

@Yuhta @bikramSingh91 @kgpai @kagamiori @laithsakka Folks, can one of you help merge this PR?

**Review by kgpai — APPROVED** [review]

**Comment by leoluan2009** [comment]
@mbasmanova @kgpai  Thanks!

**Pull request closed without merging**
