### PR TITLE
Add f_cdf Presto Function

### PR DESCRIPTION
**Pull request by rrando901**
Add Presto function f_cdf following the Java implementation([source](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java#L924))

Resolves: https://github.com/facebookincubator/velox/issues/5379

### CODE REVIEW

**Comment by rrando901** [comment]
@aditi-pandit @amitkdutta @Yuhta

The branch for https://github.com/facebookincubator/velox/pull/5384 is stale and is unable to be cleanly rebased.
This PR contains the same changes and is up-to-date with the main branch.

**Review by amitkdutta — APPROVED** [review]
Looks good. Thank @rrando901

**Review by aditi-pandit — APPROVED** [review]
Thanks for this function.

**Comment by Yuhta** [comment]
Have we run fuzzer on this function?

**Comment by aditi-pandit** [comment]
> Have we run fuzzer on this function?

@Yuhta : Yes. From the original PR :
Fuzzer output

I20230623 17:46:42.158910 443986 ExpressionVerifier.cpp:56] ===================
I20230623 17:46:42.158933 443986 ExpressionVerifier.cpp:67] All results match.
I20230623 17:46:42.158983 443986 ExpressionFuzzer.cpp:1357] ==============================> Done with iteration 428
I20230623 17:46:42.159350 443986 ExpressionFuzzer.cpp:1092] ==============================> Top 1 by number of rows processed
I20230623 17:46:42.159369 443986 ExpressionFuzzer.cpp:1094] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230623 17:46:42.159384 443986 ExpressionFuzzer.cpp:1098] f_cdf 44818 100.00% 5376
I20230623 17:46:42.159400 443986 ExpressionFuzzer.cpp:1104] ==============================> Bottom 1 by number of rows processed
I20230623 17:46:42.159415 443986 ExpressionFuzzer.cpp:1106] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230623 17:46:42.159427 443986 ExpressionFuzzer.cpp:1111] f_cdf 44818 100.00% 5376
I20230623 17:46:42.159442 443986 ExpressionFuzzer.cpp:1124] ==============================> All stats sorted by number of times the function was chosen
I20230623 17:46:42.159456 443986 ExpressionFuzzer.cpp:1126] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230623 17:46:42.159468 443986 ExpressionFuzzer.cpp:1130] f_cdf 44818 100.00% 5376
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.

**Pull request closed without merging**
