### PR TITLE
Add weibull_cdf Presto function

### PR DESCRIPTION
**Pull request by Krishna-Prasad-P-V**
Resolves https://github.com/facebookincubator/velox/issues/4760

### CODE REVIEW

**Comment by Krishna-Prasad-P-V** [comment]
@aditi-pandit - Could you please review this PR from your end? Thanks.

**Comment by aditi-pandit** [comment]
@Krishna-Prasad-P-V : The code looks good. But the build has error (not in your code though). Please rebase the code once that broken code is fixed and I will approve.

**Comment by aditi-pandit** [comment]
@Krishna-Prasad-P-V : Please can you rebase this PR. There are conflicts.

**Comment by aditi-pandit** [comment]
@Krishna-Prasad-P-V : I still see conflicts. Does this need another rebase ?

**Comment by Krishna-Prasad-P-V** [comment]
> @Krishna-Prasad-P-V : I still see conflicts. Does this need another rebase ?

@aditi-pandit - I have again rebased.

**Comment by aditi-pandit** [comment]
@Krishna-Prasad-P-V : Please check the fuzzer errors.

**Review by aditi-pandit — APPROVED** [review]

**Comment by Krishna-Prasad-P-V** [comment]
I need to check why their are fuzzer test errors. Will work on it.

**Comment by aditi-pandit** [comment]
Fuzzer test output for weibull_cdf:

I20230628 09:47:29.582652 1731535 ExpressionVerifier.cpp:56] ===================
I20230628 09:47:29.582690 1731535 ExpressionVerifier.cpp:67] All results match.
I20230628 09:47:29.582752 1731535 ExpressionFuzzer.cpp:1357] ==============================> Done with iteration 850
I20230628 09:47:29.583197 1731535 ExpressionFuzzer.cpp:1092] ==============================> Top 1 by number of rows processed
I20230628 09:47:29.583209 1731535 ExpressionFuzzer.cpp:1094] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230628 09:47:29.583216 1731535 ExpressionFuzzer.cpp:1098] weibull_cdf 96259 100.00% 10164
I20230628 09:47:29.583249 1731535 ExpressionFuzzer.cpp:1104] ==============================> Bottom 1 by number of rows processed
I20230628 09:47:29.583256 1731535 ExpressionFuzzer.cpp:1106] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230628 09:47:29.583261 1731535 ExpressionFuzzer.cpp:1111] weibull_cdf 96259 100.00% 10164
I20230628 09:47:29.583276 1731535 ExpressionFuzzer.cpp:1124] ==============================> All stats sorted by number of times the function was chosen
I20230628 09:47:29.583282 1731535 ExpressionFuzzer.cpp:1126] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20230628 09:47:29.583292 1731535 ExpressionFuzzer.cpp:1130] weibull_cdf 96259 100.00% 10164

**Comment by majetideepak** [comment]
@Krishna-Prasad-P-V there is something going on with your PRs suddenly. All CI tests are failing.
Same symptoms here as well https://github.com/facebookincubator/velox/pull/6039

**Comment by Krishna-Prasad-P-V** [comment]
> @Krishna-Prasad-P-V there is something going on with your PRs suddenly. All CI tests are failing. Same symptoms here as well #6039

I see this error in the CircleCI page.
```
Resource class docker for 2xlarge is not available for your project, or is not a valid resource class. This message will often appear if the pricing plan for this project does not support docker use.
```

**Comment by majetideepak** [comment]
@Krishna-Prasad-P-V can you apply this change in your PR https://github.com/facebookincubator/velox/pull/6181 and push again?
Likely format-check failure is not triggering other CI jobs.

**Comment by Krishna-Prasad-P-V** [comment]
@majetideepak @aditi-pandit - Even after the format-check being success, the CI pipelines are not running for me.

**Comment by majetideepak** [comment]
@Krishna-Prasad-P-V For some reason, your CI tests are running in your CircleCI account instead of facebookincubator account.
Can you create a new fork of Velox and check?

**Pull request closed without merging**
