### PR TITLE
Add cosh SparkSQL function

### PR DESCRIPTION
**Pull request by myandpr**
Spark's docs: [cosh](https://spark.apache.org/docs/latest/api/sql/#cosh)

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Comment by mbasmanova** [comment]
@myandpr Would you rebase so I could merge?

**Comment by myandpr** [comment]
> @myandpr Would you rebase so I could merge?

@mbasmanova Sorry for taking so long to reply due to some personal reasons.

I have rebased.

**Comment by mbasmanova** [comment]
@myandpr No problem. Thank you for the contribution.

**Pull request closed without merging**
