### PR TITLE
Add Presto inverse_laplace_cdf function

### PR DESCRIPTION
**Pull request by wills-feng**
Resolves https://github.com/facebookincubator/velox/issues/5541
This is a followup for https://github.com/facebookincubator/velox/pull/5543

### CODE REVIEW

**Comment by aditi-pandit** [comment]
@wills-feng : Please can you also give the fuzzer output for this function.

**Comment by wills-feng** [comment]
@aditi-pandit  I made some changes from the original version. Can you please review and let me know if it makes sense? 

Below is the fuzzer output. 
```
I20240416 14:36:46.609010 25455294 ExpressionFuzzerVerifier.cpp:367] ==============================> Done with iteration 175672
I20240416 14:36:46.609084 25455294 ExpressionFuzzerVerifier.cpp:164] ==============================> Top 1 by number of rows processed
I20240416 14:36:46.609098 25455294 ExpressionFuzzerVerifier.cpp:166] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240416 14:36:46.609113 25455294 ExpressionFuzzerVerifier.cpp:170] inverse_laplace_cdf 3989020 100.00% 4101020
I20240416 14:36:46.609131 25455294 ExpressionFuzzerVerifier.cpp:176] ==============================> Bottom 1 by number of rows processed
I20240416 14:36:46.609143 25455294 ExpressionFuzzerVerifier.cpp:178] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240416 14:36:46.609156 25455294 ExpressionFuzzerVerifier.cpp:183] inverse_laplace_cdf 3989020 100.00% 4101020
I20240416 14:36:46.609169 25455294 ExpressionFuzzerVerifier.cpp:196] ==============================> All stats sorted by number of times the function was chosen
I20240416 14:36:46.609182 25455294 ExpressionFuzzerVerifier.cpp:198] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240416 14:36:46.609194 25455294 ExpressionFuzzerVerifier.cpp:202] inverse_laplace_cdf 3989020 100.00% 4101020
E20240416 14:36:46.609208 25455294 ExpressionFuzzerVerifier.cpp:373] Total iterations: 175673
E20240416 14:36:46.609221 25455294 ExpressionFuzzerVerifier.cpp:374] Total failed: 11360
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

**Comment by wills-feng** [comment]
@aditi-pandit I rewrote the function and tests. Also posted the fuzzer tests below, please help review, thanks.

```
I20240422 11:30:06.057255 28557681 ExpressionFuzzerVerifier.cpp:367] ==============================> Done with iteration 168281
I20240422 11:30:06.057325 28557681 ExpressionFuzzerVerifier.cpp:164] ==============================> Top 1 by number of rows processed
I20240422 11:30:06.057338 28557681 ExpressionFuzzerVerifier.cpp:166] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240422 11:30:06.057350 28557681 ExpressionFuzzerVerifier.cpp:170] inverse_laplace_cdf 3813524 100.00% 3941527
I20240422 11:30:06.057366 28557681 ExpressionFuzzerVerifier.cpp:176] ==============================> Bottom 1 by number of rows processed
I20240422 11:30:06.057379 28557681 ExpressionFuzzerVerifier.cpp:178] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240422 11:30:06.057392 28557681 ExpressionFuzzerVerifier.cpp:183] inverse_laplace_cdf 3813524 100.00% 3941527
I20240422 11:30:06.057405 28557681 ExpressionFuzzerVerifier.cpp:196] ==============================> All stats sorted by number of times the function was chosen
I20240422 11:30:06.057418 28557681 ExpressionFuzzerVerifier.cpp:198] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I20240422 11:30:06.057430 28557681 ExpressionFuzzerVerifier.cpp:202] inverse_laplace_cdf 3813524 100.00% 3941527
E20240422 11:30:06.057442 28557681 ExpressionFuzzerVerifier.cpp:373] Total iterations: 168282
E20240422 11:30:06.057454 28557681 ExpressionFuzzerVerifier.cpp:374] Total failed: 10924
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
```

**Review by aditi-pandit — APPROVED** [review]
Thanks @wills-feng. Looks good.

**Comment by aditi-pandit** [comment]
@kagamiori, @Yuhta, @kgpai : Please can you help with review and merge.

**Review by Yuhta — APPROVED** [review]

**Comment by wills-feng** [comment]
There are 3 probability functions PRs are waiting for merge. I have rebased https://github.com/facebookincubator/velox/pull/9492, once it gets merged, I will rebase this one.

**Comment by wills-feng** [comment]
Once https://github.com/facebookincubator/velox/pull/9494 gets merged, I'll rebase this one.

**Comment by pedroerp** [comment]
@wills-feng #9494 was merged.

**Comment by wills-feng** [comment]
@pedroerp rebased and CI passed.

**Pull request closed without merging**
