### PR TITLE
Improve decimal overflow message

### PR DESCRIPTION
**Pull request by karteekmurthys**
Add "Decimal overflow." prefix to the existing message to be consistent with Presto messaging.

### CODE REVIEW

**Comment by majetideepak** [comment]
@karteekmurthys can we add some tests that enforce this Prefix?

**Comment by karteekmurthys** [comment]
> @karteekmurthys can we add some tests that enforce this Prefix?

Extended error messages of existing tests.

**Comment by yzhang1991** [comment]
Hi @majetideepak, can we revisit this?

**Comment by karteekmurthys** [comment]
@mbasmanova would you please review this change.

**Review by mbasmanova — APPROVED** [review]
Thanks.

**Pull request closed without merging**
