### PR TITLE
Back out "Support multiple HDFS endpoints"

### PR DESCRIPTION
**Pull request by AGFeldman**
Reviewed By: pedroerp

Differential Revision: D45678607

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@AGFeldman, is there any issue newly found in this patch? Please let me know what we should fix. Thanks!

**Review by majetideepak — CHANGES_REQUESTED** [review]
@AGFeldman Can you please explain why this is being backed out?

**Comment by majetideepak** [comment]
Looks like a version of this is already on main.
https://github.com/facebookincubator/velox/commit/a3344d8ead6de39f1b1332554b3f94c40d5143f7

**Comment by pedroerp** [comment]
> @AGFeldman Can you please explain why this is being backed out? CC: @pedroerp

This ended up breaking some internal builds due to the API change. At that time, it was easier to revert to unblock the builds. I'm adding it back in #4901. Sorry about the hassle.

**Pull request closed without merging**
