### PR TITLE
Fix velox/docs/README.md

### PR DESCRIPTION
**Pull request by acvictor**
Update README to build documentation.

Addresses #8889

### CODE REVIEW

**Comment by acvictor** [comment]
@kgpai can you please review this? Thanks!

**Comment by kgpai** [comment]
@acvictor Thanks for this change, but I am afraid this documentation is wrong. The right way to build is to go to velox/docs and run make html. We need to remove gen-docs as that was required to build pyvelox related documentation. We should make that clear in this README. I will edit the associated issue you have linked and maybe you can make the changes to make the readme right in this PR ?

**Comment by acvictor** [comment]
> @acvictor Thanks for this change, but I am afraid this documentation is wrong. The right way to build is to go to velox/docs and run make html. We need to remove gen-docs as that was required to build pyvelox related documentation. We should make that clear in this README. I will edit the associated issue you have linked and maybe you can make the changes to make the readme right in this PR ?

@kgpai will do! Can `gen-docs.sh` be deleted?

**Comment by kgpai** [comment]
> @kgpai will do! Can gen-docs.sh be deleted?

Yes !

**Comment by acvictor** [comment]
> > @kgpai will do! Can gen-docs.sh be deleted?
> 
> Yes !

Done.

**Comment by mbasmanova** [comment]
@kgpai Krishna, is anything blocking this PR from landing?

**Pull request closed without merging**
