### PR TITLE
test

### PR DESCRIPTION
**Pull request by duanmeng**

### CODE REVIEW

**Comment by czentgr** [comment]
The benchmark does build on Ubuntu. Previously, boost was installed through the package manager.

There are two problems:
1. Why is the setup-ubuntu script not running the various install functions (for folly, fmt, boost etc). This would install boost into the system. I only see the package manager being executed but none of the other libraries are downloaded and built.
2. When boost is built from the bundle the dependency to boost is not declared for the sparksql function library. Therefore it won;t find the header from the bundled location.
3. There is a possibility the header is actually not needed and can be removed.

**Comment by czentgr** [comment]
I was able to locally repro and fix the issue: https://github.com/facebookincubator/velox/pull/8936

**Comment by mbasmanova** [comment]
@duanmeng Is this PR still needed? Feel free to reopen if so.

**Comment by duanmeng** [comment]
> @duanmeng Is this PR still needed? Feel free to reopen if so.

@mbasmanova Hi Masha, there is no need for this PR. It is a test PR for investigating removing `testWithTableScan` flag, which has been merged in https://github.com/facebookincubator/velox/pull/8958.

**Pull request closed without merging**
