### PR TITLE
[Mac][minor] Add `libsodium` homebrew dep and reformatting

### PR DESCRIPTION
**Pull request by darrenfu**
To solve issue #3474

### CODE REVIEW

**Comment by darrenfu** [comment]
> I can't test locally but looks good. As long as we are not depending on any specific version of these (e.g. fmt) this is a nice change.

Thanks for the approval! 
I left `fmt` not upgraded to latest because Meta internal is still using an old version: 8.0.x. If upgrade, it will break other libraries depending on velox library. 

At some point, if the whole velox repo is upgraded to c++ 20, we can get free upgrade to `std::format`, which is even better!

**Comment by darrenfu** [comment]
Since velox team decided to use cmake for dependency management, I will trim this PR for some minor changes and formatting.

**Comment by assignUser** [comment]
> use cmake for dependency management

Just to clarify the recent work on `resolve_dependency` works with system dependencies but allows us to fallback to building the deps from source if they are not found. (or the user explicitly chooses with `VELOX_DEPENDENCY_SOURCE=BUNDLED`)

**Comment by darrenfu** [comment]
> > use cmake for dependency management
> 
> Just to clarify the recent work on `resolve_dependency` works with system dependencies but allows us to fallback to building the deps from source if they are not found. (or the user explicitly chooses with `VELOX_DEPENDENCY_SOURCE=BUNDLED`)

cc @kgpai - would you be aligned with @assignUser on the dep management direction as well as the fallback alternative?

**Comment by darrenfu** [comment]
Since the velox team decided to go with cmake system dependencies rather than brewed libraries, will close this PR for now.
Fallback brewed deps are optional at this point.

**Pull request closed without merging**
