### PR TITLE
Add SimdUtilBenchmark

### PR DESCRIPTION
**Pull request by Yuhta**
Differential Revision: D51555528

### CODE REVIEW

**Comment by majetideepak** [comment]
@Yuhta, can we put all the benchmarks under `velox/benchmarks` since it is easier to find them? Thanks.
CC: @pedroerp, @mbasmanova

**Comment by mbasmanova** [comment]
> can we put all the benchmarks under velox/benchmarks since it is easier to find them? 

@majetideepak This may not scale well. Benchmarks are similar to tests. There are lots of them and they "belong" to different parts of the code. Perhaps, we could adopt a convention of having xxx/tests and xxx/benchmarks directories for each "production" xxx directory.

**Comment by majetideepak** [comment]
> Perhaps, we could adopt a convention of having xxx/tests and xxx/benchmarks directories for each "production" xxx directory.

@mbasmanova I did not understand this statement. Can you please explain what you mean by "production"?

>  Benchmarks are similar to tests

Velox users would benefit from benchmarks on testing various platforms. Tests not so much. For example, the ReadBenchmark is helpful to analyze the throughput from a storage but is hidden somewhere in the Velox code. To make it harder, there are three different versions of this benchmark for each filesystem duplicating a lot of code.
I opened a PR here to combine them here: https://github.com/facebookincubator/velox/pull/8813

**Comment by Yuhta** [comment]
I agree with Masha to put micro benchmark under the directory with its own production code.  Only a few benchmark belonging to integration level should be moved to the common benchmark directory.  And with those benchmarks, we need to be careful about the dependencies and not making the common benchmark depending on the whole world.  Maybe we will need some subdirectory under the common benchmark directory at some point.

BTW this PR is already merged.

**Pull request closed without merging**
