### PR TITLE
Add Findstemmer.cmake to find lib stemmer

### PR DESCRIPTION
**Pull request by PHILO-HE**
This pr adds lib stemmer to setup script and allows cmake to find this installed lib during building velox.

### CODE REVIEW

**Comment by jinchengchenghh** [comment]
Please update the PR title, drop `[VL]`

**Comment by PHILO-HE** [comment]
> Please update the PR title, drop `[VL]`

@jinchengchenghh, thanks for your comment! Just updated.

**Review by assignUser — APPROVED** [review]
Nice!

**Comment by PHILO-HE** [comment]
@kgpai, could you also take a look? Thanks!

**Comment by mbasmanova** [comment]
@PHILO-HE There are Fuzzer failures. Would you take a look?

**Comment by PHILO-HE** [comment]
> @PHILO-HE There are Fuzzer failures. Would you take a look?

@mbasmanova, we will look into this issue. Assume it is not relevant to this pr.

**Comment by PHILO-HE** [comment]
@mbasmanova, I just rebased the pr. Thanks!

**Comment by PHILO-HE** [comment]
@mbasmanova, the CI failure is irrelevant, and it was just fixed by https://github.com/facebookincubator/velox/commit/4744994ae0f4c496ac65cf4637cab2626203ae9a.

**Comment by kgpai** [comment]
@PHILO-HE We had to revert this PR because it broke pyvelox and fuzzer builds. It's because the docker images produced did not work well with pyvelox . I recommend we create another PR just to make changes to the images, see if they work and subsequently land them and then re-add this findstemmer change. Thank you !

**Comment by PHILO-HE** [comment]
> @PHILO-HE We had to revert this PR because it broke pyvelox and fuzzer builds. It's because the docker images produced did not work well with pyvelox . I recommend we create another PR just to make changes to the images, see if they work and subsequently land them and then re-add this findstemmer change. Thank you !

@kgpai, I understand the reverting. Will fix that issue.

**Pull request closed without merging**
