### PR TITLE
Ensure ConnectorQueryCtx does not become a dangling pointer when SplitPreload is enabled

### PR DESCRIPTION
**Pull request by zhli1142015**
Fixes: #9545 
Store `shared_ptr<ConnectorQueryCtx>` instead of` ConnectorQueryCtx*` in `SplitReader` 
to prevent dangling pointer issue when split preloading enabled.

### CODE REVIEW

**Comment by Yuhta** [comment]
Thanks for spotting this issue.  The fix works memory-wise, however there still could be mismatch between the `ConnectorQueryCtx` kept by the preloaded source vs the current driver.  I think we should add a `SplitReader::setConnectorQueryCtx` method and call it in `setFromDataSource`.  What do you think?

**Review by yingsu00 — COMMENTED** [review]
@zhli1142015 Thanks for sending the fix! I'm wondering if a test could be added to repro the issue in [Crash in IcebergSplitReader when SplitPreload enabled](https://github.com/facebookincubator/velox/issues/9545#top)?

**Comment by zhli1142015** [comment]
> @zhli1142015 Thanks for sending the fix! I'm wondering if a test could be added to repro the issue in [Crash in IcebergSplitReader when SplitPreload enabled](https://github.com/facebookincubator/velox/issues/9545#top)?

It's reproduced with multiple splits and preloading enabled, add a new UT in `HiveIcebergTest` to repro it, thanks.

**Comment by zhli1142015** [comment]
> Thanks for spotting this issue. The fix works memory-wise, however there still could be mismatch between the `ConnectorQueryCtx` kept by the preloaded source vs the current driver. I think we should add a `SplitReader::setConnectorQueryCtx` method and call it in `setFromDataSource`. What do you think?

Added, thanks.

**Review by Yuhta — APPROVED** [review]

**Comment by Yuhta** [comment]
@zhli1142015 It seems there is just too many connector subclasses to be updated.  Since the lifecycle of `ConnectorQueryCtx` is supposed to be longer than `DataSource`, can we change the shared_ptr back to raw pointer?  The issue should already fixed with the addition of `setConnectorQueryCtx`

**Comment by zhli1142015** [comment]
> @zhli1142015 It seems there is just too many connector subclasses to be updated. Since the lifecycle of `ConnectorQueryCtx` is supposed to be longer than `DataSource`, can we change the shared_ptr back to raw pointer? The issue should already fixed with the addition of `setConnectorQueryCtx`

Updated, thanks.

**Comment by Yuhta** [comment]
Can you rebase to latest to get rid of build failure?  Also seems there is some memory leak in exchange, not sure if it is related.

**Comment by Yuhta** [comment]
There is crash in `TableScanTest.parallelPrepare`

```
Note: Google Test filter = TableScanTest.parallelPrepare
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TableScanTest
[ RUN      ] TableScanTest.parallelPrepare

I0423 08:45:30.513954 304460 HiveConnector.cpp:69] Hive connector test-hive created with maximum of 20000 cached file handles.
I0423 08:45:30.516470 304460 Compression.cpp:628] Initialized zstd compressor with compression level 7
I0423 08:45:30.518788 304460 FileSink.cpp:125] closing file: /tmp/velox_test_qYezhz,  total size: 488B
AddressSanitizer:DEADLYSIGNAL
=================================================================
==304460==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x7fa541b8b822 bp 0x7fa4e2783130 sp 0x7fa4e2783100 T38)
==304460==The signal is caused by a READ memory access.
==304460==Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/unique_ptr.h:407: typename add_lvalue_reference<element_type>::type std::unique_ptr<facebook::velox::SelectivityVector>::operator*() const [_Tp = facebook::velox::SelectivityVector, _Dp = std::default_delete<facebook::velox::SelectivityVector>]: Assertion 'get() != pointer()' failed.
*** Aborted at 1713887130 (Unix time, try 'date -d @1713887130') ***
*** Signal 6 (SIGABRT) (0x75590004a54c) received by PID 304460 (pthread TID 0x7fa4e1483640) (linux TID 304502) (maybe from PID 304460, UID 30041) (code: -6), stack trace: ***
    #0 0x7fa541b8b822 in __gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int>>>::__normal_iterator(int const* const&) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_iterator.h:1011
    #1 0x7fa541b8b612 in std::vector<int, std::allocator<int>>::begin() const fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_vector.h:821
    #2 0x7fa541b8b168 in std::vector<int, std::allocator<int>>::empty() const fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_vector.h:1008
    #3 0x7fa541b8ad1c in facebook::velox::DecodedVector::indicesNotCopied() const fbcode/velox/vector/DecodedVector.h:321
    #4 0x7fa541b8942c in facebook::velox::DecodedVector::reset(int) fbcode/velox/vector/DecodedVector.cpp:108
    #5 0x7fa541b887b5 in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*, bool) fbcode/velox/vector/DecodedVector.cpp:51
    #6 0x7fa5345edb90 in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const&, bool) fbcode/velox/vector/DecodedVector.h:124
    #7 0x7fa5345ecb0e in facebook::velox::exec::LocalDecodedVector::LocalDecodedVector(facebook::velox::exec::EvalCtx const&, facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const&, bool) fbcode/velox/expression/EvalCtx.h:553
    #8 0x7fa5337cac25 in facebook::velox::exec::CastExpr::apply(facebook::velox::SelectivityVector const&, std::shared_ptr<facebook::velox::BaseVector> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::Type const> const&, std::shared_ptr<facebook::velox::Type const> const&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/CastExpr.cpp:852
    #9 0x7fa53377cb20 in facebook::velox::exec::CastExpr::evalSpecialForm(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/CastExpr.cpp:923
    #10 0x7fa53475832a in facebook::velox::exec::Expr::evalSpecialFormWithStats(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1564
    #11 0x7fa534768730 in facebook::velox::exec::Expr::evalAllImpl(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1413
    #12 0x7fa53475e5e6 in facebook::velox::exec::Expr::evalAll(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1395
    #13 0x7fa534761823 in facebook::velox::exec::Expr::evalWithNulls(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1185
    #14 0x7fa53475ec71 in facebook::velox::exec::Expr::evalEncodings(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1107
    #15 0x7fa53475dee3 in facebook::velox::exec::Expr::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&, facebook::velox::exec::ExprSet const*) fbcode/velox/expression/Expr.cpp:857
    #16 0x7fa5347c30aa in facebook::velox::exec::(anonymous namespace)::tryFoldIfConstant(std::shared_ptr<facebook::velox::exec::Expr> const&, facebook::velox::exec::(anonymous namespace)::Scope*) fbcode/velox/expression/ExprCompiler.cpp:312
    #17 0x7fa5347ba64c in facebook::velox::exec::(anonymous namespace)::compileRewrittenExpression(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, bool) fbcode/velox/expression/ExprCompiler.cpp:515
    #18 0x7fa5347ad7d1 in facebook::velox::exec::(anonymous namespace)::compileExpression(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, bool) fbcode/velox/expression/ExprCompiler.cpp:532
    #19 0x7fa5347bdc74 in facebook::velox::exec::(anonymous namespace)::compileInputs(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, bool) fbcode/velox/expression/ExprCompiler.cpp:201
    #20 0x7fa5347b6d7c in facebook::velox::exec::(anonymous namespace)::compileRewrittenExpression(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, bool) fbcode/velox/expression/ExprCompiler.cpp:383
    #21 0x7fa5347ad7d1 in facebook::velox::exec::(anonymous namespace)::compileExpression(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, bool) fbcode/velox/expression/ExprCompiler.cpp:532
    #22 0x7fa5347bdaf5 in facebook::velox::exec::(anonymous namespace)::compileInputs(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, s
...
...
...
y::ThreadPoolExecutor::Thread>) fbcode/folly/executors/CPUThreadPoolExecutor.cpp:350
    #27 0x7fa544abbed3 in void std::__invoke_impl<void, void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&>(std::__invoke_memfun_deref, void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/invoke.h:74
    #28 0x7fa544abbc94 in std::__invoke_result<void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&>::type std::__invoke<void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&>(void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/invoke.h:96
    #29 0x7fa544abbbf3 in void std::_Bind<void (folly::ThreadPoolExecutor::* (folly::ThreadPoolExecutor*, std::shared_ptr<folly::ThreadPoolExecutor::Thread>))(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)>::__call<void, 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/functional:420
    #30 0x7fa544abba5d in void std::_Bind<void (folly::ThreadPoolExecutor::* (folly::ThreadPoolExecutor*, std::shared_ptr<folly::ThreadPoolExecutor::Thread>))(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)>::operator()<void>() fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/functional:503
    #31 0x7fa544abb77c in void folly::detail::function::call_<std::_Bind<void (folly::ThreadPoolExecutor::* (folly::ThreadPoolExecutor*, std::shared_ptr<folly::ThreadPoolExecutor::Thread>))(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)>, true, false, void>(folly::detail::function::Data&) fbcode/folly/Function.h:341
    #32 0x1baac26 in folly::detail::function::FunctionTraits<void ()>::operator()() fbcode/folly/Function.h:370
    #33 0x2425ce4 in folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()::operator()() fbcode/folly/executors/thread_factory/NamedThreadFactory.h:40
    #34 0x2425ba4 in void std::__invoke_impl<void, folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>(std::__invoke_other, folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()&&) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/invoke.h:61
    #35 0x2425b64 in std::__invoke_result<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>::type std::__invoke<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>(folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()&&) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/invoke.h:96
    #36 0x2425b3c in void std::thread::_Invoker<std::tuple<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>>::_M_invoke<0ul>(std::_Index_tuple<0ul>) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/std_thread.h:253
    #37 0x2425b14 in std::thread::_Invoker<std::tuple<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>>::operator()() fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/std_thread.h:260
    #38 0x24259d8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>>>::_M_run() fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/std_thread.h:211
    #39 0x7fa5194df4e4 in execute_native_thread_routine /home/engshare/third-party2/libgcc/11.x/src/gcc-11.x/x86_64-facebook-linux/libstdc++-v3/src/c++11/../../../.././libstdc++-v3/src/c++11/thread.cc:82:18
    #40 0x7fa51989ac28 in start_thread /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/nptl/pthread_create.c:434:8

Thread T36 created by T0 here:
    #0 0x2b40eb2 in __interceptor_pthread_create (/data/sandcastle/boxes/eden-trunk-hg-full-fbsource/buck-out/v2/gen/fbcode/05af3bec81fdae30/velox/exec/tests/__velox_exec_test__/velox_exec_test+0x2b40eb2)
    #1 0x7fa5194df80e in __gthread_create /home/engshare/third-party2/libgcc/11.x/src/gcc-11.x/x86_64-facebook-linux/libstdc++-v3/include/x86_64-facebook-linux/bits/gthr-default.h:663:35
    #2 0x7fa5194df80e in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State>>, void (*)()) /home/engshare/third-party2/libgcc/11.x/src/gcc-11.x/x86_64-facebook-linux/libstdc++-v3/src/c++11/../../../.././libstdc++-v3/src/c++11/thread.cc:147:37
    #3 0x2424dea in std::thread::thread<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'(), void>(folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()&&) fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/std_thread.h:143
    #4 0x242444a in folly::NamedThreadFactory::newThread(folly::Function<void ()>&&) fbcode/folly/executors/thread_factory/NamedThreadFactory.h:37
    #5 0x7fa544ab74a9 in folly::ThreadPoolExecutor::addThreads(unsigned long) fbcode/folly/executors/ThreadPoolExecutor.cpp:250
    #6 0x7fa544ae9d90 in folly::ThreadPoolExecutor::ensureActiveThreads() fbcode/folly/executors/ThreadPoolExecutor.cpp:545
    #7 0x7fa544c5ed6b in void folly::CPUThreadPoolExecutor::addImpl<false>(folly::Function<void ()>, signed char, std::chrono::duration<long, std::ratio<1l, 1000l>>, folly::Function<void ()>) fbcode/folly/executors/CPUThreadPoolExecutor.cpp:266
    #8 0x7fa544b6dd0b in folly::CPUThreadPoolExecutor::add(folly::Function<void ()>, std::chrono::duration<long, std::ratio<1l, 1000l>>, folly::Function<void ()>) fbcode/folly/executors/CPUThreadPoolExecutor.cpp:210
    #9 0x7fa544b6d60f in folly::CPUThreadPoolExecutor::add(folly::Function<void ()>) fbcode/folly/executors/CPUThreadPoolExecutor.cpp:205
    #10 0x7fa53d0ae391 in facebook::velox::exec::Driver::enqueue(std::shared_ptr<facebook::velox::exec::Driver>) fbcode/velox/exec/Driver.cpp:269
    #11 0x7fa53d8ff46b in facebook::velox::exec::Task::createAndStartDrivers(unsigned int) fbcode/velox/exec/Task.cpp:845
    #12 0x7fa53d8fb6a4 in facebook::velox::exec::Task::start(unsigned int, unsigned int) fbcode/velox/exec/Task.cpp:736
    #13 0x7fa5355fdd02 in facebook::velox::exec::test::MultiThreadedTaskCursor::start() fbcode/velox/exec/tests/utils/Cursor.cpp:268
    #14 0x7fa5355fdf5b in facebook::velox::exec::test::MultiThreadedTaskCursor::moveNext() fbcode/velox/exec/tests/utils/Cursor.cpp:276
    #15 0x7fa5358302e0 in facebook::velox::exec::test::readCursor(facebook::velox::exec::test::CursorParameters const&, std::function<void (facebook::velox::exec::Task*)>, unsigned long) fbcode/velox/exec/tests/utils/QueryAssertions.cpp:1367
    #16 0x7fa5355d9150 in facebook::velox::exec::test::AssertQueryBuilder::readCursor() fbcode/velox/exec/tests/utils/AssertQueryBuilder.cpp:262
    #17 0x7fa5355db797 in facebook::velox::exec::test::AssertQueryBuilder::copyResults(facebook::velox::memory::MemoryPool*, std::shared_ptr<facebook::velox::exec::Task>&) fbcode/velox/exec/tests/utils/AssertQueryBuilder.cpp:208
    #18 0x7fa5355db509 in facebook::velox::exec::test::AssertQueryBuilder::copyResults(facebook::velox::memory::MemoryPool*) fbcode/velox/exec/tests/utils/AssertQueryBuilder.cpp:202
    #19 0x2603619 in TableScanTest_parallelPrepare_Test::TestBody() fbcode/velox/exec/tests/TableScanTest.cpp:3456
    #20 0x7fa5452d073e in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) fbsource/src/gtest.cc:2675
    #21 0x7fa5452cffc4 in testing::Test::Run() fbsource/src/gtest.cc:2692
    #22 0x7fa5452d5bff in testing::TestInfo::Run() fbsource/src/gtest.cc:2841
    #23 0x7fa5452ddbb6 in testing::TestSuite::Run() fbsource/src/gtest.cc:3020
    #24 0x7fa54531951b in testing::internal::UnitTestImpl::RunAllTests() fbsource/src/gtest.cc:5925
    #25 0x7fa54531857b in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) fbsource/src/gtest.cc:2675
    #26 0x7fa545317ab9 in testing::UnitTest::Run() fbsource/src/gtest.cc:5489
    #27 0x1bf1050 in RUN_ALL_TESTS() fbsource/gtest/gtest.h:2317
    #28 0x1bf0f11 in main fbcode/velox/exec/tests/Main.cpp:28
    #29 0x7fa51982c656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #30 0x7fa51982c717 in [__libc_start_main@GLIBC_2.2.5](mailto:__libc_start_main@GLIBC_2.2.5) /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #31 0xc26e30 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

==304460==ABORTING

Test was never completed. The test process might have crashed.
(Truncated to 18976 bytes by Tpx; full output here: everstore://GAdHiAd8DxmYOg4DABNJbK9q9ugibswMAAAz:Full_Test_Output: - Alternatively, you can use `bunnylol everpaste GAdHiAd8DxmYOg4DABNJbK9q9ugibswMAAAz`)
```

**Review by yingsu00 — APPROVED** [review]

**Pull request closed without merging**
