### PR TITLE
Add to_iso8601() presto function

### LINKED ISSUE #4725: Implement to_ISO8601() presto function
### Description

Implement `to_ISO8601()` presto function in velox. 

Changes can be tracked here - https://github.com/facebookincubator/velox/compare/main...svm1:velox:svm_to_iso?expand=1

### PR DESCRIPTION
**Pull request by svm1**
Implementing `to_iso8601()` presto function with three signatures for `Date`, `Timestamp`, and `TimestampWithTimezone` input. Adding test cases to validate functionality.

Created new PR due to issues with squashing and rebasing on the original.

Resolves #4725

### CODE REVIEW

**Comment by svm1** [comment]
@aditi-pandit @majetideepak I've finalized my changes here, including accounting for Date type refactor. However, a concern with DST remains - copying my comment from my original PR:

> Though it does not account for DST, which Presto seems to be doing:
> 
> presto:default> SELECT to_iso8601(TIMESTAMP '2001-08-22 03:04:05.321 America/Los_Angeles');
>              _col0             
> -------------------------------
>  2001-08-22T03:04:05.321-07:00 
> (1 row)
> 
> I don't see this being possible unless we store some additional info, perhaps in the `TimeZoneDatabase`, to keep track of which timezones use DST, as well as the portions of the year DST would apply to.
> 
> Any thoughts?

**Comment by svm1** [comment]
@mbasmanova would appreciate your input on the situation here, in regard to adding `to_iso8601()` function to velox:

> My implementation does not account for DST, which Presto seems to be doing:
``` 
presto:default> SELECT to_iso8601(TIMESTAMP '2001-08-22 03:04:05.321 America/Los_Angeles');
             _col0             
 -------------------------------
 2001-08-22T03:04:05.321-07:00 
(1 row)
```
> I don't see this being possible unless we store some additional info, perhaps in the `TimeZoneDatabase`, to keep track of which timezones use DST, as well as the portions of the year DST would apply to.
> 
> Any thoughts?

**Comment by mbasmanova** [comment]
@svm1 Since we need to match Presto's semantic, would you look into Presto's implementation and think about how this can be implemented in Velox?

**Comment by svm1** [comment]
@mbasmanova As I mentioned, Velox seems to currently be handling timezones with `TimeZoneDatabase.cpp` - this maps each timezone to a unique ID. There is no knowledge stored beyond this. 

I dug around the Presto implementation - it seems to be relying on a series of time-functions from external libraries, like `joda.time`, as well as some custom Java implementations. Specifically, the `ISODateTimeFormat` class from `joda.time` seems to have methods equipped that convert to ISO format while accounting for DST. The timestamp value passed in as a `long` appears to reserve some bits for the timezone, as a bitwise operation with a mask is used to extract the timezone from the input value. Passing this timezone into `joda.time`'s methods seems to generate an ISO string with a DST-included GMT offset.

I wasn't able to dig deeper into where/how exactly this DST logic is implemented in the library, as I haven't been able to setup a debug build to step through the function's execution and observe how the output is being constructed. Though from what I do see, our structure in Velox is certainly quite different. Looking into if any similar libraries may exist for C++.

**Pull request closed without merging**
