### PR TITLE
Switch boost site to archives.boost.io in setup-centos8.sh

### LINKED ISSUE #8207: Running scripts /setup-centos8.sh fails due to missing Boost dependency
### Problem description

Seems that https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz is not available: 
- https://github.com/boostorg/boost/issues/842 
- https://github.com/boostorg/boost/issues/843

Relevant part of `scripts /setup-centos8.sh`:
https://github.com/facebookincubator/velox/blob/523e561d3da99a78a33c4e22106ba7d1cf83c8a2/scripts/setup-centos8.sh#L69C16-L69C100

Would it please be possible to switch to https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz?

### System information

N/A

### CMake log

```bash
N/A
```

### PR DESCRIPTION
**Pull request by dcoliversun**
Change boost site from `boostorg.jfrog.io` to `archives.boost.io`

Resolves #8207

### CODE REVIEW

**Comment by dcoliversun** [comment]
cc @rz-vastdata I also test with sourceforge site, and error is here

```plain
+ wget_and_untar https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz boost
+ local URL=https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz
+ local DIR=boost
+ mkdir -p boost
+ wget -q --max-redirect 3 -O - https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz
+ tar -xz -C boost --strip-components=1

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by dcoliversun** [comment]
jfrog is restore, so close this pr

**Comment by rz-vastdata** [comment]
JFrog is down again :(
https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz

**Comment by dcoliversun** [comment]
@rz-vastdata Thanks for your reporting. Let's reopen this pr

**Comment by dcoliversun** [comment]
cc @majetideepak It would be nice if you have time to review this pr

**Review by majetideepak — APPROVED** [review]

**Review by kgpai — APPROVED** [review]

**Comment by dcoliversun** [comment]
@majetideepak  @kgpai Thanks for your review and please approve github action workflow :)

**Comment by majetideepak** [comment]
| please approve github action workflow

@dcoliversun this is not required for this change.

**Comment by czentgr** [comment]
This PR is not necessary anymore. The PR https://github.com/facebookincubator/velox/pull/8679 upgraded the Boost version is now using the source from github instead of downloading the archive. This aligns it with the source of the bundled version.
Thanks for bringing the issue up so a better source could be found.

**Pull request closed without merging**
