### PR TITLE
Upgrade DuckDB code to v0.8.0

### PR DESCRIPTION
**Pull request by isadikov**
This PR is to upgrade the inlined DuckDB code from `v0.4.1-dev344` to `v0.8.0` (https://github.com/duckdb/duckdb/tree/v0.8.0).

This addresses 
- https://github.com/facebookincubator/velox/issues/4350
- https://github.com/facebookincubator/velox/issues/4532
and potentially other similar issues.

The PR depends on https://github.com/facebookincubator/velox/pull/5162 since DuckDB does not have parquet-amalgamation script anymore.

I followed the instructions https://github.com/facebookincubator/velox/blob/main/velox/duckdb/README.md.

### CODE REVIEW

**Comment by mbasmanova** [comment]
> the newer DuckDB versions don't have scripts/parquet_amalgamation.py

We no longer need Parquet implementation from DuckDB, so all the related code can be deleted. CC: @kgpai

**Comment by majetideepak** [comment]
I filed https://github.com/facebookincubator/velox/issues/5108 to remove the bits for Parquet Reader over DuckDB.
@isadikov Do you want to work on this first?

**Comment by isadikov** [comment]
After that, I will try to upgrade directly to 0.8.0 then if we don't have dependency on Parquet.

**Comment by aditi-pandit** [comment]
> After that, I will try to upgrade directly to 0.8.0 then if we don't have dependency on Parquet.

@isadikov , @majetideepak : So Duckdb 0.8 also has some fixes for window functions (especially with empty frames). Let's move to that version if possible.

**Comment by isadikov** [comment]
Thanks Aditi. Yes, I will update to DuckDB 0.8.0.

**Comment by isadikov** [comment]
Apparently, amalgamation scripts are no longer officially supported: https://github.com/duckdb/duckdb/issues/8078.

**Comment by isadikov** [comment]
DuckDB does not support amalgamation script with splits and `duckdb-internal.hpp` files anymore (https://github.com/duckdb/duckdb/issues/8078). When I tried to use them and follow the steps in the wiki, I got a lot of errors in duckdb-internal.hpp related to the third-party dependencies `fmt` and `re2` - issue with namespaces, for example, max_value function was not visible under the same namespace. Removing those dependencies would result in renaming namespaces from duckdb_fmt to fmt and duckdb_re2 to re2.

I also tried to use a single duckdb.hpp and duckdb.cpp (without splits). However, I would get `error: incomplete type 'duckdb::TableCatalogEntry' named in nested name specifier` and similar errors. I added imports for duckdb.hpp and confirmed the class definition was there but I would still get the error.

The latter approach that I tried:
```sh
# generate files
cd duckdb && python3 scripts/amalgamation.py --extended
# delete the existing generated duckdb files
cd velox && rm velox/external/duckdb/duckdb*
# copy duckdb.hpp and duckdb.cpp
rsync -vrh src/amalgamation/duckdb* ${VELOX_PATH}/velox/external/duckdb/
...
```

I think maybe having single duckdb.hpp and duckdb.cpp files is the way to go, just need to figure out how to solve the `error: incomplete type 'duckdb::TableCatalogEntry' named in nested name specifier` error. However, I don't know how to fix it so any commnents would be appreciated.

**Comment by pedroerp** [comment]
This is a bummer. Having a single amalgamated files is problematic as it increases compilation time. Another option would be to have duckdb imported as a regular dependency (without amalgamation), but this would require more changes in the touch points between Velox and DuckDB code. But this might be the only option. 

Alternatively, we could look into what would it take to remove this dependency, at the cost of losing the differential testing we do for aggregates, joins and other operators. Cc: @mbasmanova @majetideepak

**Comment by pedroerp** [comment]
@isadikov would you like to raise this topic for discussion in the next monthly sync? Cc: @sanumandla

**Comment by aditi-pandit** [comment]
> @pedroerp
> 
> > Alternatively, we could look into what would it take to remove this dependency, at the cost of losing the differential testing we do for aggregates, joins and other operators.
> 
> I'm not sure that loosing differential testing is an option and I also don't think this can we discussed productively in a monthly sync. Let's create a GitHub discussion entry first.

@isadikov has left the Ahana team. GitHub discussion would be better.

**Pull request closed without merging**
