### PR TITLE
Simplify hasFilter condition by removing local condition

### PR DESCRIPTION
**Pull request by Yuhta**
Summary:
The local `hasFilter` should be consistent with
`ScanSpec::hasFilter()`.  Unify the two to reduce chance of future bugs.

Differential Revision: D45184859

### CODE REVIEW

**Comment by markjin1990** [comment]
@Yuhta Thanks for quickly adding this fix! With the current fix,  the previous one https://github.com/facebookincubator/velox/commit/0a8760ffd6fcb9633ae7a911b935018be42e6e2b is no longer needed, right? I run the unit test and the unit test succeeds without it.  In this case, shall we remove it? Since I am worried that the previous fix might cause performance regression.

**Comment by Yuhta** [comment]
@markjin1990 Yes we can remove that although I don't think the impact to performance is large in this case.  @zhejiangxiaomai Do you think it's safe to remove the `resetCachedValues` from `addSplit`?

**Comment by markjin1990** [comment]
@Yuhta Thanks for the reply!
> Actually I think that change could improve the performance in some cases by avoid allocating & copying `outputRows_`
This may be right in certain cases. However, I now kinda doubt whether it is worth to have `ScanSpec.hasFilter_` and `ScanSpec::resetCachedValues` to achieve a bit performance gain since it is not super clear when to use/refresh these caches and they might introduce bugs if misused.

**Comment by Yuhta** [comment]
@markjin1990 `ScanSpec::hasFilter_` is most likely needed as we cannot afford traversing the whole subtree every time we want to check if filter exists on one node.  In the reader tree we might be able to compute this on the fly, but the reordering of the filters also needs this state, and reordering can happen both inside the reader and outside reader (when a new filter is pushed down dynamically).

**Comment by markjin1990** [comment]
@Yuhta Got it! Thanks for the detailed explanation.

**Pull request closed without merging**
