### PR TITLE
Move VariantToVector to velox/vector (from velox/parse)

### PR DESCRIPTION
**Pull request by zhejiangxiaomai**

### CODE REVIEW

**Review by mbasmanova — APPROVED** [review]
@zhejiangxiaomai Thanks.

**Comment by zhejiangxiaomai** [comment]
@mbasmanova  some erros in "Facebook Internal - Linter", would you give me detail information?

**Comment by mbasmanova** [comment]
@zhejiangxiaomai I need to update buck files.

**Comment by zhejiangxiaomai** [comment]
> @zhejiangxiaomai I need to update buck files.

What should I do？

**Comment by mbasmanova** [comment]
I updated the buck files and waiting for the build and test to pass. Once it all is green I'll merge.

**Pull request closed without merging**
