### PR TITLE
Refactor substrait/CMakeLists.txt

### PR DESCRIPTION
**Pull request by mbasmanova**
- Move Protobuf compilation into substrait/proto/CMakeLists.txt
- Use protobuf_generate_cpp
- Modify macos-build CircleCI job to build code in substrait directory.

Also, refactor Substrait2VeloxPlanConversionTest for readability.

### CODE REVIEW

**Comment by mbasmanova** [comment]
CC: @rui-mo

**Comment by mbasmanova** [comment]
Let's add logic to check exit code and fail fast if the script didn't succeed: https://stackoverflow.com/questions/52076948/check-exit-status-of-execute-process-in-cmake

**Comment by kagamiori** [comment]
Hi @mbasmanova, I'm going to close this PR since it has been inactive for 90 days. Please feel free to reopen it if needed.

**Comment by rui-mo** [comment]
Hi @mbasmanova, is this refactor still needed? If yes, we are glad to help if needed. @zhejiangxiaomai

**Comment by mbasmanova** [comment]
@rui-mo I think this change is no longer needed. We could use help enabling Substrait tests in CircleCI and upgrading 'arg' to 'arguments' in checked in json files though.

**Pull request closed without merging**
