### PR TITLE
Fix the issue that the splits cannot be skipped for some special case

### PR DESCRIPTION
**Pull request by yingsu00**
In some rare case, the tables created by other engines would put the partition key columns in the data file too, and fail to write ColumnStats for such columns. In such case, the split from a partition with NULL partition keys failed to be skipped, causing wrong results. This is because HiveConnectorUtils::testFilters() assumes the partition keys are not in the data file, therefore is unable to apply the filter on the partition key. This commit fixes this issue by also checking the partition key list even when the partition columns are in the data file.

Unlike https://github.com/facebookincubator/velox/pull/9275, this PR doesn't modify the DwrfWriter to not to write ColumnStatistics, but uses a Parquet file from a null partition in a Spark generated Iceberg table.

### CODE REVIEW

**Review by Yuhta — APPROVED** [review]

**Comment by kgpai** [comment]
@yingsu00 Can you fix the conflict before I start the merge process ?

**Comment by majetideepak** [comment]
@yingsu00 can you rebase again? I will work with @kgpai to merge this.

**Comment by yingsu00** [comment]
@kgpai Sorry I forgot to tag you after I rebased and resolved the conflicts a few days ago. I have just rebased it again. cc @majetideepak

**Comment by kgpai** [comment]
@yingsu00 Can you confirm that the test failures are unrelated to your change ?

**Review by Yuhta — APPROVED** [review]

**Comment by majetideepak** [comment]
@kgpai the adapters test is now passing.

**Pull request closed without merging**
