### PR TITLE
Add null check for hdfs write handle in HdfsWriteFile

### PR DESCRIPTION
**Pull request by KevinyhZou**
This change is to address a comment from https://github.com/facebookincubator/velox/pull/3252

### CODE REVIEW

**Comment by KevinyhZou** [comment]
cc @xiaoxmeng @mbasmanova

**Review by mbasmanova — COMMENTED** [review]
@KevinyhZou Thanks. After this change, do we still need "Cannot flush HDFS file because file is not opened for write: {}" check? It seems it can never fail.

**Comment by KevinyhZou** [comment]
> @KevinyhZou Thanks. After this change, do we still need "Cannot flush HDFS file because file is not opened for write: {}" check? It seems it can never fail.

Yes, you are right. And I think we shoule remove the hdfs write handle whether open check.

**Review by mbasmanova — APPROVED** [review]
@KevinyhZou Thanks.

**Comment by mbasmanova** [comment]
@KevinyhZou Would you rebase this PR onto latest main so I could merge it?

**Comment by KevinyhZou** [comment]
> @KevinyhZou Would you rebase this PR onto latest main so I could merge it?

done

**Pull request closed without merging**
