### PR TITLE
Disable codegen with minimal build

### PR DESCRIPTION
**Pull request by majetideepak**
Codegen requires the Protobuf library. However, the expectation with the minimal build is that the Protobuf library should not be required. Therefore, we will disable codegen with the minimal build.

### CODE REVIEW

**Comment by majetideepak** [comment]
I hit the following build error without this fix.
```
FAILED: velox/experimental/codegen/utils/resources/package.json /Users/velox/_build/release/velox/experimental/codegen/utils/resources/package.json 
cd /Users/velox/_build/release/velox/experimental/codegen/utils/resources && python3 /Users/velox/velox/experimental/codegen/utils/resources/generatePackage.py --var-file /Users/velox/_build/release/velox/experimental/codegen/utils/resources/cmake_var_file.txt
Traceback (most recent call last):
  File "/Users/velox/velox/experimental/codegen/utils/resources/generatePackage.py", line 78, in <module>
    "defaultLibraries": [{f4d_libraries(cmake_vars)}, {additional_libraries(cmake_vars)}],
  File "/Users/velox/velox/experimental/codegen/utils/resources/generatePackage.py", line 33, in additional_libraries
    library_includes = {
  File "/Users/velox/velox/experimental/codegen/utils/resources/generatePackage.py", line 34, in <setcomp>
    '"' + cmake_vars[f"{name}_INCLUDE_DIR"] + '"' for name in library_names
KeyError: 'PROTOBUF_INCLUDE_DIR'
```

**Comment by mbasmanova** [comment]
@majetideepak Deepak, do we have a CicleCI job to signal this problem?

**Comment by majetideepak** [comment]
@mbasmanova I added a PR with minimal build on macos where we enable codegen by default. The run failed.
https://github.com/facebookincubator/velox/pull/1217

**Comment by mbasmanova** [comment]
> @mbasmanova I added a PR with minimal build on macos where we enable codegen by default. The run failed. #1217

Let's disable codegen.

**Review by mbasmanova — APPROVED** [review]

**Pull request closed without merging**
