### PR TITLE
Update dependencies of GCS

### LINKED ISSUE #8963: Dependencies of GCS have not been updated for nearly a year
### Description

Dependencies of GCS have not been updated for nearly a year, I propose to update them to the recommended versions as of Feb 2024.

### PR DESCRIPTION
**Pull request by tigrux**
Small change to update dependencies of GCS, that have not been updated in almost a year.
Fixes #8963.

### CODE REVIEW

**Comment by tigrux** [comment]
@majetideepak Hello, we are in the process of adding new connectors and the first step is to update GCS. Thanks.

**Review by majetideepak — APPROVED** [review]
@tigrux Changes look good! Can you share what the new connectors are?

**Comment by tigrux** [comment]
> @tigrux Changes look good! Can you share what the new connectors are?

Surely, we are planning to add support for Google BigQuery, and then enable it in Gluten as we did before we GCS.

**Comment by tigrux** [comment]
@kgpai Could you take a look at this PR please?
Thanks.

**Review by kgpai — APPROVED** [review]

**Review by Yuhta — APPROVED** [review]

**Pull request closed without merging**
