### PR TITLE
[WIP] Example of TPC-H q6 over Parquet files

### PR DESCRIPTION
**Pull request by mbasmanova**
This is an example of running TPC-H query 6 over Parquet files locally. 

The files were created using Presto:

```
CREATE TABLE t
WITH (format = 'PARQUET') AS
SELECT
    quantity,
    extendedprice,
    discount,
    CAST(shipdate AS VARCHAR) AS shipdate
FROM lineitem
```

The query plan is a TableScan -> PartialAggregation -> LocalExchange (N->1 or gather) -> FinalAggregation.

TableScan -> PartialAggregation -> LocalExchange runs as a separate pipeline with concurrency 4 (params.maxDrivers = 4) and processes 1 split per thread. 

FinalAggregation runs in a separate pipeline single-threaded.

I noticed that pushing down filters into the Parquet reader fails with 

`INTERNAL Error: Invalid PhysicalType for GetTypeIdSize`

My guess this is because the files have incomplete stats, e.g. min is set, but max is missing and the reader is not expecting this.

CC: @Mytherin @hannesmuehleisen @majetideepak @yingsu00

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
Can you send me a small parquet file that shows the issue please?

**Comment by mbasmanova** [comment]
@hannesmuehleisen Turns out that filter pushdown works just fine if we specify output columns in the same order they appear in the file. When we specify them out of order, e.g. shipdate, extendedprice, discount, quantity, we get an error: INTERNAL Error: Invalid PhysicalType for GetTypeIdSize

I wonder if this is because filter are specified for column indices. `quantity < 24` is specified for column 0, because quantity is the first column in the file. Could it be that this index is interpreted as an index of a column in the output? How would it work if a column is filter-only, is not projected out and therefore doesn't appear in the list of output columns.

**Comment by Mytherin** [comment]
> @hannesmuehleisen Turns out that filter pushdown works just fine if we specify output columns in the same order they appear in the file. When we specify them out of order, e.g. shipdate, extendedprice, discount, quantity, we get an error: INTERNAL Error: Invalid PhysicalType for GetTypeIdSize
> I wonder if this is because filter are specified for column indices. quantity < 24 is specified for column 0, because quantity is the first column in the file. Could it be that this index is interpreted as an index of a column in the output? How would it work if a column is filter-only, is not projected out and therefore doesn't appear in the list of output columns.

Indeed filters are specified relative to the columns in the projection list, the order of the columns in the file does not matter. So if your projection list is `shipdate, extendedprice, discount, quantity ` and you want to push a filter on `quantity`, it should be pushed on column 3 (no matter where quantity is located in the file). The error likely occurs because of an out-of-bounds read.

Pushing filters on columns not in the projection list is currently not supported yet.

**Comment by mbasmanova** [comment]
@Mytherin Mark, thank you for clarifying. We can update the integration to make sure that filter-only columns are specified in the output list and filters are defined on column indices relative to the output. In the future, it would be nice to support filter-only columns to save on materialization of the columns that are not needed further in the query.

**Comment by majetideepak** [comment]
Subsumed by https://github.com/facebookincubator/velox/pull/923

**Pull request closed without merging**
