### PR TITLE
Fix Spark build.

### PR DESCRIPTION
**Pull request by kgpai**
Spark Fuzzer builds break after recently landing https://github.com/facebookincubator/velox/pull/10357 and https://github.com/facebookincubator/velox/pull/10568 . This fixes it.

### CODE REVIEW

**Review by kevinwilfong — APPROVED** [review]
Thanks for the quick fix, LGTM as long as the CI builds work again.

**Review by rui-mo — COMMENTED** [review]
Thanks for the quick fix.

To work with https://github.com/facebookincubator/velox/pull/10568, an aggregate pool needs to be passed to the constructor, and the child pools are created by it. This commit added the needed changes: https://github.com/rui-mo/velox/commit/cadd1cd715d73f45ab44e99b218a0a922a465191. You may add them to this PR, or I can address this in another PR if you would like. Thanks.

**Comment by kgpai** [comment]
> To work with https://github.com/facebookincubator/velox/pull/10568, an aggregate pool needs to be passed to the constructor, and the child pools are created by it. This commit added the additional changes: https://github.com/rui-mo/velox/commit/cadd1cd715d73f45ab44e99b218a0a922a465191. You may add them to this PR, or I can address this in another PR if you would like. Thanks.

@rui-mo Lets create another PR for that.

**Comment by kgpai** [comment]
Macos failure is in uploading build artifacts for caching and not in the build, so should be safe to land.

**Pull request closed without merging**
