### PR TITLE
Prefix decimal value structs with Unscaled

### PR DESCRIPTION
**Pull request by karteekmurthys**
ShortDecimal and LongDecimal only store the unscaled decimal values.
To clarify this semantic, we add the prefix "Unscaled".

```
ShortDecimal -> UnscaledShortDecimal
LongDecimal -> UnscaledLongDecimal
```

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]

**Comment by majetideepak** [comment]
@karteekmurthys can you add a description?

**Comment by kgpai** [comment]
I am hoping to start work on this merging this latest by next Monday (Aug 15) , in case its not taken up by anyone else . Please reach out to me if you need this sooner.

**Comment by majetideepak** [comment]
@kgpai It will be great if we can get this merged sooner, before the presto_cpp deadline. This is a core but simple change where two decimal structs are renamed.
There is a corresponding PR on the presto_cpp side that you can use for mono-repo.
https://github.com/facebookexternal/presto_cpp/pull/833
You can ping us on Slack if you face any issues when merging this.

**Comment by majetideepak** [comment]
Thanks @kgpai

**Comment by kgpai** [comment]
Barring unforeseen circumstances, I should be able to merge this today

**Pull request closed without merging**
