### PR TITLE
Fix PartitionedOutput with round-robin partition function

### PR DESCRIPTION
**Pull request by mbasmanova**

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]
Thanks, Masha. I am also verifying this fix on the Presto side. Will update here.

**Review by tanjialiang — APPROVED** [review]
Thanks Masha for the fix

**Comment by majetideepak** [comment]
This PR fixes the Presto CI. I will advance Velox when this is merged.

**Review by xiaoxmeng — APPROVED** [review]
@mbasmanova thanks for the quick fix!

**Pull request closed without merging**
