### PR TITLE
CustomAdapter with operator replacement

### PR DESCRIPTION
**Pull request by karthikeyann**
Segfault during execution after operator replacement - Custom operators and Custom Bridge.

### CODE REVIEW

**Comment by karthikeyann** [comment]
Segfault while running velox_customdriver_test.
<details> 
<code>

root@cd1f0841424f:/velox# ./_build/release/velox/experimental/karthi/velox_customdriver_test 
Registering CustomJoinBridgeTranslator
Registering CustomDriverAdapter
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HashJoinTest
[ RUN      ] HashJoinTest.leftJoinWithMissAtEndOfBatch2
CustomJoinBridge replaced
Calling CompileState::compile
Number of operators: 3
  Operator: ID 0: Values[0] 0
  Operator: ID 1: HashProbe[2] 1
  Operator: ID 2: CallbackSink[N/A] 2
Number of plan nodes: 2
  Plan node: ID 0: -- Values[0]

  Plan node: ID 2: -- HashJoin[2]

operator[0]:  Operator: ID 0: Values[0] 0
operator[1]:  Operator: ID 1: HashProbe[2] 1
replaced HashProbe
operator[2]:  Operator: ID 2: CallbackSink[N/A] 2
Calling CompileState::compile
Number of operators: 2
  Operator: ID 0: Values[1] 0
  Operator: ID 1: HashBuild[2] 1
Number of plan nodes: 1
  Plan node: ID 1: -- Values[1]

operator[0]:  Operator: ID 0: Values[1] 0
operator[1]:  Operator: ID 1: HashBuild[2] 1
replaced HashBuild
*** Aborted at 1721102200 (Unix time, try 'date -d @1721102200') ***
*** Signal 11 (SIGSEGV) (0x18) received by PID 45290 (pthread TID 0x79a7ab7fe640) (linux TID 45359) (code: address not mapped to object), stack trace: ***
    @ 00000000035a2d91 _ZN5folly10symbolizer12_GLOBAL__N_113signalHandlerEiP9siginfo_tPv
                       /velox/_build/release/_deps/folly-src/folly/experimental/symbolizer/SignalHandler.cpp:453
    @ 000000000004251f (unknown)
    @ 0000000000097ef4 pthread_mutex_lock
    @ 000000000207284e _ZN15CustomJoinBuild11noMoreInputEv
    @ 00000000020a7822 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
    @ 00000000020a8d6c _ZN8facebook5velox4exec6Driver3runESt10shared_ptrIS2_E
    @ 00000000020a8f54 _ZN5folly6detail8function5call_IZN8facebook5velox4exec6Driver7enqueueESt10shared_ptrIS6_EEUlvE_Lb1ELb0EvJEEET2_DpT3_RNS1_4DataE
    @ 00000000035042ea _ZN5folly18ThreadPoolExecutor7runTaskERKSt10shared_ptrINS0_6ThreadEEONS0_4TaskE
                       /velox/_build/release/_deps/folly-src/folly/Function.h:370
                       -> /velox/_build/release/_deps/folly-src/folly/executors/ThreadPoolExecutor.cpp
    @ 00000000034e8105 _ZN5folly21CPUThreadPoolExecutor9threadRunESt10shared_ptrINS_18ThreadPoolExecutor6ThreadEE
                       /velox/_build/release/_deps/folly-src/folly/executors/CPUThreadPoolExecutor.cpp:350
    @ 000000000350aadc _ZN5folly6detail8function5call_ISt5_BindIFMNS_18ThreadPoolExecutorEFvSt10shared_ptrINS4_6ThreadEEEPS4_S7_EELb1ELb0EvJEEET2_DpT3_RNS1_4DataE
                       /usr/include/c++/11/bits/invoke.h:74
                       -> /velox/_build/release/_deps/folly-src/folly/executors/ThreadPoolExecutor.cpp
    @ 00000000000dc252 (unknown)
    @ 0000000000094ac2 (unknown)
    @ 0000000000125a03 clone
Fatal signal handler. Query Id=  Task Id= test_cursor 1
Segmentation fault (core dumped)
</code>
</details>

**Comment by Yuhta** [comment]
@karthikeyann It's probably a nullptr somewhere, can you debug and find out which value is nullptr?

**Comment by karthikeyann** [comment]
@Yuhta The nullptr arises because `HashJoinBridge` object is returned by `getCustomJoinBridge` call instead of `CustomJoinBridge`. The bridge created from translators() is not stored in the map `SplitGroupState::bridges`, because `HashJoinNode`'s corresponding `HashJoinBridge` object is already stored there. So, `getCustomJoinBridge`  returns `HashJoinBridge` object and dynamic cast creates a nullptr.
Even if we use `insert_or_assign` instead of `emplace`, it will cause problem during initialization of `HashProbe` and `HashBuild` operators, which expects `HashJoinBridge` object.

Solutions considered:
1. considered using a multimap for `SplitGroupState::bridges`, but it may still return `HashJoinBridge`, instead of custom join bridge. (both are derived from `JoinBridge`).

2. added another map `SplitGroupState::custom_bridges` and added a few methods. It solved the problem, but velox bridges and translator bridges are separated.

**Comment by Yuhta** [comment]
@karthikeyann Thanks for the investigation.  I am curious why this line is not triggered?  https://github.com/facebookincubator/velox/blob/8e0181ef723854b438b8e56d72bf87cb0cb51333/velox/exec/Task.cpp#L1827-L1830

I think adding `custom_bridges` makes sense.  Can you separate 7dd75b00e795fd69c32eb9cc47e126558443ee47 to a PR?  You should pass the map as parameter for some underlying implementation functions to remove duplicates.  Also add some check to make sure we don't overwrite the same key on the map.

**Comment by karthikeyann** [comment]
That line is not triggered because `getCustomJoinBridge` calls `getJoinBridgeInternal<TBridgeType=JoinBridge>`, since all join bridges including custom bridges are derived from `JoinBridge`, dynamic cast creates non-null ptr, and that line is not triggered.

**Comment by Yuhta** [comment]
@karthikeyann We need to make sure we don't even try to overwrite an existing key.

**Pull request closed without merging**
