### PR TITLE
Upgrade GTest submodule to 1.11 (from 1.10)

### PR DESCRIPTION
**Pull request by kagamiori**
Summary: This PR fixes the build failure when using MacOSX12.3.sdk. 

First, there is a compilation error in the source code of GTest ver 1.10, so we upgrade the GTest submodule to ver 1.11.

The upgrade to GTest  1.11 then triggers another compilation error coming from `velox::Tree`. The error is caused by `velox::Tree::cbegin()` trying to construct a `velox::TreeIterator` with a `const velox::Tree<T>` object, but velox::TreeIterator's constructor expects a `const velox::Tree<const T>`. And there is no known conversion from `const velox::Tree<T>` to `const velox::Tree<const T>`. So we remove the inner "const" from `const velox::Tree<const T>`.

In addition, `std::result_of` is depreciated in MacOSX12.3.sdk. So we replace `std::result_of` with `std::invoke_result` in Velox source code. The compiler also complains that the implicit copy assignment operator for `CompilerOptions` is disabled because it has a user-declared copy constructor. So we add the default copy assignment operator for `CompilerOptions` as well.

Differential Revision: D35293292

### CODE REVIEW

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by majetideepak** [comment]
Should we update the googletest submodule in a separate PR?

**Comment by mbasmanova** [comment]
> Should we update the googletest submodule in a separate PR?

I'll let @kagamiori reply, but my understanding is that upgrading breaks the build, e.g. we can't just upgrade without changing any code.

**Comment by majetideepak** [comment]
ah! then please update the PR description about the googletest upgrade.

**Comment by kagamiori** [comment]
> Should we update the googletest submodule in a separate PR?
Hi @majetideepak, Thank you for asking! The context is that I upgraded Mac OS last week and the build suddenly broke with MacOSX12.3.sdk. There were some errors from GTest 1.10, so I upgrade it to 1.11 in this PR. The upgrade to GTest 1.11, however, triggered another compilation error coming from `velox::Tree` and `velox::TreeIterator`, so I fix that in this PR as well. In addition, there were also two other errors from the Velox code base about the use of std::result_of and a copy assignment operator of CompilerOptions, so I fixed them all together.

I've updated the title and description. Please let me know if you have any suggestions!

**Comment by mbasmanova** [comment]
@kagamiori Thank you, Wei. I suggest to use slightly different format for the Upgrade messages where "to" comes first (most important) and "from" coming after (still important, but not as much as "to"):

Upgrade GTest submodule to 1.11 (from 1.10)

**Review by mbasmanova — APPROVED** [review]

**Pull request closed without merging**
