### PR TITLE
Remove dependency on RLEv1 and v2 from IntDecoder and IntEncoder 

### PR DESCRIPTION
**Pull request by yingsu00**
IntDecoder will be moved to dwio::common, but its member functions createRle and createDirect need to reference RLEv1 and RLEv2. This PR moves the decoder creation from IntDecoder to the new DecoderUtil.h to prepare for the upcoming moves. In addition, the encoder creation from IntEncoder was moved out to EncoderUtil.h to keep the encoder creation in the same manner..

### CODE REVIEW

**Comment by yingsu00** [comment]
@HuamengJiang will you be able to review this PR? It'll be very appreciated!

**Comment by yingsu00** [comment]
Updated the include ordering as proposed in https://github.com/facebookincubator/velox/issues/1918

**Comment by weizheng10** [comment]
Hi, Ying:

Due to recently committed changes, this pull request need to be rebased. I could have fixed everything internallybut we will not be able to export it to github and get that validated using cmake.  The changes caused by rebasing are not big, but it is also not trivial enough for me to assume it won't cause problem when validated using cmake in github.

Could you please rebase it and then I will import and land it?

Thank you very much!

**Comment by weizheng10** [comment]
@yingsu00 

Forgot to add "@" in my last message. 

Thanks!

**Comment by yingsu00** [comment]
This PR was included in PR #1865

**Pull request closed without merging**
