### PR TITLE
[Do n ot review] Add HashTable based window partitioning

### PR DESCRIPTION
**Pull request by aditi-pandit**
For Window operator the most performance critical code path is partitioning and sorting the input rows as per the Window function partitioning spec.

There are multiple algorithms to fine tune the window partitioning build step. e.g. A single sort across all the input rows with (partition keys + sort keys) combination (the current implementation). Another strategy used by Spark assumes a sorted input stream from a prior step and simply identifies partition key column changes to build the Window partitions.

A third strategy is to use a HashTable to identify the partitions. There is extra work to compute a hash value for partition keys for each row. But the advantages of this approach are :

- The sorts of partitions are self-contained within each partition.
- Each partition rows are kept pre-sorted in a priority queue so a massive sort after noMoreInput is not required.
- Removing this sort eliminates a computationally expensive and blocking step in the Window operator logic. 
 
This makes the runtime more efficient and robust. The benchmark run shows that even with basic runs HashWindowBuild performs as well as SortWindowBuild. https://gist.github.com/aditi-pandit/b519b29083f8ba82167629f12b805c21

Implementation :
The Window operator code is modularized to abstract a WindowBuild class to plug these different algorithms. This PR implements a HashWindowBuild that splits input data into partitions using a HashTable. Each partition entry in the HashTable maintains a priority queue of the row pointers ordered as per the ORDER BY spec of the partition.

The HashWindowBuild is used with WindowNode.useHashBuild is set. Ideally, the HashWindowBuild should be used by default.

Note: The HashWindowBuild needs to be enhanced for spilling.

### CODE REVIEW

**Comment by mbasmanova** [comment]
> The benchmark run shows that even with basic runs HashWindowBuild performs as well as SortWindowBuild. https://gist.github.com/aditi-pandit/b519b29083f8ba82167629f12b805c21

This sounds like the perf of two implementations is the same. Is this the case? If there are no perf gains for HashWindowBuild, they why would we want to use it?

**Comment by aditi-pandit** [comment]
> > The benchmark run shows that even with basic runs HashWindowBuild performs as well as SortWindowBuild. https://gist.github.com/aditi-pandit/b519b29083f8ba82167629f12b805c21
> 
> This sounds like the perf of two implementations is the same. Is this the case? If there are no perf gains for HashWindowBuild, they why would we want to use it?

@mbasmanova : I high-lighted those results to indicate that HashTable wasn't bringing regressions. It does cause speedup broadly as well. I'll get some benchmark numbers showing that.

**Comment by waitinfuture** [comment]
Hi @aditi-pandit , is there any update for this PR? Thanks :)

**Comment by aditi-pandit** [comment]
> Hi @aditi-pandit , is there any update for this PR? Thanks :)

Hi @waitinfuture, I had suspended work on this to improve its performance further. But HashTable has had many perf improvements since. I can rebase this code to work on it again.

Any particular reason you are asking about this PR ?

**Comment by waitinfuture** [comment]
> > Hi @aditi-pandit , is there any update for this PR? Thanks :)
> 
> Hi @waitinfuture, I had suspended work on this to improve its performance further. But HashTable has had many perf improvements since. I can rebase this code to work on it again.
> 
> Any particular reason you are asking about this PR ?

@aditi-pandit Thanks for your reply, in one of our tests the sorting in window operator takes long time (single partition with lots of data), then I looked into the code and found this PR, you mentioned in your experiment HashWindowBuild has broad speedup, I think this can be helpful.

**Comment by aditi-pandit** [comment]
> > > Hi @aditi-pandit , is there any update for this PR? Thanks :)
> > 
> > 
> > Hi @waitinfuture, I had suspended work on this to improve its performance further. But HashTable has had many perf improvements since. I can rebase this code to work on it again.
> > Any particular reason you are asking about this PR ?
> 
> @aditi-pandit Thanks for your reply, in one of our tests the sorting in window operator takes long time, then I looked into the code and found this PR, you mentioned in your experiment HashWindowBuild has broad speedup, I think this can be helpful.

Thanks @waitinfuture 

Will rebase this PR with the latest code and do a new benchmark run. 

Though there are some more design points to work through. 
i) SortWindowBuild might still do better than its current state when enhanced with prefix-sort. Also Presto can determine if the window was pre-sorted on some subset of the keys improving numbers further. Ideally, we should switch between sort and Hash based on these criteria.
ii) SortWindowBuild supports spilling. Add spilling support for HashWindowBuild. In general, I think if the query does require a spill, then Hash spill is likely to be better than Sort spill.

Lets sync on 5/28 about this.

**Comment by waitinfuture** [comment]
Thanks @aditi-pandit for detailed explanation.
i) I believe prefix-sort can improve performance, and using StreamingWindowBuild for pre-sorted data can improve further. Making it adaptive according to data characteristics is great.
ii) Currently SortWindowBuild don't support spill after noMoreInput. I think HashWindowBuild may support this easier.

Unfortunately the job I mentioned is from one of our customers and it's hard to test again, but I can make a job that has similar characteristics based on TPCDS data.

**Comment by HolyLow** [comment]
@aditi-pandit I have some optimization suggestions that you might consider. 
1. Do not use priority queue to store and sort the rows. In TopNRowNumber's implementation, we use a priority queue because only N rows are needed for each partition, and using a priority queue helps to eliminate the unnecessary rows at runtime. However, in Window's case, all the rows are needed for each partition, so using a priority queue brings nothing good. By contrast, the performance of continuously pushing and popping elements from a priority queue could be poor, especially when the comparison is carried out by the multi-column data pointed by pointers and uses multiple comparators over multiple columns.
2. Instead, store the rows in a vector or something like a linked list (by adding a row as linker in RowContainer, maybe), and when we are going to get the result of a partition, we could list all the rows of the partition and sort them together with whatever sorting algorithm we like, including prefixSort. In this way we could take advantage of the optimized sorting methods.
3. I think gaining performance improvement in HashWindow should not be hard as the algorithmic advantages of hashing over sort and reduced sorting columns(the partitioning columns are no longer sorted), but the disadvantage of HashWindow would be the memory consumption. Using a hash table could consume a great amount of memory compared with sorting. Maybe we should accumulate all the data, compute or estimate the cardinality of the partition columns to decide whether to use hash method or sort method. This auto decision would make Window faster and more robust.

**Comment by aditi-pandit** [comment]
@HolyLow : Agree that priority_queue brings inefficiencies and I'm open to changing the data structure there.

i'd been debating the tipping point to go from sort -> hash window building since sort is quite efficient for large number of small partitions case. Going with the approach in https://www.vldb.org/pvldb/vol8/p1058-leis.pdf where they use a small number of hash partitions would be good I feel.

**Pull request closed without merging**
