### PR TITLE
upgrade fbos dependencies to v2024.04.01.00 (from v2024.02.26.00)

### PR DESCRIPTION
**Pull request by czentgr**

### CODE REVIEW

**Comment by czentgr** [comment]
Fixes issue https://github.com/facebookincubator/velox/issues/9339

**Review by assignUser — APPROVED** [review]
Thanks for the fix! LGTM, the fuzzer fail seems unrelated but best that someone with domain knowledge has a look.

**Comment by czentgr** [comment]
I've created https://github.com/facebookincubator/velox/issues/9376 to record the failure. Unfortunately, the iteration seed is not printed to the log - maybe an additional bug/issue - and so I can't check with the old version to see if it is related to the new fbos version.

I also checked that gcc11 is good with the selected version. When the velox submodule is updated in prestissimo proxygen needs to be updated and use this version.

@kgpai FYI

**Comment by pedroerp** [comment]
Thank you guys

**Comment by czentgr** [comment]
@pedroerp Thank you! When this lands I will update the velox submodule in prestissimo and ensure proxygen is updated then as well to avoid issues. I have a PR to update proxygen in prestissimo to match the (soon outdated) version.

**Review by majetideepak — APPROVED** [review]

**Review by kgpai — APPROVED** [review]

**Pull request closed without merging**
