### PR TITLE
Fix VectorPool for custom types

### PR DESCRIPTION
**Pull request by mbasmanova**
VectorPool used to keep a cache of vectors keyed by TypeKind. Hence, it could
not distinguish between types that have the same TypeKind and could return a
vector of type VARCHAR when requested a vector of type JSON.

This change is to use raw Type pointer as a cache key and limit the supported
types to singleton built-in types like BIGINT and VARCHAR. Decimal, fixed-width
array, complex and custom types are not supported.

In the future, we may add support for custom singleton types by changing the 
type registry to know which custom types are singleton types.

### CODE REVIEW

**Comment by majetideepak** [comment]
@mbasmanova any reason not to use a `typeid` for the cache key?

**Comment by mbasmanova** [comment]
> @mbasmanova any reason not to use a `type_index(typeid(type))` for the cache key?

@majetideepak That's a good question. Generally speaking type_index does not fully describe the Type. For example, two decimal types with different precision and scale have same type_index. I'm using TypeKind because it allows me to use a simple array instead of a hash table for storing the caches. I initially tried F14HashMap<Type*, TypePool>, but saw a perf regression on a Preproc benchmark. Hence, changed back to using an array.

**Comment by majetideepak** [comment]
Good point on decimals. Could we generate a unique hash value based on precision, scale for decimals, fixed-width arrays, etc., and add it to the key? We should be able to hash complex types as well.
Alternatively, we could keep an exclude list with Decimal, fixed-width array, complex. With type_index we can at least allow custom types.

**Comment by mbasmanova** [comment]
> Good point on decimals. Could we generate a unique hash value based on precision, scale for decimals, fixed-width arrays, etc., and add it to the key? We should be able to hash complex types as well. 

This should be possible, but we'll need to make sure the implementation is performant. As I mentioned earlier, just using F14FastMap<Type*, TypePool> caused perf regressions and I had to switch batch to using an array.

> With type_index we can at least allow custom types.

Custom types may not be singletons, hence, using type_index alone would not be sufficient.

**Comment by majetideepak** [comment]
Thanks for the clarification.

**Pull request closed without merging**
