### PR TITLE
Add xsimd as dependency

### PR DESCRIPTION
**Pull request by kgpai**

### CODE REVIEW

**Comment by majetideepak** [comment]
I hope this is the last submodule after which users get to choose between external dependencies vs. submodules :).

**Comment by pedroerp** [comment]
> I hope this is the last submodule after which users get to choose between external dependencies vs. submodules :).

I think the intent is to move all (or most) dependencies to submodules to follow PyTorch's model. Is there any reason why we would prefer external dependencies over submodules?

**Comment by majetideepak** [comment]
Using submodules, which essentially means the third-party applications are always built as part of Velox, is not portable.
Just a single `googletest` submodule broke a couple of platforms. See https://github.com/facebookincubator/velox/issues/1369 and https://github.com/facebookincubator/velox/issues/1339.
Users who build with `-Werror` will find it impossible to build Velox since most of the third-party dependencies are not C++17 compatible including thrift. One such unavoidable issue was mentioned here https://github.com/facebookincubator/velox/issues/1286 and patched.

**Comment by wenleix** [comment]
> Using submodules, which essentially means the third-party applications are always built as part of Velox, is not portable.
Just a single googletest submodule broke a couple of platforms. See https://github.com/facebookincubator/velox/issues/1369 and https://github.com/facebookincubator/velox/issues/1339.

@majetideepak The root cause is because GTest 1.10 doesn't built on later version of clang -- this is also a problem even install GTest 1.10 as deps (users need to install GTest 1.11 instead). So no matter GTest is used as a submodule or dependencies, it needs to bumped to 1.11. In fact https://github.com/facebookincubator/velox/pull/1319 tries to bump GTest as deps to 1.11 as well, but get landing time conflict with the moving to submodule PR.

**Comment by majetideepak** [comment]
@wenleix Using submodules is not the problem here. But we cannot assume specific third-party library versions pinned by these submodules will work for everyone. We need to give users the flexibility to choose third-party versions. 
As we observed with GTest, the build issues are not the same across different platforms. 
As noted here https://github.com/facebookincubator/velox/issues/1369, I had GTest 1.10 already installed and Velox using GTest 1.11 caused conflicts.
Even GTest 1.11 is not sufficient since it does not have a patch that removes -Werror that got merged later. https://github.com/google/googletest/commit/f7902802f1a61140e188223fb6d1c95925cbec4a
Also, building all the third-party dependencies for every build is inefficient if they are already built on the platform. Velox must provide a way to re-use external dependencies if they are already built.

**Comment by pedroerp** [comment]
> Velox must provide a way to re-use external dependencies if they are already built.

Is it something that should be handled by our cmake? Something like: if you find a suitable version of gtest in the system, use it; otherwise, resolve the submodule and install the pinned version known to be compatible.

> But we cannot assume specific third-party library versions pinned by these submodules will work for everyone. We need to give users the flexibility to choose third-party versions.

I'm a bit confused by this. Wouldn't pinning libraries to a specific version be more reliable, as we can ensure that these are the exact versions we exercise in CI, but giving users more flexibility would make things harder because users might end up using a version or some specific compilation options that are not compatible with Velox?

**Comment by majetideepak** [comment]
> I'm a bit confused by this. Wouldn't pinning libraries to a specific version be more reliable, as we can ensure that these are the exact versions we exercise in CI

You are right here. The submodules should be pinned to specific versions that we test on CI. My argument about the flexibility of third-party versions is only to support external dependencies. Specific versions will not work for everyone and allowing external dependencies will resolve this.

> Is it something that should be handled by our cmake?

Yes. The ideal solution should be that CMake should try finding the packages and if some packages are missing, it will build the known compatible version. The standard way is via `ExternalProject_Add`.

**Comment by wenleix** [comment]
> I'm a bit confused by this. Wouldn't pinning libraries to a specific version be more reliable, as we can ensure that these are the exact versions we exercise in CI, but giving users more flexibility would make things harder because users might end up using a version or some specific compilation options that are not compatible with Velox?

+1 on this. This actually makes easier to test and guarantee all the developers has the same experience (otherwise, users may have compilation error due to they compile dependency with different version and different compiler, etc)

Especially, when users need to build multiple libraries (e.g. TorchArrow + TorchText/TorchRec, having different library needs to be installed (and may be different version)) basically make thing impossible. 

> Also, building all the third-party dependencies for every build is inefficient if they are already built on the platform. Velox must provide a way to re-use external dependencies if they are already built.

Doesn't CCache make re-use already built dependencies (from cache perspective? )

**Comment by majetideepak** [comment]
> Doesn't CCache make re-use already built dependencies (from cache perspective? )

Yeah, ccache will help with the re-use of dependencies across builds as well.

**Pull request closed without merging**
