### PR TITLE
Bump protobuf min version and relax version specifier

### PR DESCRIPTION
**Pull request by assignUser**
Fixes: #3136 and improves issues with the EXACT version called out in #10113

### CODE REVIEW

**Review by majetideepak — APPROVED** [review]
Thanks, @assignUser

**Review by kgpai — APPROVED** [review]

**Comment by rui-mo** [comment]
Shall we also update the protobuf version in setup-adapters.sh? Thanks.
https://github.com/facebookincubator/velox/blob/main/scripts/setup-adapters.sh#L77

**Comment by assignUser** [comment]
@rui-mo ah, I missed it in centos9.sh but it shouldn't be in adapters actually as that is supposed to be run in addition to the base script so we should remove it. Do you want to open a PR?

**Comment by rui-mo** [comment]
@assignUser Thanks for the pointer. I'm glad to open a PR for that.

**Pull request closed without merging**
