### PR TITLE
Fix setup-centos8 script to use pip3.9

### PR DESCRIPTION
**Pull request by majetideepak**
Use pip3.9 to install packages since python39-pip is installed.

### CODE REVIEW

**Comment by assignUser** [comment]
does `pip3` not default to the newest installed pip version or change based on `alternatives`(which I guess I didn't chang? anther reason to use `python3 -m pip ...`)

**Comment by majetideepak** [comment]
The setup script itself does not use alternatives. I invoked the script on a clean centos8 container and I got pip3 command not found.

**Comment by majetideepak** [comment]
I guess it is not clean after all
```
# alternatives --display python3
python3 - status is auto.
 link currently points to /usr/bin/python3.11
/usr/bin/python3.11 - priority 31100
 slave easy_install-3: (null)
 slave pip-3: (null)
 slave pip3: (null)
 slave pydoc-3: /usr/bin/pydoc3.11
 slave pydoc3: /usr/bin/pydoc3.11
 slave python3-config: (null)
 slave pyvenv-3: (null)
 slave python3-man: /usr/share/man/man1/python3.11.1.gz
/usr/bin/python3.9 - priority 3900
 slave easy_install-3: /usr/bin/easy_install-3.9
 slave pip-3: /usr/bin/pip-3.9
 slave pip3: /usr/bin/pip3.9
 slave pydoc-3: /usr/bin/pydoc3.9
 slave pydoc3: /usr/bin/pydoc3.9
 slave python3-config: /usr/bin/python3.9-config
 slave pyvenv-3: (null)
 slave python3-man: /usr/share/man/man1/python3.9.1.gz
Current `best' version is /usr/bin/python3.11.

```

**Comment by majetideepak** [comment]
`python3 -m pip` says
```
/usr/bin/python3: No module named pip
```

**Comment by majetideepak** [comment]
Is it not safe to use `pip3.9` in the presence of other versions?

**Comment by assignUser** [comment]
> Is it not safe to use pip3.9 in the presence of other versions?

Oh no it should, I was just wondering. But of course I only touch `alternatives` in the docker image so this makes sense! Sorry for the confusion^^

**Review by assignUser — APPROVED** [review]

**Pull request closed without merging**
