### PR TITLE
Reduce CI Linux build link parallelism

### PR DESCRIPTION
**Pull request by majetideepak**

### CODE REVIEW

**Comment by majetideepak** [comment]
Temporary fix to resolve CI build failures.

**Review by kgpai — APPROVED** [review]

**Comment by mbasmanova** [comment]
@majetideepak Thank you for fixing the build. Looks good to me. It would be nice to describe the change in more details in the PR description, e.g. explain the motivation and clarify what was the number of concurrent jobs before and what it is now. Also, would be nice to explain what's the impact on build times.

**Comment by majetideepak** [comment]
@mbasmanova I wasn't sure between this and https://github.com/facebookincubator/velox/pull/880.
I will check the CI jobs and update the description with more details.

**Comment by majetideepak** [comment]
Updated the description

**Pull request closed without merging**
