### PR TITLE
Fix bundled build linking failure with Parquet ON

### PR DESCRIPTION
**Pull request by nmahadevuni**
Fixes https://github.com/facebookincubator/velox/issues/6744

### CODE REVIEW

**Comment by majetideepak** [comment]
@nmahadevuni, can you explain the fix? I only see a new CI job here.

**Comment by nmahadevuni** [comment]
> @nmahadevuni, can you explain the fix? I only see a new CI job here.

Sorry, its WIP. Was building without fix to see it fails with the same error. Will update with the fix soon

**Comment by nmahadevuni** [comment]
@majetideepak The linux build option I added fails in 25 mins with `collect2: fatal error: ld terminated with signal 9 [Killed]`. Can't find the reason anywhere. The timeout is 1 hour. Any idea what's happening here?

**Comment by majetideepak** [comment]
> collect2: fatal error: ld terminated with signal 9 [Killed]

@nmahadevuni This is likely due to the linker not having enough memory. Reduce the number of parallel link jobs.

**Comment by nmahadevuni** [comment]
> > collect2: fatal error: ld terminated with signal 9 [Killed]
> 
> @nmahadevuni This is likely due to the linker not having enough memory. Try reducing the number of parallel link jobs.

Thanks. I have removed the CI job commit. Its a very long job too. I verified it building locally that the fix works. Can you review this?

**Pull request closed without merging**
