### PR TITLE
fix: Fix Macos build

### PR DESCRIPTION
**Pull request by jinchengchenghh**
Fix https://github.com/facebookincubator/velox/actions/runs/12344726488/job/34447696056?pr=11497

### CODE REVIEW

**Review by xiaoxmeng — APPROVED** [review]
@jinchengchenghh thanks for the quick fix!

**Comment by zuyu** [comment]
Same as my PR #11858

**Comment by jinchengchenghh** [comment]
OK, I will close this.

**Comment by jinchengchenghh** [comment]
Not

**Pull request closed without merging**
